$axure.loadCurrentPage({
  "url":"添加新闻.html",
  "generationDate":new Date(1383013849348.13),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a0d2e4a3dc384a208dd35c2c23d56f84",
    "type":"Axure:Page",
    "name":"添加新闻",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c7e851678e44470baa5d580feb695130",
          "label":"导航",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":50},
            "size":{
              "width":716,
              "height":129}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"21f5831231714ed383b11e2e8e5883b2",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"663575d23b9749debb9679275d60bd26",
                  "label":"",
                  "parentDynamicPanel":"c7e851678e44470baa5d580feb695130",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":90,
                      "y":7},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b0f2ba19542245adb849d3db81b36f7b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c7e851678e44470baa5d580feb695130",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":90,
                          "y":7},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"e5b2c1945f294849900fda6e84d88311",
                  "label":"",
                  "parentDynamicPanel":"c7e851678e44470baa5d580feb695130",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":300,
                      "y":7},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"aaf797a31a284a15bac09ea3f8c31ae0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c7e851678e44470baa5d580feb695130",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":300,
                          "y":7},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"30c8e2f7132d44a1aafbf854688f7309",
                  "label":"",
                  "parentDynamicPanel":"c7e851678e44470baa5d580feb695130",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":407,
                      "y":7},
                    "size":{
                      "width":79,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d9f0e8c52513441b8252032ab4cbf9b7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c7e851678e44470baa5d580feb695130",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":407,
                          "y":7},
                        "size":{
                          "width":79,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"734212e032b745928eafaca6372a81e8",
                  "label":"",
                  "parentDynamicPanel":"c7e851678e44470baa5d580feb695130",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":542,
                      "y":7},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f6df676e4bce4fc49957f9d79f79cf49",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c7e851678e44470baa5d580feb695130",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":542,
                          "y":7},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"8ee6d777f1764cfa90cd4e5bac50fdc2",
                  "label":"",
                  "parentDynamicPanel":"c7e851678e44470baa5d580feb695130",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":637,
                      "y":7},
                    "size":{
                      "width":79,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"efe908e61642497d9e5c8b47f8d430b3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c7e851678e44470baa5d580feb695130",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":637,
                          "y":7},
                        "size":{
                          "width":79,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"a8306e41386b4801807b303b85a9eddc",
                  "label":"",
                  "parentDynamicPanel":"c7e851678e44470baa5d580feb695130",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":22},
                    "size":{
                      "width":1000,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/修改密码_1/u21_line.png"}},
{
                  "id":"c84e77cd87d44474916c6d063e573f3e",
                  "label":"",
                  "parentDynamicPanel":"c7e851678e44470baa5d580feb695130",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF5E5E5E,
                      "opacity":1},
                    "location":{
                      "x":68,
                      "y":1},
                    "size":{
                      "width":97,
                      "height":27},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bbe4a5ffd2bb4133a9eb42d120484c94",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c7e851678e44470baa5d580feb695130",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF5E5E5E,
                          "opacity":1},
                        "location":{
                          "x":68,
                          "y":1},
                        "size":{
                          "width":97,
                          "height":27},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onMouseOver":{
                      "description":"OnMouseOver",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 ",
                              "objectsToFades":[]}]}]},
                    "onMouseOut":{
                      "description":"OnMouseOut",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 ",
                              "objectsToFades":[]}]}]}},
                  "images":{
                    "normal~":"images/新闻管理/u12.png"}},
{
                  "id":"72e4c84e707f4792a8c1cd3312c9d3aa",
                  "label":"",
                  "parentDynamicPanel":"c7e851678e44470baa5d580feb695130",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "location":{
                      "x":165,
                      "y":7},
                    "size":{
                      "width":115,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7310a56fe805417f8d7a252662b3b1e3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c7e851678e44470baa5d580feb695130",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "location":{
                          "x":165,
                          "y":7},
                        "size":{
                          "width":115,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"c60d0b20ccf74444b3f9cc982d672858",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":170,
              "height":51}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"80984ef1d00c49399d6a8d17352eb55b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":170,
                  "height":51}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改密码_1/u0.jpg"}},
{
          "id":"1445bb1b19564d11bfa95b951f74832d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":105},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d21000f9c1b0433a8475a91f44f7d499",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":48,
                  "y":105},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8e1a6db02b164adeb73f92457af82b06",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":33,
              "y":101},
            "size":{
              "width":86,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9b72f552f6c432cbc7bd9907c053715",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":33,
                  "y":101},
                "size":{
                  "width":86,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9938e52469104831947e4f77512e781a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":132,
              "y":101},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"317728b392b049f9adc3c0fef5a4fc45",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":132,
                  "y":101},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"33b8bd2237aa4c189a2db77e388204b8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":598,
              "y":4},
            "size":{
              "width":148,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1293eddbc134cdf831b469ed8ad00a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":598,
                  "y":4},
                "size":{
                  "width":148,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a35b98c7741c4e858b350befb62ca314",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":903,
              "y":4},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b82c0b6f03d646798af37fc76138510b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":903,
                  "y":4},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 后台登录",
                      "target":{
                        "targetType":"page",
                        "url":"后台登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b1848780c7e54078839c049d308a6839",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":828,
              "y":4},
            "size":{
              "width":88,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bd2648f8cee403db79837a84c9ac00c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":828,
                  "y":4},
                "size":{
                  "width":88,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 修改密码",
                      "target":{
                        "targetType":"page",
                        "url":"修改密码_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"06005e63de5847bbb28717657defb48d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":756,
              "y":4},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8dadd6d4dfd44ff4a5bd6ea7681204fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":756,
                  "y":4},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c43e79d51f144515aab51862af375255",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":79,
              "y":149},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d454c12326ad45979aad5cd57b80cb79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":79,
                  "y":149},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d389c12d214e415693fb71564862a720",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":117},
            "size":{
              "width":946,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF949494}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/修改密码_1/u24_line.png"}},
{
          "id":"b813678148ab4b769bd796b17fd2fa1d",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":143,
              "y":145},
            "size":{
              "width":477,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"71e1f102007d46878eebd0a642818a44",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":143,
              "y":340},
            "size":{
              "width":477,
              "height":210}},
          "adaptiveStyles":{
}},
{
          "id":"4589a10dcbf94aa3b62c431436d090fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":79,
              "y":320},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69f36baa403f42e28ad0db3d6b146c96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":79,
                  "y":320},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6555b200261e428dba7f988e2a727004",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":53,
              "y":273},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9a1df78fa244d50b2757aa7713fbb6a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":53,
                  "y":273},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"86b5bc2bff33457984d84679ad2ad67f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":143,
              "y":315},
            "size":{
              "width":361,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4fca03aa552b42f6932c9fefd73dafbf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":143,
                  "y":315},
                "size":{
                  "width":361,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加新闻/u41.png"}},
{
          "id":"3b5b9f2389014f68857b652d6700cefd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":72,
              "y":234},
            "size":{
              "width":58,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cce7f94d8f194dee9b8e7c0e738dc063",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":72,
                  "y":234},
                "size":{
                  "width":58,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3a94a93b072d490a8e0c0909143f9bb6",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":143,
              "y":190},
            "size":{
              "width":190,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"92ae211f57514dbba08156def35ab5cb",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":143,
              "y":234},
            "size":{
              "width":187,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"49645c08f7334c60bab6e2819bfd0fe7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF87DB01}}},
            "fill":{
              "fillType":"solid",
              "color":0xFF6AB30C},
            "location":{
              "x":143,
              "y":624},
            "size":{
              "width":81,
              "height":26},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10bb6b88934f4551a7c64a17944ab824",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF87DB01}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF6AB30C},
                "location":{
                  "x":143,
                  "y":624},
                "size":{
                  "width":81,
                  "height":26},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 alert",
                      "objectsToFades":[{
                          "objectPath":["e233490c585a4672b23262f38934f761"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/修改个人资料/u102.png",
            "mouseOver~":"images/修改个人资料/u102_mouseOver.png"}},
{
          "id":"d527e39ea0644173a80d9ffda82cf7d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF87DB01}}},
            "fill":{
              "fillType":"solid",
              "color":0xFF6AB30C},
            "location":{
              "x":262,
              "y":624},
            "size":{
              "width":81,
              "height":26},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16cf34f84ccd4e70a636c3451dffcd5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF87DB01}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF6AB30C},
                "location":{
                  "x":262,
                  "y":624},
                "size":{
                  "width":81,
                  "height":26},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 新闻管理",
                      "target":{
                        "targetType":"page",
                        "url":"新闻管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/修改个人资料/u102.png",
            "mouseOver~":"images/修改个人资料/u102_mouseOver.png"}},
{
          "id":"e233490c585a4672b23262f38934f761",
          "label":"alert",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":380,
              "y":248},
            "size":{
              "width":320,
              "height":190},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"90ae3419fe3d4306be1fd3d6b9db9804",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"192bedbaf3f541438857a37882aaccff",
                  "label":"",
                  "parentDynamicPanel":"e233490c585a4672b23262f38934f761",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":280,
                      "height":160}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"de431b86f8714abfb3c11d0619972555",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e233490c585a4672b23262f38934f761",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":280,
                          "height":160}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/修改密码_1/u44.png"}},
{
                  "id":"931c669242814e27aa4fa8cfb7d38a65",
                  "label":"",
                  "parentDynamicPanel":"e233490c585a4672b23262f38934f761",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "location":{
                      "x":42,
                      "y":9},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"56c43433ce754655996bd47b152977f5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e233490c585a4672b23262f38934f761",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontWeight":"700",
                        "location":{
                          "x":42,
                          "y":9},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"452a2bf159904d5f91c82f1ce76b6ee8",
                  "label":"",
                  "parentDynamicPanel":"e233490c585a4672b23262f38934f761",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":26},
                    "size":{
                      "width":280,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/修改密码_1/u48_line.png"}},
{
                  "id":"feb0c0f0e8994d8c90357fa311aacb3e",
                  "label":"",
                  "parentDynamicPanel":"e233490c585a4672b23262f38934f761",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":101,
                      "y":120},
                    "size":{
                      "width":78,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5151edfadf4749fe8cc2e1f0177846ca",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e233490c585a4672b23262f38934f761",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4},
                        "location":{
                          "x":101,
                          "y":120},
                        "size":{
                          "width":78,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 alert",
                              "objectsToFades":[{
                                  "objectPath":["e233490c585a4672b23262f38934f761"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]},
{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 新闻管理",
                              "target":{
                                "targetType":"page",
                                "url":"新闻管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/修改密码_1/u49.png"}},
{
                  "id":"547566a6b2f54104a47ff06277fe986c",
                  "label":"",
                  "parentDynamicPanel":"e233490c585a4672b23262f38934f761",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":16,
                      "y":9},
                    "size":{
                      "width":16,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"dfd81f004f1443268510049460acbc78",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e233490c585a4672b23262f38934f761",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "location":{
                          "x":16,
                          "y":9},
                        "size":{
                          "width":16,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/修改密码_1/u51.png"}},
{
                  "id":"9cdf9420bee9472e9f72c236db8cbca3",
                  "label":"",
                  "parentDynamicPanel":"e233490c585a4672b23262f38934f761",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":126,
                      "y":72},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"30006162fcd74ffb9f53018d41e7c558",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e233490c585a4672b23262f38934f761",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":126,
                          "y":72},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"326daffdbd534ba288813e089e1ad2f7",
                  "label":"",
                  "parentDynamicPanel":"e233490c585a4672b23262f38934f761",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":100,
                      "y":72},
                    "size":{
                      "width":16,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"87d255644ab740a38b1016e656a8dc7a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e233490c585a4672b23262f38934f761",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "location":{
                          "x":100,
                          "y":72},
                        "size":{
                          "width":16,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/修改密码_1/u55.png"}}]}]},
{
          "id":"8161fe771f8645a197702cc22491ed2c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":79,
              "y":190},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"601b19042f5647a0a366dc188a19c388",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":79,
                  "y":190},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0a9de6f1e27d43108782038e0b55e57d",
          "label":"1",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":138,
              "y":276},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42d1268092e54fccbc5352bc1fccf4d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":138,
                  "y":276},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 1 等于 &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["0a9de6f1e27d43108782038e0b55e57d"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}},
{
                      "action":"setFunction",
                      "description":"设置 被选中的 2 等于 &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["924fa938defc4436bf76c825bc7ef8a4"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}}},
{
          "id":"924fa938defc4436bf76c825bc7ef8a4",
          "label":"2",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":248,
              "y":276},
            "size":{
              "width":47,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51467100f23947eab4dcd8595f3a9519",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":248,
                  "y":276},
                "size":{
                  "width":47,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 2 等于 &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["924fa938defc4436bf76c825bc7ef8a4"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}},
{
                      "action":"setFunction",
                      "description":"设置 被选中的 1 等于 &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["0a9de6f1e27d43108782038e0b55e57d"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}}}]}},
  "masters":{
},
  "objectPaths":{
    "c7e851678e44470baa5d580feb695130":{
      "scriptId":"u0"},
    "663575d23b9749debb9679275d60bd26":{
      "scriptId":"u1"},
    "b0f2ba19542245adb849d3db81b36f7b":{
      "scriptId":"u2"},
    "e5b2c1945f294849900fda6e84d88311":{
      "scriptId":"u3"},
    "aaf797a31a284a15bac09ea3f8c31ae0":{
      "scriptId":"u4"},
    "30c8e2f7132d44a1aafbf854688f7309":{
      "scriptId":"u5"},
    "d9f0e8c52513441b8252032ab4cbf9b7":{
      "scriptId":"u6"},
    "734212e032b745928eafaca6372a81e8":{
      "scriptId":"u7"},
    "f6df676e4bce4fc49957f9d79f79cf49":{
      "scriptId":"u8"},
    "8ee6d777f1764cfa90cd4e5bac50fdc2":{
      "scriptId":"u9"},
    "efe908e61642497d9e5c8b47f8d430b3":{
      "scriptId":"u10"},
    "a8306e41386b4801807b303b85a9eddc":{
      "scriptId":"u11"},
    "c84e77cd87d44474916c6d063e573f3e":{
      "scriptId":"u12"},
    "bbe4a5ffd2bb4133a9eb42d120484c94":{
      "scriptId":"u13"},
    "72e4c84e707f4792a8c1cd3312c9d3aa":{
      "scriptId":"u14"},
    "7310a56fe805417f8d7a252662b3b1e3":{
      "scriptId":"u15"},
    "c60d0b20ccf74444b3f9cc982d672858":{
      "scriptId":"u16"},
    "80984ef1d00c49399d6a8d17352eb55b":{
      "scriptId":"u17"},
    "1445bb1b19564d11bfa95b951f74832d":{
      "scriptId":"u18"},
    "d21000f9c1b0433a8475a91f44f7d499":{
      "scriptId":"u19"},
    "8e1a6db02b164adeb73f92457af82b06":{
      "scriptId":"u20"},
    "d9b72f552f6c432cbc7bd9907c053715":{
      "scriptId":"u21"},
    "9938e52469104831947e4f77512e781a":{
      "scriptId":"u22"},
    "317728b392b049f9adc3c0fef5a4fc45":{
      "scriptId":"u23"},
    "33b8bd2237aa4c189a2db77e388204b8":{
      "scriptId":"u24"},
    "f1293eddbc134cdf831b469ed8ad00a0":{
      "scriptId":"u25"},
    "a35b98c7741c4e858b350befb62ca314":{
      "scriptId":"u26"},
    "b82c0b6f03d646798af37fc76138510b":{
      "scriptId":"u27"},
    "b1848780c7e54078839c049d308a6839":{
      "scriptId":"u28"},
    "4bd2648f8cee403db79837a84c9ac00c":{
      "scriptId":"u29"},
    "06005e63de5847bbb28717657defb48d":{
      "scriptId":"u30"},
    "8dadd6d4dfd44ff4a5bd6ea7681204fd":{
      "scriptId":"u31"},
    "c43e79d51f144515aab51862af375255":{
      "scriptId":"u32"},
    "d454c12326ad45979aad5cd57b80cb79":{
      "scriptId":"u33"},
    "d389c12d214e415693fb71564862a720":{
      "scriptId":"u34"},
    "b813678148ab4b769bd796b17fd2fa1d":{
      "scriptId":"u35"},
    "71e1f102007d46878eebd0a642818a44":{
      "scriptId":"u36"},
    "4589a10dcbf94aa3b62c431436d090fa":{
      "scriptId":"u37"},
    "69f36baa403f42e28ad0db3d6b146c96":{
      "scriptId":"u38"},
    "6555b200261e428dba7f988e2a727004":{
      "scriptId":"u39"},
    "e9a1df78fa244d50b2757aa7713fbb6a":{
      "scriptId":"u40"},
    "86b5bc2bff33457984d84679ad2ad67f":{
      "scriptId":"u41"},
    "4fca03aa552b42f6932c9fefd73dafbf":{
      "scriptId":"u42"},
    "3b5b9f2389014f68857b652d6700cefd":{
      "scriptId":"u43"},
    "cce7f94d8f194dee9b8e7c0e738dc063":{
      "scriptId":"u44"},
    "3a94a93b072d490a8e0c0909143f9bb6":{
      "scriptId":"u45"},
    "92ae211f57514dbba08156def35ab5cb":{
      "scriptId":"u46"},
    "49645c08f7334c60bab6e2819bfd0fe7":{
      "scriptId":"u47"},
    "10bb6b88934f4551a7c64a17944ab824":{
      "scriptId":"u48"},
    "d527e39ea0644173a80d9ffda82cf7d9":{
      "scriptId":"u49"},
    "16cf34f84ccd4e70a636c3451dffcd5e":{
      "scriptId":"u50"},
    "e233490c585a4672b23262f38934f761":{
      "scriptId":"u51"},
    "192bedbaf3f541438857a37882aaccff":{
      "scriptId":"u52"},
    "de431b86f8714abfb3c11d0619972555":{
      "scriptId":"u53"},
    "931c669242814e27aa4fa8cfb7d38a65":{
      "scriptId":"u54"},
    "56c43433ce754655996bd47b152977f5":{
      "scriptId":"u55"},
    "452a2bf159904d5f91c82f1ce76b6ee8":{
      "scriptId":"u56"},
    "feb0c0f0e8994d8c90357fa311aacb3e":{
      "scriptId":"u57"},
    "5151edfadf4749fe8cc2e1f0177846ca":{
      "scriptId":"u58"},
    "547566a6b2f54104a47ff06277fe986c":{
      "scriptId":"u59"},
    "dfd81f004f1443268510049460acbc78":{
      "scriptId":"u60"},
    "9cdf9420bee9472e9f72c236db8cbca3":{
      "scriptId":"u61"},
    "30006162fcd74ffb9f53018d41e7c558":{
      "scriptId":"u62"},
    "326daffdbd534ba288813e089e1ad2f7":{
      "scriptId":"u63"},
    "87d255644ab740a38b1016e656a8dc7a":{
      "scriptId":"u64"},
    "8161fe771f8645a197702cc22491ed2c":{
      "scriptId":"u65"},
    "601b19042f5647a0a366dc188a19c388":{
      "scriptId":"u66"},
    "0a9de6f1e27d43108782038e0b55e57d":{
      "scriptId":"u67"},
    "42d1268092e54fccbc5352bc1fccf4d7":{
      "scriptId":"u68"},
    "924fa938defc4436bf76c825bc7ef8a4":{
      "scriptId":"u69"},
    "51467100f23947eab4dcd8595f3a9519":{
      "scriptId":"u70"}}});