$axure.loadCurrentPage({
  "url":"修改班级_1.html",
  "generationDate":new Date(1383013851971.28),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ad026b6a57ed473e8b6385c32ead6a1d",
    "type":"Axure:Page",
    "name":"修改班级",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1da6a849a90b44edb94fdf60e227d9fc",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":98,
              "y":706},
            "size":{
              "width":1001,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页/u228_line.png"}},
{
          "id":"8bd7de3b9b884e05bd5a96bc1a1b2487",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":429,
              "y":754},
            "size":{
              "width":181,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79c7430874be408d826190adaec31b3f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":429,
                  "y":754},
                "size":{
                  "width":181,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b63b4bd824f14b5f86863b307db095e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":721},
            "size":{
              "width":46,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"327bdda5f41340bbb9a7966bb3cc016d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":370,
                  "y":721},
                "size":{
                  "width":46,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"110820df14bb4a73a52020e3e656b906",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":431,
              "y":721},
            "size":{
              "width":80,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a198f0b305464a6fbddd4d62e9ab58c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":431,
                  "y":721},
                "size":{
                  "width":80,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 底部单页",
                      "target":{
                        "targetType":"page",
                        "url":"底部单页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ab4d8240d6b9402b8fb154fd54d9e674",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":526,
              "y":721},
            "size":{
              "width":68,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f084c68303d74b8fb77b2a75910898f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":526,
                  "y":721},
                "size":{
                  "width":68,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 底部单页",
                      "target":{
                        "targetType":"page",
                        "url":"底部单页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"19825d26b97545129e074bb784cfda01",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":617,
              "y":721},
            "size":{
              "width":68,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e59827e9779b41e196125e80d70e7c60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":617,
                  "y":721},
                "size":{
                  "width":68,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 底部单页",
                      "target":{
                        "targetType":"page",
                        "url":"底部单页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0ce6811010f2490f8ae3ea2133579dc2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":711,
              "y":721},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7865195e9854bceb417cdb7995d2da7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":711,
                  "y":721},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 底部单页",
                      "target":{
                        "targetType":"page",
                        "url":"底部单页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ad585df7919d49fc972ff64eca9c4a50",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":130},
            "size":{
              "width":746,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF949494}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/会员中心默认页/u27_line.png"}},
{
          "id":"517a0db4d6b94294ac8c6967c12d26ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":92,
              "y":238},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e236f9c7b0f46aca0274c895c79849c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":92,
                  "y":238},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e89c92e9d7344a528ce371de42c7f1d5",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":168,
              "y":234},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"35ce5845f3934458bd75069c44a215f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":92,
              "y":285},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22e89e913afd41c2900ccd9c26981580",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":92,
                  "y":285},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"81d0131ed0a047f09147e6623df3a854",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":168,
              "y":284},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"3d708702d4dc414caac463bcb6c87a04",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":92,
              "y":336},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8135d26d28a44a182eb5ca5df59c889",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":92,
                  "y":336},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eacbe762bbd547109d93cc8c546c8c6c",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":168,
              "y":336},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"76ff66b56c2d4ee194886e6d22568490",
          "label":"createSchool",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":92,
              "y":162},
            "size":{
              "width":697,
              "height":48}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"bb1eac3a697e4d0dac13864be726258f",
              "label":"1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"11c8e99ac06e4ce3a8c11a80994ac290",
                  "label":"",
                  "parentDynamicPanel":"76ff66b56c2d4ee194886e6d22568490",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":505,
                      "y":12},
                    "size":{
                      "width":105,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"09b5a5aa0fba446eac5f46d0cc0f37b2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"76ff66b56c2d4ee194886e6d22568490",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":505,
                          "y":12},
                        "size":{
                          "width":105,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"26e81eedf52042f59909ef62d9453a9a",
                  "label":"马上去创建",
                  "parentDynamicPanel":"76ff66b56c2d4ee194886e6d22568490",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF009933,
                      "opacity":1},
                    "location":{
                      "x":610,
                      "y":12},
                    "size":{
                      "width":77,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d68d80d075db4faaa551fabdccba1725",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"76ff66b56c2d4ee194886e6d22568490",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF009933,
                          "opacity":1},
                        "location":{
                          "x":610,
                          "y":12},
                        "size":{
                          "width":77,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 createSchool 到 2",
                              "panelsToStates":[{
                                  "panelPath":["76ff66b56c2d4ee194886e6d22568490"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"10e33e7fde8d4447aa14c422cc3d2dda",
                  "label":"",
                  "parentDynamicPanel":"76ff66b56c2d4ee194886e6d22568490",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":13},
                    "size":{
                      "width":66,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a407216e79f6449985a20b5175d24bbb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"76ff66b56c2d4ee194886e6d22568490",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":13},
                        "size":{
                          "width":66,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"547fe618119746269f4eda29ffe5461a",
                  "label":"",
                  "parentDynamicPanel":"76ff66b56c2d4ee194886e6d22568490",
                  "type":"comboBox",
                  "styleType":"comboBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":295,
                      "y":10},
                    "size":{
                      "width":200,
                      "height":22}},
                  "adaptiveStyles":{
}},
{
                  "id":"d1032b8fad804e80acabf1e829ca24a9",
                  "label":"",
                  "parentDynamicPanel":"76ff66b56c2d4ee194886e6d22568490",
                  "type":"comboBox",
                  "styleType":"comboBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":76,
                      "y":10},
                    "size":{
                      "width":200,
                      "height":22}},
                  "adaptiveStyles":{
}},
{
                  "id":"2b2587ab5d544d6e9ba83588159c8d42",
                  "label":"",
                  "parentDynamicPanel":"76ff66b56c2d4ee194886e6d22568490",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000,
                      "opacity":1},
                    "location":{
                      "x":76,
                      "y":32},
                    "size":{
                      "width":150,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0e59ec91ab8f474cb750665954a2dd82",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"76ff66b56c2d4ee194886e6d22568490",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF0000,
                          "opacity":1},
                        "location":{
                          "x":76,
                          "y":32},
                        "size":{
                          "width":150,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]},
{
              "id":"ded0cb0a425a4fca99068abc332793e0",
              "label":"2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"86e62eca75274649b1675af5c5c6943a",
                  "label":"",
                  "parentDynamicPanel":"76ff66b56c2d4ee194886e6d22568490",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":14},
                    "size":{
                      "width":92,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d8ecfc8fb3a34dafab0d628f3644c2ce",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"76ff66b56c2d4ee194886e6d22568490",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":14},
                        "size":{
                          "width":92,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"2dba743fe777416e9d040e0b6076a7b1",
                  "label":"",
                  "parentDynamicPanel":"76ff66b56c2d4ee194886e6d22568490",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":92,
                      "y":10},
                    "size":{
                      "width":150,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"67e2cb0c92d64473a1b3fc034da4230c",
                  "label":"",
                  "parentDynamicPanel":"76ff66b56c2d4ee194886e6d22568490",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":252,
                      "y":14},
                    "size":{
                      "width":92,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"337fd16ff14f4ce381106a5d4a2f228b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"76ff66b56c2d4ee194886e6d22568490",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":252,
                          "y":14},
                        "size":{
                          "width":92,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"3dcc0c1c2e4043968ee6f6f62e501f33",
                  "label":"添加",
                  "parentDynamicPanel":"76ff66b56c2d4ee194886e6d22568490",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF009933,
                      "opacity":1},
                    "location":{
                      "x":496,
                      "y":14},
                    "size":{
                      "width":27,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e0b2579e33c64366a547913ceb961529",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"76ff66b56c2d4ee194886e6d22568490",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF009933,
                          "opacity":1},
                        "location":{
                          "x":496,
                          "y":14},
                        "size":{
                          "width":27,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 添加成功 淡入淡出 500 ms",
                              "objectsToFades":[{
                                  "objectPath":["6c42973f4032403abbda2636f1e888d5"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "easing":"fade",
                                      "duration":500,
                                      "showType":"none"}}}]},
{
                              "action":"wait",
                              "description":"等待2000毫秒",
                              "waitTime":2000},
{
                              "action":"fadeWidget",
                              "description":"隐藏 添加成功 淡入淡出 500 ms",
                              "objectsToFades":[{
                                  "objectPath":["6c42973f4032403abbda2636f1e888d5"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "easing":"fade",
                                      "duration":500,
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"447efc1aee924f6c8a7464926c97dd76",
                  "label":"",
                  "parentDynamicPanel":"76ff66b56c2d4ee194886e6d22568490",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF009933,
                      "opacity":1},
                    "location":{
                      "x":546,
                      "y":15},
                    "size":{
                      "width":79,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9a0ada15f5f34037abaab3486aed3a4c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"76ff66b56c2d4ee194886e6d22568490",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF009933,
                          "opacity":1},
                        "location":{
                          "x":546,
                          "y":15},
                        "size":{
                          "width":79,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 createSchool 到 1",
                              "panelsToStates":[{
                                  "panelPath":["76ff66b56c2d4ee194886e6d22568490"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"9650109a228a470eb0c6732f0505941e",
                  "label":"",
                  "parentDynamicPanel":"76ff66b56c2d4ee194886e6d22568490",
                  "type":"comboBox",
                  "styleType":"comboBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":344,
                      "y":11},
                    "size":{
                      "width":142,
                      "height":22}},
                  "adaptiveStyles":{
}},
{
                  "id":"6c42973f4032403abbda2636f1e888d5",
                  "label":"添加成功",
                  "parentDynamicPanel":"76ff66b56c2d4ee194886e6d22568490",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":false,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF009933,
                      "opacity":1},
                    "location":{
                      "x":92,
                      "y":45},
                    "size":{
                      "width":66,
                      "height":16},
                    "visible":false,
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF339900}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a0deef02fa084602ae075f4606e201b6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"76ff66b56c2d4ee194886e6d22568490",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF009933,
                          "opacity":1},
                        "location":{
                          "x":92,
                          "y":45},
                        "size":{
                          "width":66,
                          "height":16},
                        "visible":false,
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF339900}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"8e650246d8ab42ecb47b4b1e753354f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF87DB01}}},
            "fill":{
              "fillType":"solid",
              "color":0xFF6AB30C},
            "location":{
              "x":168,
              "y":424},
            "size":{
              "width":81,
              "height":26},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"68fcf4e3a9cf4bb091ac46a6f17b55d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF87DB01}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF6AB30C},
                "location":{
                  "x":168,
                  "y":424},
                "size":{
                  "width":81,
                  "height":26},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 alert",
                      "objectsToFades":[{
                          "objectPath":["6cafee3a594246eea272c4123786bdc1"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/修改个人资料/u102.png",
            "mouseOver~":"images/修改个人资料/u102_mouseOver.png"}},
{
          "id":"0190cdca9c56443cb82fafbedfb5790e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":92,
              "y":377},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6e2b844c983468fbf9706670d319e90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":92,
                  "y":377},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e5938c4d34184cd9a9455c6e067d0c7b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":168,
              "y":376},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52cc2df8312346dba5aa46d121ffe5b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":168,
                  "y":376},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"18b74233513c4c7cbc8a3300cfbb8912",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":205,
              "y":376},
            "size":{
              "width":131,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28e18ba5b91c44ab960db20fedf55a2d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":205,
                  "y":376},
                "size":{
                  "width":131,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6cafee3a594246eea272c4123786bdc1",
          "label":"alert",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":219,
              "y":172},
            "size":{
              "width":279,
              "height":148},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"6dd9bdcc48d24dacabb6e5db0e568de0",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"6811198e431e4ea2b1e8c810a77a5c86",
                  "label":"",
                  "parentDynamicPanel":"6cafee3a594246eea272c4123786bdc1",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":280,
                      "height":160}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3e9b406b569d4d45917256fa667a422a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6cafee3a594246eea272c4123786bdc1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":280,
                          "height":160}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/修改密码_1/u44.png"}},
{
                  "id":"fc67cfbeb8074df98e53fc4acbd19636",
                  "label":"",
                  "parentDynamicPanel":"6cafee3a594246eea272c4123786bdc1",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "location":{
                      "x":42,
                      "y":9},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6d4d586695104b8fbef82f8cfedf0d75",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6cafee3a594246eea272c4123786bdc1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontWeight":"700",
                        "location":{
                          "x":42,
                          "y":9},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"3ffea152cb9e4306be5978e4495b8f9d",
                  "label":"",
                  "parentDynamicPanel":"6cafee3a594246eea272c4123786bdc1",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":26},
                    "size":{
                      "width":280,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/修改密码_1/u48_line.png"}},
{
                  "id":"000621ca074e466d803913dd13c5b74a",
                  "label":"",
                  "parentDynamicPanel":"6cafee3a594246eea272c4123786bdc1",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":101,
                      "y":110},
                    "size":{
                      "width":78,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bb137f09983d4688be2c827c00ffabfd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6cafee3a594246eea272c4123786bdc1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4},
                        "location":{
                          "x":101,
                          "y":110},
                        "size":{
                          "width":78,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 alert",
                              "objectsToFades":[{
                                  "objectPath":["6cafee3a594246eea272c4123786bdc1"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/修改密码_1/u49.png"}},
{
                  "id":"756bdece1810420da93dcab62db16293",
                  "label":"",
                  "parentDynamicPanel":"6cafee3a594246eea272c4123786bdc1",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":16,
                      "y":9},
                    "size":{
                      "width":16,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"81f31977bc454deba3ad776485f6b336",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6cafee3a594246eea272c4123786bdc1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "location":{
                          "x":16,
                          "y":9},
                        "size":{
                          "width":16,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/修改密码_1/u51.png"}},
{
                  "id":"0eb577c1b00a4d06a5b25203a02e56fb",
                  "label":"",
                  "parentDynamicPanel":"6cafee3a594246eea272c4123786bdc1",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":114,
                      "y":64},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b27f32d7e818401da4aa16df55acbe71",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6cafee3a594246eea272c4123786bdc1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":114,
                          "y":64},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"4787be592ada407bb72e4835cbabedc3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":82,
              "y":115},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5f1c0e68e68433d8788d3daf5c992ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":82,
                  "y":115},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 管理班级",
                      "target":{
                        "targetType":"page",
                        "url":"管理班级.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4b3ed4a3939444dc86467c5cbdc961d4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":60,
              "y":115},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8bae34eec6e94b789867a43784dbe2f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":60,
                  "y":115},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理班级/u42.png"}},
{
          "id":"f0f990c368fb4327be6ac21cb977b54d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":171,
              "y":115},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2678543d5ab84981a99b3c3c40aa5c79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":171,
                  "y":115},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"522ac5093fd24c428cbe008dd299e495",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":195,
              "y":115},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9f005b9f0ee4f8e9feff2e704b98b93",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":195,
                  "y":115},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"41d0285196cb4ee8a524bd998fcbfa94",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":170,
              "height":51}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2260ce0413fd4dd59d696296a194d078",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":170,
                  "height":51}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改密码_1/u0.jpg"}},
{
          "id":"f14f8bdb61ef4a51a4c42c80d8d4691c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":598,
              "y":4},
            "size":{
              "width":148,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1f5ba6fd444440b8b4a104202c4c32b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":598,
                  "y":4},
                "size":{
                  "width":148,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b458aa8469cb493d9426d42095906ff1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":903,
              "y":4},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0c99930989c4c64992cf345f6af3a49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":903,
                  "y":4},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 后台登录",
                      "target":{
                        "targetType":"page",
                        "url":"后台登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9e7edac47e0d4a3eb670b8b50b87251d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":828,
              "y":4},
            "size":{
              "width":88,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0bf23b5937c749ce9bc597f346ffd641",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":828,
                  "y":4},
                "size":{
                  "width":88,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 修改密码",
                      "target":{
                        "targetType":"page",
                        "url":"修改密码_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a466cd628fc74787bf48c6ffcdf76685",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":756,
              "y":4},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2484e31c76be4708a820b5268ba2991b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":756,
                  "y":4},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"23af8860d03a40eea527de277d441138",
          "label":"导航",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":50},
            "size":{
              "width":716,
              "height":129}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"74404ccfe0f64d9ca96d81fd61bc3c38",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"121514e85395409cbd2384991a8d863c",
                  "label":"",
                  "parentDynamicPanel":"23af8860d03a40eea527de277d441138",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":90,
                      "y":7},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f01683b9a78646259602f5654eae0b25",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"23af8860d03a40eea527de277d441138",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":90,
                          "y":7},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 新闻管理",
                              "target":{
                                "targetType":"page",
                                "url":"新闻管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"09c56d07dd56458998ea9451b9459219",
                  "label":"",
                  "parentDynamicPanel":"23af8860d03a40eea527de277d441138",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":190,
                      "y":7},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2ca4e039dc3b452c88e3c4c76f953faa",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"23af8860d03a40eea527de277d441138",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":190,
                          "y":7},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 KAB概况管理",
                              "target":{
                                "targetType":"page",
                                "url":"kab概况管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f7e0fe11c30b4a1b8911433d75bd1537",
                  "label":"",
                  "parentDynamicPanel":"23af8860d03a40eea527de277d441138",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":287,
                      "y":7},
                    "size":{
                      "width":54,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9656ec65625443c8a5a429234d5d61c4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"23af8860d03a40eea527de277d441138",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":287,
                          "y":7},
                        "size":{
                          "width":54,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 KAB公告管理",
                              "target":{
                                "targetType":"page",
                                "url":"kab公告管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f952dcf996d54a849ec75254f05c7b91",
                  "label":"",
                  "parentDynamicPanel":"23af8860d03a40eea527de277d441138",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":637,
                      "y":7},
                    "size":{
                      "width":79,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"be502221b75a43a6ab62651e34bfad9c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"23af8860d03a40eea527de277d441138",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":637,
                          "y":7},
                        "size":{
                          "width":79,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 系统参数配置",
                              "target":{
                                "targetType":"page",
                                "url":"系统参数配置.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"72c4629b22cf4fb6a0faa29002f0d08a",
                  "label":"",
                  "parentDynamicPanel":"23af8860d03a40eea527de277d441138",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":22},
                    "size":{
                      "width":1000,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/修改密码_1/u21_line.png"}},
{
                  "id":"39c57fa4de2142bd8d1068c82df20840",
                  "label":"",
                  "parentDynamicPanel":"23af8860d03a40eea527de277d441138",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF5E5E5E,
                      "opacity":1},
                    "location":{
                      "x":393,
                      "y":1},
                    "size":{
                      "width":97,
                      "height":27},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"31bd179000b449008b6095623e3db920",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"23af8860d03a40eea527de277d441138",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF5E5E5E,
                          "opacity":1},
                        "location":{
                          "x":393,
                          "y":1},
                        "size":{
                          "width":97,
                          "height":27},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 班级管理",
                              "target":{
                                "targetType":"page",
                                "url":"班级管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/新闻管理/u12.png"}},
{
                  "id":"b420390883be41a187587622336b7ce4",
                  "label":"",
                  "parentDynamicPanel":"23af8860d03a40eea527de277d441138",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":545,
                      "y":7},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5d9b865becb744b4b629bf66d303f502",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"23af8860d03a40eea527de277d441138",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":545,
                          "y":7},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 用户管理",
                              "target":{
                                "targetType":"page",
                                "url":"用户管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"235ee3c13c0b42559439681f4ccb763e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF87DB01}}},
            "fill":{
              "fillType":"solid",
              "color":0xFF6AB30C},
            "location":{
              "x":280,
              "y":424},
            "size":{
              "width":81,
              "height":26},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b535e4f05a649a1ac8386d49027a4d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF87DB01}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF6AB30C},
                "location":{
                  "x":280,
                  "y":424},
                "size":{
                  "width":81,
                  "height":26},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 管理班级",
                      "target":{
                        "targetType":"page",
                        "url":"管理班级.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/修改个人资料/u102.png",
            "mouseOver~":"images/修改个人资料/u102_mouseOver.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "1da6a849a90b44edb94fdf60e227d9fc":{
      "scriptId":"u0"},
    "8bd7de3b9b884e05bd5a96bc1a1b2487":{
      "scriptId":"u1"},
    "79c7430874be408d826190adaec31b3f":{
      "scriptId":"u2"},
    "b63b4bd824f14b5f86863b307db095e9":{
      "scriptId":"u3"},
    "327bdda5f41340bbb9a7966bb3cc016d":{
      "scriptId":"u4"},
    "110820df14bb4a73a52020e3e656b906":{
      "scriptId":"u5"},
    "a198f0b305464a6fbddd4d62e9ab58c0":{
      "scriptId":"u6"},
    "ab4d8240d6b9402b8fb154fd54d9e674":{
      "scriptId":"u7"},
    "f084c68303d74b8fb77b2a75910898f4":{
      "scriptId":"u8"},
    "19825d26b97545129e074bb784cfda01":{
      "scriptId":"u9"},
    "e59827e9779b41e196125e80d70e7c60":{
      "scriptId":"u10"},
    "0ce6811010f2490f8ae3ea2133579dc2":{
      "scriptId":"u11"},
    "d7865195e9854bceb417cdb7995d2da7":{
      "scriptId":"u12"},
    "ad585df7919d49fc972ff64eca9c4a50":{
      "scriptId":"u13"},
    "517a0db4d6b94294ac8c6967c12d26ef":{
      "scriptId":"u14"},
    "0e236f9c7b0f46aca0274c895c79849c":{
      "scriptId":"u15"},
    "e89c92e9d7344a528ce371de42c7f1d5":{
      "scriptId":"u16"},
    "35ce5845f3934458bd75069c44a215f1":{
      "scriptId":"u17"},
    "22e89e913afd41c2900ccd9c26981580":{
      "scriptId":"u18"},
    "81d0131ed0a047f09147e6623df3a854":{
      "scriptId":"u19"},
    "3d708702d4dc414caac463bcb6c87a04":{
      "scriptId":"u20"},
    "d8135d26d28a44a182eb5ca5df59c889":{
      "scriptId":"u21"},
    "eacbe762bbd547109d93cc8c546c8c6c":{
      "scriptId":"u22"},
    "76ff66b56c2d4ee194886e6d22568490":{
      "scriptId":"u23"},
    "11c8e99ac06e4ce3a8c11a80994ac290":{
      "scriptId":"u24"},
    "09b5a5aa0fba446eac5f46d0cc0f37b2":{
      "scriptId":"u25"},
    "26e81eedf52042f59909ef62d9453a9a":{
      "scriptId":"u26"},
    "d68d80d075db4faaa551fabdccba1725":{
      "scriptId":"u27"},
    "10e33e7fde8d4447aa14c422cc3d2dda":{
      "scriptId":"u28"},
    "a407216e79f6449985a20b5175d24bbb":{
      "scriptId":"u29"},
    "547fe618119746269f4eda29ffe5461a":{
      "scriptId":"u30"},
    "d1032b8fad804e80acabf1e829ca24a9":{
      "scriptId":"u31"},
    "2b2587ab5d544d6e9ba83588159c8d42":{
      "scriptId":"u32"},
    "0e59ec91ab8f474cb750665954a2dd82":{
      "scriptId":"u33"},
    "86e62eca75274649b1675af5c5c6943a":{
      "scriptId":"u34"},
    "d8ecfc8fb3a34dafab0d628f3644c2ce":{
      "scriptId":"u35"},
    "2dba743fe777416e9d040e0b6076a7b1":{
      "scriptId":"u36"},
    "67e2cb0c92d64473a1b3fc034da4230c":{
      "scriptId":"u37"},
    "337fd16ff14f4ce381106a5d4a2f228b":{
      "scriptId":"u38"},
    "3dcc0c1c2e4043968ee6f6f62e501f33":{
      "scriptId":"u39"},
    "e0b2579e33c64366a547913ceb961529":{
      "scriptId":"u40"},
    "447efc1aee924f6c8a7464926c97dd76":{
      "scriptId":"u41"},
    "9a0ada15f5f34037abaab3486aed3a4c":{
      "scriptId":"u42"},
    "9650109a228a470eb0c6732f0505941e":{
      "scriptId":"u43"},
    "6c42973f4032403abbda2636f1e888d5":{
      "scriptId":"u44"},
    "a0deef02fa084602ae075f4606e201b6":{
      "scriptId":"u45"},
    "8e650246d8ab42ecb47b4b1e753354f0":{
      "scriptId":"u46"},
    "68fcf4e3a9cf4bb091ac46a6f17b55d4":{
      "scriptId":"u47"},
    "0190cdca9c56443cb82fafbedfb5790e":{
      "scriptId":"u48"},
    "f6e2b844c983468fbf9706670d319e90":{
      "scriptId":"u49"},
    "e5938c4d34184cd9a9455c6e067d0c7b":{
      "scriptId":"u50"},
    "52cc2df8312346dba5aa46d121ffe5b0":{
      "scriptId":"u51"},
    "18b74233513c4c7cbc8a3300cfbb8912":{
      "scriptId":"u52"},
    "28e18ba5b91c44ab960db20fedf55a2d":{
      "scriptId":"u53"},
    "6cafee3a594246eea272c4123786bdc1":{
      "scriptId":"u54"},
    "6811198e431e4ea2b1e8c810a77a5c86":{
      "scriptId":"u55"},
    "3e9b406b569d4d45917256fa667a422a":{
      "scriptId":"u56"},
    "fc67cfbeb8074df98e53fc4acbd19636":{
      "scriptId":"u57"},
    "6d4d586695104b8fbef82f8cfedf0d75":{
      "scriptId":"u58"},
    "3ffea152cb9e4306be5978e4495b8f9d":{
      "scriptId":"u59"},
    "000621ca074e466d803913dd13c5b74a":{
      "scriptId":"u60"},
    "bb137f09983d4688be2c827c00ffabfd":{
      "scriptId":"u61"},
    "756bdece1810420da93dcab62db16293":{
      "scriptId":"u62"},
    "81f31977bc454deba3ad776485f6b336":{
      "scriptId":"u63"},
    "0eb577c1b00a4d06a5b25203a02e56fb":{
      "scriptId":"u64"},
    "b27f32d7e818401da4aa16df55acbe71":{
      "scriptId":"u65"},
    "4787be592ada407bb72e4835cbabedc3":{
      "scriptId":"u66"},
    "b5f1c0e68e68433d8788d3daf5c992ca":{
      "scriptId":"u67"},
    "4b3ed4a3939444dc86467c5cbdc961d4":{
      "scriptId":"u68"},
    "8bae34eec6e94b789867a43784dbe2f1":{
      "scriptId":"u69"},
    "f0f990c368fb4327be6ac21cb977b54d":{
      "scriptId":"u70"},
    "2678543d5ab84981a99b3c3c40aa5c79":{
      "scriptId":"u71"},
    "522ac5093fd24c428cbe008dd299e495":{
      "scriptId":"u72"},
    "e9f005b9f0ee4f8e9feff2e704b98b93":{
      "scriptId":"u73"},
    "41d0285196cb4ee8a524bd998fcbfa94":{
      "scriptId":"u74"},
    "2260ce0413fd4dd59d696296a194d078":{
      "scriptId":"u75"},
    "f14f8bdb61ef4a51a4c42c80d8d4691c":{
      "scriptId":"u76"},
    "c1f5ba6fd444440b8b4a104202c4c32b":{
      "scriptId":"u77"},
    "b458aa8469cb493d9426d42095906ff1":{
      "scriptId":"u78"},
    "f0c99930989c4c64992cf345f6af3a49":{
      "scriptId":"u79"},
    "9e7edac47e0d4a3eb670b8b50b87251d":{
      "scriptId":"u80"},
    "0bf23b5937c749ce9bc597f346ffd641":{
      "scriptId":"u81"},
    "a466cd628fc74787bf48c6ffcdf76685":{
      "scriptId":"u82"},
    "2484e31c76be4708a820b5268ba2991b":{
      "scriptId":"u83"},
    "23af8860d03a40eea527de277d441138":{
      "scriptId":"u84"},
    "121514e85395409cbd2384991a8d863c":{
      "scriptId":"u85"},
    "f01683b9a78646259602f5654eae0b25":{
      "scriptId":"u86"},
    "09c56d07dd56458998ea9451b9459219":{
      "scriptId":"u87"},
    "2ca4e039dc3b452c88e3c4c76f953faa":{
      "scriptId":"u88"},
    "f7e0fe11c30b4a1b8911433d75bd1537":{
      "scriptId":"u89"},
    "9656ec65625443c8a5a429234d5d61c4":{
      "scriptId":"u90"},
    "f952dcf996d54a849ec75254f05c7b91":{
      "scriptId":"u91"},
    "be502221b75a43a6ab62651e34bfad9c":{
      "scriptId":"u92"},
    "72c4629b22cf4fb6a0faa29002f0d08a":{
      "scriptId":"u93"},
    "39c57fa4de2142bd8d1068c82df20840":{
      "scriptId":"u94"},
    "31bd179000b449008b6095623e3db920":{
      "scriptId":"u95"},
    "b420390883be41a187587622336b7ce4":{
      "scriptId":"u96"},
    "5d9b865becb744b4b629bf66d303f502":{
      "scriptId":"u97"},
    "235ee3c13c0b42559439681f4ccb763e":{
      "scriptId":"u98"},
    "3b535e4f05a649a1ac8386d49027a4d7":{
      "scriptId":"u99"}}});