$axure.loadCurrentPage({
  "url":"kab概况管理.html",
  "generationDate":new Date(1383013849714.15),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1c4515dd95a241f48a84de54606dcc83",
    "type":"Axure:Page",
    "name":"KAB概况管理",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e6c1505df5544cb58efd3bc3738d5ba9",
          "label":"导航",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":50},
            "size":{
              "width":716,
              "height":129}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"5830709c8d874f45a7ce90675b6ba8da",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"a1ac1fc37cc04d38a0a5f0c5a9809741",
                  "label":"",
                  "parentDynamicPanel":"e6c1505df5544cb58efd3bc3738d5ba9",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":90,
                      "y":7},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"65c4b387bea74707a3c97872024892a0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e6c1505df5544cb58efd3bc3738d5ba9",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":90,
                          "y":7},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 新闻管理",
                              "target":{
                                "targetType":"page",
                                "url":"新闻管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"64ff3219bc374d07b094a1b93d8dff03",
                  "label":"",
                  "parentDynamicPanel":"e6c1505df5544cb58efd3bc3738d5ba9",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":300,
                      "y":7},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"50b315d0d2e64846b4cf871d1cc1c70a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e6c1505df5544cb58efd3bc3738d5ba9",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":300,
                          "y":7},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 KAB公告管理",
                              "target":{
                                "targetType":"page",
                                "url":"kab公告管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"78dbfafa0a714834bda7b63825dea9f0",
                  "label":"",
                  "parentDynamicPanel":"e6c1505df5544cb58efd3bc3738d5ba9",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":407,
                      "y":7},
                    "size":{
                      "width":79,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ed222b5284444f4ca3b1748731163b3a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e6c1505df5544cb58efd3bc3738d5ba9",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":407,
                          "y":7},
                        "size":{
                          "width":79,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 班级管理",
                              "target":{
                                "targetType":"page",
                                "url":"班级管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"06886f78b301450fa2246fb87825a17d",
                  "label":"",
                  "parentDynamicPanel":"e6c1505df5544cb58efd3bc3738d5ba9",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":542,
                      "y":7},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b7a0eeb1153f40eca80946843d643e51",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e6c1505df5544cb58efd3bc3738d5ba9",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":542,
                          "y":7},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 用户管理",
                              "target":{
                                "targetType":"page",
                                "url":"用户管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"fc0f8bf41608438b9429c7e6454237b9",
                  "label":"",
                  "parentDynamicPanel":"e6c1505df5544cb58efd3bc3738d5ba9",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":637,
                      "y":7},
                    "size":{
                      "width":79,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"88154bb6c17f41c18084a3dddc7f1036",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e6c1505df5544cb58efd3bc3738d5ba9",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":637,
                          "y":7},
                        "size":{
                          "width":79,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 系统参数配置",
                              "target":{
                                "targetType":"page",
                                "url":"系统参数配置.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"5bfea81d40ae455e86626305bfd707a7",
                  "label":"",
                  "parentDynamicPanel":"e6c1505df5544cb58efd3bc3738d5ba9",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":22},
                    "size":{
                      "width":1000,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/修改密码_1/u21_line.png"}},
{
                  "id":"70df364cc2044f68a637df15e05053af",
                  "label":"",
                  "parentDynamicPanel":"e6c1505df5544cb58efd3bc3738d5ba9",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF5E5E5E,
                      "opacity":1},
                    "location":{
                      "x":173,
                      "y":1},
                    "size":{
                      "width":97,
                      "height":27},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7e6bc00a8aa243c785f2c32c293c9e76",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e6c1505df5544cb58efd3bc3738d5ba9",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF5E5E5E,
                          "opacity":1},
                        "location":{
                          "x":173,
                          "y":1},
                        "size":{
                          "width":97,
                          "height":27},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onMouseOut":{
                      "description":"OnMouseOut",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 ",
                              "objectsToFades":[]}]}]}},
                  "images":{
                    "normal~":"images/新闻管理/u12.png"}},
{
                  "id":"10531a2eba6c454a964f8239a80408bf",
                  "label":"",
                  "parentDynamicPanel":"e6c1505df5544cb58efd3bc3738d5ba9",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "location":{
                      "x":173,
                      "y":38},
                    "size":{
                      "width":80,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8915a7fd206b4290b0c4baf0e4ead536",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e6c1505df5544cb58efd3bc3738d5ba9",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontWeight":"700",
                        "location":{
                          "x":173,
                          "y":38},
                        "size":{
                          "width":80,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 KAB概况管理",
                              "target":{
                                "targetType":"page",
                                "url":"kab概况管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"72b3e619f9594f50a4fdc4ddaa75031e",
                  "label":"",
                  "parentDynamicPanel":"e6c1505df5544cb58efd3bc3738d5ba9",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":280,
                      "y":38},
                    "size":{
                      "width":110,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"98aaa27aae8f43bf80a0137c7665d64d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e6c1505df5544cb58efd3bc3738d5ba9",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":280,
                          "y":38},
                        "size":{
                          "width":110,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 创业资讯管理",
                              "target":{
                                "targetType":"page",
                                "url":"创业资讯管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"953eee309ca0482e8e6009d7881096d3",
                  "label":"",
                  "parentDynamicPanel":"e6c1505df5544cb58efd3bc3738d5ba9",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":410,
                      "y":38},
                    "size":{
                      "width":137,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f3aca697b26b485a8e21b553662cf537",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e6c1505df5544cb58efd3bc3738d5ba9",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":410,
                          "y":38},
                        "size":{
                          "width":137,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 KAB课程介绍管理",
                              "target":{
                                "targetType":"page",
                                "url":"kab课程介绍管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"7cfdc4acde1b466bb2042b76c7273ccf",
                  "label":"",
                  "parentDynamicPanel":"e6c1505df5544cb58efd3bc3738d5ba9",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":570,
                      "y":38},
                    "size":{
                      "width":84,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1551a5fa6b374fb29ca6a8be977d0cf6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e6c1505df5544cb58efd3bc3738d5ba9",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":570,
                          "y":38},
                        "size":{
                          "width":84,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 单页管理",
                              "target":{
                                "targetType":"page",
                                "url":"单页管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"296fe2c7c1f04e41a341f34ccbf2d39e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":170,
              "height":51}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12f1d4d4a2d640969bf2412a7f1c91a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":170,
                  "height":51}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改密码_1/u0.jpg"}},
{
          "id":"dc2d4a6a440f4144be247ab814ca0f89",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":598,
              "y":4},
            "size":{
              "width":148,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"727109b73cbb4724a99789fa84ca5e9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":598,
                  "y":4},
                "size":{
                  "width":148,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f9893c624fec4eaabef511e1db6bc5ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":903,
              "y":4},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0139a70bf1904c98b277c96c71a07f8a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":903,
                  "y":4},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 后台登录",
                      "target":{
                        "targetType":"page",
                        "url":"后台登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3bed4d1336db455ebba05f7a0df87e11",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":828,
              "y":4},
            "size":{
              "width":88,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c06ae036b29b4805a6b24f7c4324a68f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":828,
                  "y":4},
                "size":{
                  "width":88,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 修改密码",
                      "target":{
                        "targetType":"page",
                        "url":"修改密码_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2937faaf8fd948c0a2db4f00499da462",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":105},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"094b6e62fe1241a98a3ffe7ab0d0b477",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":48,
                  "y":105},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d17bece7b6ca4ada9e9812ba096666bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":756,
              "y":4},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25fc08369a984ff3a426a4784507e408",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":756,
                  "y":4},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"093b7cb764b4493ebcab8d6ea1aa545a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":31,
              "y":109},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e089363e4b8464dba98742ac76d0d31",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":31,
                  "y":109},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f7fe1cb37eea450ebcf5169f783928d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":31,
              "y":116},
            "size":{
              "width":86,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b810435f64e547b8b4d6c98f046e55ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":31,
                  "y":116},
                "size":{
                  "width":86,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"410510b92b5646f88cb768c23045a274",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":115,
              "y":116},
            "size":{
              "width":80,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ecfed10584764b15b1bfd6540836a4ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":115,
                  "y":116},
                "size":{
                  "width":80,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e46a841614954f169d28cf142bfbcf72",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":37,
              "y":132},
            "size":{
              "width":946,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF949494}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/修改密码_1/u24_line.png"}},
{
          "id":"dd23ac826ed246df8f3d96e285a5c52b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":174},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72d00c828721488994df33e76b7dc795",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":174},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"09410f8e26c24cf1ab2468a3a5814d83",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":144,
              "y":170},
            "size":{
              "width":485,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"3981214bfea04569bbe64e784cd89790",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":224},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64b035b6eede4670a8493292c4e3c2c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":224},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3141a4c2cee64538b7309eb856ff2097",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":144,
              "y":220},
            "size":{
              "width":155,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"82192329bee14405b5b09a5a1b96399b",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":143,
              "y":292},
            "size":{
              "width":477,
              "height":210}},
          "adaptiveStyles":{
}},
{
          "id":"c80ba152457a4f91bc49b32187ede6aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":272},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9abf2065f348415dadca84f89169857c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":272},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"30f4c9402eff458f818a3b3d831924c1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":143,
              "y":267},
            "size":{
              "width":361,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0f85f0ea3d04145aa1d67407c29bd6f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":143,
                  "y":267},
                "size":{
                  "width":361,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加新闻/u41.png"}},
{
          "id":"3de065ff01c743eab718e651d432b25e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF87DB01}}},
            "fill":{
              "fillType":"solid",
              "color":0xFF6AB30C},
            "location":{
              "x":143,
              "y":576},
            "size":{
              "width":81,
              "height":26},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e510fb200d44a04b152b9b67dc44c18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF87DB01}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF6AB30C},
                "location":{
                  "x":143,
                  "y":576},
                "size":{
                  "width":81,
                  "height":26},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 alert",
                      "objectsToFades":[{
                          "objectPath":["142540a9dfc54b5e8e6097c0e9a2b4f7"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/修改个人资料/u102.png",
            "mouseOver~":"images/修改个人资料/u102_mouseOver.png"}},
{
          "id":"142540a9dfc54b5e8e6097c0e9a2b4f7",
          "label":"alert",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":380,
              "y":200},
            "size":{
              "width":320,
              "height":190},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"f7192b3a1cdb4de08126e700b9c01378",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"0e0a72b1fc9048ba99f6c32ca8160d4b",
                  "label":"",
                  "parentDynamicPanel":"142540a9dfc54b5e8e6097c0e9a2b4f7",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":280,
                      "height":160}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f3e5fba28a16447ba5b8cfbc95721d90",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"142540a9dfc54b5e8e6097c0e9a2b4f7",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":280,
                          "height":160}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/修改密码_1/u44.png"}},
{
                  "id":"fc01bac52b194d60b714ec4db7c21eb7",
                  "label":"",
                  "parentDynamicPanel":"142540a9dfc54b5e8e6097c0e9a2b4f7",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "location":{
                      "x":42,
                      "y":9},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f742752525c54644992aacb1c9834b94",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"142540a9dfc54b5e8e6097c0e9a2b4f7",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontWeight":"700",
                        "location":{
                          "x":42,
                          "y":9},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d94d9851ba56433a82fa6964a87764a6",
                  "label":"",
                  "parentDynamicPanel":"142540a9dfc54b5e8e6097c0e9a2b4f7",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":26},
                    "size":{
                      "width":280,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/修改密码_1/u48_line.png"}},
{
                  "id":"236150ea9ee34fd2bec81878f23f1dac",
                  "label":"",
                  "parentDynamicPanel":"142540a9dfc54b5e8e6097c0e9a2b4f7",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":101,
                      "y":120},
                    "size":{
                      "width":78,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"91195213111147c8aa76cdbe728c1094",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"142540a9dfc54b5e8e6097c0e9a2b4f7",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4},
                        "location":{
                          "x":101,
                          "y":120},
                        "size":{
                          "width":78,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 alert",
                              "objectsToFades":[{
                                  "objectPath":["142540a9dfc54b5e8e6097c0e9a2b4f7"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/修改密码_1/u49.png"}},
{
                  "id":"d3628c2ea8c4475fba5e77ceaa8bae3e",
                  "label":"",
                  "parentDynamicPanel":"142540a9dfc54b5e8e6097c0e9a2b4f7",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":16,
                      "y":9},
                    "size":{
                      "width":16,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d49c1023cbc74d8f8d8961d7d7c17bd5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"142540a9dfc54b5e8e6097c0e9a2b4f7",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "location":{
                          "x":16,
                          "y":9},
                        "size":{
                          "width":16,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/修改密码_1/u51.png"}},
{
                  "id":"abbcf8c88a59451aaf042d57212ed4cb",
                  "label":"",
                  "parentDynamicPanel":"142540a9dfc54b5e8e6097c0e9a2b4f7",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":126,
                      "y":72},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9123f67b143b4479bf57baa0740f61ac",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"142540a9dfc54b5e8e6097c0e9a2b4f7",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":126,
                          "y":72},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"08ee437c3d76445895dbb8c158f14b82",
                  "label":"",
                  "parentDynamicPanel":"142540a9dfc54b5e8e6097c0e9a2b4f7",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":100,
                      "y":72},
                    "size":{
                      "width":16,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5d840213b83045d4bbb04b88fda88ee8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"142540a9dfc54b5e8e6097c0e9a2b4f7",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "location":{
                          "x":100,
                          "y":72},
                        "size":{
                          "width":16,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/修改密码_1/u55.png"}}]}]},
{
          "id":"039341c77b0943df8dfacab682b7f378",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":143,
              "y":634},
            "size":{
              "width":32,
              "height":1}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da4915b68bdf4e14ad31b92908538954",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":143,
                  "y":634},
                "size":{
                  "width":32,
                  "height":1}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "e6c1505df5544cb58efd3bc3738d5ba9":{
      "scriptId":"u0"},
    "a1ac1fc37cc04d38a0a5f0c5a9809741":{
      "scriptId":"u1"},
    "65c4b387bea74707a3c97872024892a0":{
      "scriptId":"u2"},
    "64ff3219bc374d07b094a1b93d8dff03":{
      "scriptId":"u3"},
    "50b315d0d2e64846b4cf871d1cc1c70a":{
      "scriptId":"u4"},
    "78dbfafa0a714834bda7b63825dea9f0":{
      "scriptId":"u5"},
    "ed222b5284444f4ca3b1748731163b3a":{
      "scriptId":"u6"},
    "06886f78b301450fa2246fb87825a17d":{
      "scriptId":"u7"},
    "b7a0eeb1153f40eca80946843d643e51":{
      "scriptId":"u8"},
    "fc0f8bf41608438b9429c7e6454237b9":{
      "scriptId":"u9"},
    "88154bb6c17f41c18084a3dddc7f1036":{
      "scriptId":"u10"},
    "5bfea81d40ae455e86626305bfd707a7":{
      "scriptId":"u11"},
    "70df364cc2044f68a637df15e05053af":{
      "scriptId":"u12"},
    "7e6bc00a8aa243c785f2c32c293c9e76":{
      "scriptId":"u13"},
    "10531a2eba6c454a964f8239a80408bf":{
      "scriptId":"u14"},
    "8915a7fd206b4290b0c4baf0e4ead536":{
      "scriptId":"u15"},
    "72b3e619f9594f50a4fdc4ddaa75031e":{
      "scriptId":"u16"},
    "98aaa27aae8f43bf80a0137c7665d64d":{
      "scriptId":"u17"},
    "953eee309ca0482e8e6009d7881096d3":{
      "scriptId":"u18"},
    "f3aca697b26b485a8e21b553662cf537":{
      "scriptId":"u19"},
    "7cfdc4acde1b466bb2042b76c7273ccf":{
      "scriptId":"u20"},
    "1551a5fa6b374fb29ca6a8be977d0cf6":{
      "scriptId":"u21"},
    "296fe2c7c1f04e41a341f34ccbf2d39e":{
      "scriptId":"u22"},
    "12f1d4d4a2d640969bf2412a7f1c91a2":{
      "scriptId":"u23"},
    "dc2d4a6a440f4144be247ab814ca0f89":{
      "scriptId":"u24"},
    "727109b73cbb4724a99789fa84ca5e9d":{
      "scriptId":"u25"},
    "f9893c624fec4eaabef511e1db6bc5ca":{
      "scriptId":"u26"},
    "0139a70bf1904c98b277c96c71a07f8a":{
      "scriptId":"u27"},
    "3bed4d1336db455ebba05f7a0df87e11":{
      "scriptId":"u28"},
    "c06ae036b29b4805a6b24f7c4324a68f":{
      "scriptId":"u29"},
    "2937faaf8fd948c0a2db4f00499da462":{
      "scriptId":"u30"},
    "094b6e62fe1241a98a3ffe7ab0d0b477":{
      "scriptId":"u31"},
    "d17bece7b6ca4ada9e9812ba096666bd":{
      "scriptId":"u32"},
    "25fc08369a984ff3a426a4784507e408":{
      "scriptId":"u33"},
    "093b7cb764b4493ebcab8d6ea1aa545a":{
      "scriptId":"u34"},
    "9e089363e4b8464dba98742ac76d0d31":{
      "scriptId":"u35"},
    "f7fe1cb37eea450ebcf5169f783928d5":{
      "scriptId":"u36"},
    "b810435f64e547b8b4d6c98f046e55ba":{
      "scriptId":"u37"},
    "410510b92b5646f88cb768c23045a274":{
      "scriptId":"u38"},
    "ecfed10584764b15b1bfd6540836a4ed":{
      "scriptId":"u39"},
    "e46a841614954f169d28cf142bfbcf72":{
      "scriptId":"u40"},
    "dd23ac826ed246df8f3d96e285a5c52b":{
      "scriptId":"u41"},
    "72d00c828721488994df33e76b7dc795":{
      "scriptId":"u42"},
    "09410f8e26c24cf1ab2468a3a5814d83":{
      "scriptId":"u43"},
    "3981214bfea04569bbe64e784cd89790":{
      "scriptId":"u44"},
    "64b035b6eede4670a8493292c4e3c2c5":{
      "scriptId":"u45"},
    "3141a4c2cee64538b7309eb856ff2097":{
      "scriptId":"u46"},
    "82192329bee14405b5b09a5a1b96399b":{
      "scriptId":"u47"},
    "c80ba152457a4f91bc49b32187ede6aa":{
      "scriptId":"u48"},
    "9abf2065f348415dadca84f89169857c":{
      "scriptId":"u49"},
    "30f4c9402eff458f818a3b3d831924c1":{
      "scriptId":"u50"},
    "d0f85f0ea3d04145aa1d67407c29bd6f":{
      "scriptId":"u51"},
    "3de065ff01c743eab718e651d432b25e":{
      "scriptId":"u52"},
    "9e510fb200d44a04b152b9b67dc44c18":{
      "scriptId":"u53"},
    "142540a9dfc54b5e8e6097c0e9a2b4f7":{
      "scriptId":"u54"},
    "0e0a72b1fc9048ba99f6c32ca8160d4b":{
      "scriptId":"u55"},
    "f3e5fba28a16447ba5b8cfbc95721d90":{
      "scriptId":"u56"},
    "fc01bac52b194d60b714ec4db7c21eb7":{
      "scriptId":"u57"},
    "f742752525c54644992aacb1c9834b94":{
      "scriptId":"u58"},
    "d94d9851ba56433a82fa6964a87764a6":{
      "scriptId":"u59"},
    "236150ea9ee34fd2bec81878f23f1dac":{
      "scriptId":"u60"},
    "91195213111147c8aa76cdbe728c1094":{
      "scriptId":"u61"},
    "d3628c2ea8c4475fba5e77ceaa8bae3e":{
      "scriptId":"u62"},
    "d49c1023cbc74d8f8d8961d7d7c17bd5":{
      "scriptId":"u63"},
    "abbcf8c88a59451aaf042d57212ed4cb":{
      "scriptId":"u64"},
    "9123f67b143b4479bf57baa0740f61ac":{
      "scriptId":"u65"},
    "08ee437c3d76445895dbb8c158f14b82":{
      "scriptId":"u66"},
    "5d840213b83045d4bbb04b88fda88ee8":{
      "scriptId":"u67"},
    "039341c77b0943df8dfacab682b7f378":{
      "scriptId":"u68"},
    "da4915b68bdf4e14ad31b92908538954":{
      "scriptId":"u69"}}});