$axure.loadCurrentPage({
  "url":"添加课程介绍.html",
  "generationDate":new Date(1383013850400.19),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7fc5debae922446885890c71b66ad069",
    "type":"Axure:Page",
    "name":"添加课程介绍",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c60d0b20ccf74444b3f9cc982d672858",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":170,
              "height":51}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"80984ef1d00c49399d6a8d17352eb55b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":170,
                  "height":51}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改密码_1/u0.jpg"}},
{
          "id":"1445bb1b19564d11bfa95b951f74832d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":133},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d21000f9c1b0433a8475a91f44f7d499",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":48,
                  "y":133},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"33b8bd2237aa4c189a2db77e388204b8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":598,
              "y":4},
            "size":{
              "width":148,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1293eddbc134cdf831b469ed8ad00a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":598,
                  "y":4},
                "size":{
                  "width":148,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a35b98c7741c4e858b350befb62ca314",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":903,
              "y":4},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b82c0b6f03d646798af37fc76138510b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":903,
                  "y":4},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 后台登录",
                      "target":{
                        "targetType":"page",
                        "url":"后台登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b1848780c7e54078839c049d308a6839",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":828,
              "y":4},
            "size":{
              "width":88,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bd2648f8cee403db79837a84c9ac00c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":828,
                  "y":4},
                "size":{
                  "width":88,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 修改密码",
                      "target":{
                        "targetType":"page",
                        "url":"修改密码_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"06005e63de5847bbb28717657defb48d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":756,
              "y":4},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8dadd6d4dfd44ff4a5bd6ea7681204fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":756,
                  "y":4},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c43e79d51f144515aab51862af375255",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":79,
              "y":177},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d454c12326ad45979aad5cd57b80cb79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":79,
                  "y":177},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d389c12d214e415693fb71564862a720",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":145},
            "size":{
              "width":946,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF949494}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/修改密码_1/u24_line.png"}},
{
          "id":"b813678148ab4b769bd796b17fd2fa1d",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":143,
              "y":173},
            "size":{
              "width":477,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"71e1f102007d46878eebd0a642818a44",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":143,
              "y":368},
            "size":{
              "width":477,
              "height":210}},
          "adaptiveStyles":{
}},
{
          "id":"4589a10dcbf94aa3b62c431436d090fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":79,
              "y":348},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69f36baa403f42e28ad0db3d6b146c96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":79,
                  "y":348},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6555b200261e428dba7f988e2a727004",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":53,
              "y":285},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9a1df78fa244d50b2757aa7713fbb6a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":53,
                  "y":285},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"86b5bc2bff33457984d84679ad2ad67f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":143,
              "y":343},
            "size":{
              "width":361,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4fca03aa552b42f6932c9fefd73dafbf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":143,
                  "y":343},
                "size":{
                  "width":361,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加新闻/u41.png"}},
{
          "id":"9ce63d832f93415aba8e831903d250f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":77,
              "y":228},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c261da604f24acda20d918f1d13372f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":77,
                  "y":228},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3a94a93b072d490a8e0c0909143f9bb6",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":143,
              "y":224},
            "size":{
              "width":190,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"49645c08f7334c60bab6e2819bfd0fe7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF87DB01}}},
            "fill":{
              "fillType":"solid",
              "color":0xFF6AB30C},
            "location":{
              "x":143,
              "y":624},
            "size":{
              "width":81,
              "height":26},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10bb6b88934f4551a7c64a17944ab824",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF87DB01}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF6AB30C},
                "location":{
                  "x":143,
                  "y":624},
                "size":{
                  "width":81,
                  "height":26},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 alert",
                      "objectsToFades":[{
                          "objectPath":["e233490c585a4672b23262f38934f761"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/修改个人资料/u102.png",
            "mouseOver~":"images/修改个人资料/u102_mouseOver.png"}},
{
          "id":"d527e39ea0644173a80d9ffda82cf7d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF87DB01}}},
            "fill":{
              "fillType":"solid",
              "color":0xFF6AB30C},
            "location":{
              "x":262,
              "y":624},
            "size":{
              "width":81,
              "height":26},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16cf34f84ccd4e70a636c3451dffcd5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF87DB01}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF6AB30C},
                "location":{
                  "x":262,
                  "y":624},
                "size":{
                  "width":81,
                  "height":26},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 KAB课程介绍管理",
                      "target":{
                        "targetType":"page",
                        "url":"kab课程介绍管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/修改个人资料/u102.png",
            "mouseOver~":"images/修改个人资料/u102_mouseOver.png"}},
{
          "id":"e233490c585a4672b23262f38934f761",
          "label":"alert",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":380,
              "y":276},
            "size":{
              "width":320,
              "height":190},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"90ae3419fe3d4306be1fd3d6b9db9804",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"192bedbaf3f541438857a37882aaccff",
                  "label":"",
                  "parentDynamicPanel":"e233490c585a4672b23262f38934f761",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":280,
                      "height":160}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"de431b86f8714abfb3c11d0619972555",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e233490c585a4672b23262f38934f761",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":280,
                          "height":160}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/修改密码_1/u44.png"}},
{
                  "id":"931c669242814e27aa4fa8cfb7d38a65",
                  "label":"",
                  "parentDynamicPanel":"e233490c585a4672b23262f38934f761",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "location":{
                      "x":42,
                      "y":9},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"56c43433ce754655996bd47b152977f5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e233490c585a4672b23262f38934f761",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontWeight":"700",
                        "location":{
                          "x":42,
                          "y":9},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"452a2bf159904d5f91c82f1ce76b6ee8",
                  "label":"",
                  "parentDynamicPanel":"e233490c585a4672b23262f38934f761",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":26},
                    "size":{
                      "width":280,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/修改密码_1/u48_line.png"}},
{
                  "id":"feb0c0f0e8994d8c90357fa311aacb3e",
                  "label":"",
                  "parentDynamicPanel":"e233490c585a4672b23262f38934f761",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":101,
                      "y":120},
                    "size":{
                      "width":78,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5151edfadf4749fe8cc2e1f0177846ca",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e233490c585a4672b23262f38934f761",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4},
                        "location":{
                          "x":101,
                          "y":120},
                        "size":{
                          "width":78,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 alert",
                              "objectsToFades":[{
                                  "objectPath":["e233490c585a4672b23262f38934f761"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]},
{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 KAB课程介绍管理",
                              "target":{
                                "targetType":"page",
                                "url":"kab课程介绍管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/修改密码_1/u49.png"}},
{
                  "id":"547566a6b2f54104a47ff06277fe986c",
                  "label":"",
                  "parentDynamicPanel":"e233490c585a4672b23262f38934f761",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":16,
                      "y":9},
                    "size":{
                      "width":16,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"dfd81f004f1443268510049460acbc78",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e233490c585a4672b23262f38934f761",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "location":{
                          "x":16,
                          "y":9},
                        "size":{
                          "width":16,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/修改密码_1/u51.png"}},
{
                  "id":"9cdf9420bee9472e9f72c236db8cbca3",
                  "label":"",
                  "parentDynamicPanel":"e233490c585a4672b23262f38934f761",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":126,
                      "y":72},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"30006162fcd74ffb9f53018d41e7c558",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e233490c585a4672b23262f38934f761",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":126,
                          "y":72},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"326daffdbd534ba288813e089e1ad2f7",
                  "label":"",
                  "parentDynamicPanel":"e233490c585a4672b23262f38934f761",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":100,
                      "y":72},
                    "size":{
                      "width":16,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"87d255644ab740a38b1016e656a8dc7a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e233490c585a4672b23262f38934f761",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "location":{
                          "x":100,
                          "y":72},
                        "size":{
                          "width":16,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/修改密码_1/u55.png"}}]}]},
{
          "id":"d6d0634f98e54e4ea42e524c442c3f44",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":31,
              "y":131},
            "size":{
              "width":82,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0dffaf3bd73d4cbe878d4a3f8fe272bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":31,
                  "y":131},
                "size":{
                  "width":82,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"71fd6b8a9aca4f8d99110bdc75f2d00d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":115,
              "y":131},
            "size":{
              "width":80,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b7b5e71deaa43d5824f9c72022baa6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":115,
                  "y":131},
                "size":{
                  "width":80,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 创业资讯管理",
                      "target":{
                        "targetType":"page",
                        "url":"创业资讯管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"614c0d54aecc45a08d7fed4151afa7b6",
          "label":"导航",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":50},
            "size":{
              "width":716,
              "height":129}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"aa9c1546d19348ccb45f4d4cb0abe726",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"a5cd7b7864da491fb696828453a80c26",
                  "label":"",
                  "parentDynamicPanel":"614c0d54aecc45a08d7fed4151afa7b6",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":90,
                      "y":7},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e199a85000a04f85baf2734756a4b096",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"614c0d54aecc45a08d7fed4151afa7b6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":90,
                          "y":7},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 新闻管理",
                              "target":{
                                "targetType":"page",
                                "url":"新闻管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"4f4493a516ee4578bdd92b850f3cde73",
                  "label":"",
                  "parentDynamicPanel":"614c0d54aecc45a08d7fed4151afa7b6",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":300,
                      "y":7},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"56c8f27abd2d4266a08f3fec51052593",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"614c0d54aecc45a08d7fed4151afa7b6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":300,
                          "y":7},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 KAB公告管理",
                              "target":{
                                "targetType":"page",
                                "url":"kab公告管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"17eddb96d85748cc9a7e7784e408c5c5",
                  "label":"",
                  "parentDynamicPanel":"614c0d54aecc45a08d7fed4151afa7b6",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":407,
                      "y":7},
                    "size":{
                      "width":79,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bc3cdfdf9d984c92a52fa015197fe9c0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"614c0d54aecc45a08d7fed4151afa7b6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":407,
                          "y":7},
                        "size":{
                          "width":79,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 班级管理",
                              "target":{
                                "targetType":"page",
                                "url":"班级管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"4d2161fdfd6b46f3801c6bff095b0a05",
                  "label":"",
                  "parentDynamicPanel":"614c0d54aecc45a08d7fed4151afa7b6",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":542,
                      "y":7},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f8fe3456f2c749f9b76fc6c7c79a50cb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"614c0d54aecc45a08d7fed4151afa7b6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":542,
                          "y":7},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 用户管理",
                              "target":{
                                "targetType":"page",
                                "url":"用户管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"6ae70657229946c5a1f018f785b05948",
                  "label":"",
                  "parentDynamicPanel":"614c0d54aecc45a08d7fed4151afa7b6",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":637,
                      "y":7},
                    "size":{
                      "width":79,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b141d11057d8490e89f094092dc93158",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"614c0d54aecc45a08d7fed4151afa7b6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":637,
                          "y":7},
                        "size":{
                          "width":79,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 系统参数配置",
                              "target":{
                                "targetType":"page",
                                "url":"系统参数配置.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"21c27c9dcd814bc8bcc31796c5687dc0",
                  "label":"",
                  "parentDynamicPanel":"614c0d54aecc45a08d7fed4151afa7b6",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":22},
                    "size":{
                      "width":1000,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/修改密码_1/u21_line.png"}},
{
                  "id":"ae4606b7c70842a6847b901683d47dbe",
                  "label":"",
                  "parentDynamicPanel":"614c0d54aecc45a08d7fed4151afa7b6",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF5E5E5E,
                      "opacity":1},
                    "location":{
                      "x":173,
                      "y":1},
                    "size":{
                      "width":97,
                      "height":27},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d2c4c7b555334cf2b8367d2fe8e24a90",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"614c0d54aecc45a08d7fed4151afa7b6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF5E5E5E,
                          "opacity":1},
                        "location":{
                          "x":173,
                          "y":1},
                        "size":{
                          "width":97,
                          "height":27},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onMouseOut":{
                      "description":"OnMouseOut",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 ",
                              "objectsToFades":[]}]}]}},
                  "images":{
                    "normal~":"images/新闻管理/u12.png"}},
{
                  "id":"67e38765b81b4d939842718314664402",
                  "label":"",
                  "parentDynamicPanel":"614c0d54aecc45a08d7fed4151afa7b6",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":173,
                      "y":38},
                    "size":{
                      "width":80,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c06a623695004a36b001f9d7a0d9783f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"614c0d54aecc45a08d7fed4151afa7b6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":173,
                          "y":38},
                        "size":{
                          "width":80,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 KAB概况管理",
                              "target":{
                                "targetType":"page",
                                "url":"kab概况管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"ce004e689f13423897cce451e5bb465c",
                  "label":"",
                  "parentDynamicPanel":"614c0d54aecc45a08d7fed4151afa7b6",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":280,
                      "y":38},
                    "size":{
                      "width":110,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1ca1359e763b4c6983a26208447f2c8f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"614c0d54aecc45a08d7fed4151afa7b6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":280,
                          "y":38},
                        "size":{
                          "width":110,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 创业资讯管理",
                              "target":{
                                "targetType":"page",
                                "url":"创业资讯管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"cc690beee7df4423be7c729327095d44",
                  "label":"",
                  "parentDynamicPanel":"614c0d54aecc45a08d7fed4151afa7b6",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "location":{
                      "x":410,
                      "y":38},
                    "size":{
                      "width":137,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"efb142d4525c42679ee54805c345c00c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"614c0d54aecc45a08d7fed4151afa7b6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontWeight":"700",
                        "location":{
                          "x":410,
                          "y":38},
                        "size":{
                          "width":137,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 KAB课程介绍管理",
                              "target":{
                                "targetType":"page",
                                "url":"kab课程介绍管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"aac6d5d901714172b3df3b260d641389",
                  "label":"",
                  "parentDynamicPanel":"614c0d54aecc45a08d7fed4151afa7b6",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":570,
                      "y":38},
                    "size":{
                      "width":84,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ad92c5a75dfd4e3dbc1315a005d2e55f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"614c0d54aecc45a08d7fed4151afa7b6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":570,
                          "y":38},
                        "size":{
                          "width":84,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 单页管理",
                              "target":{
                                "targetType":"page",
                                "url":"单页管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"6011ad3d37df4080bd2012507f27deda",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":205,
              "y":131},
            "size":{
              "width":123,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c191d03774ff4adf889857afecceab51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":205,
                  "y":131},
                "size":{
                  "width":123,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"000f42f6b75f4be8aaf980f3e22a7d88",
          "label":"1",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":143,
              "y":285},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a1f1bb48dc7546c2bce196c8d4dbcf42",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":143,
                  "y":285},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 1 等于 &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["000f42f6b75f4be8aaf980f3e22a7d88"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}},
{
                      "action":"setFunction",
                      "description":"设置 被选中的 2 等于 &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["1d074616bba64dbd98fc68331468d79c"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}}},
{
          "id":"1d074616bba64dbd98fc68331468d79c",
          "label":"2",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":253,
              "y":285},
            "size":{
              "width":47,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c3368004d514af180dc281488258c06",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":253,
                  "y":285},
                "size":{
                  "width":47,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 2 等于 &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["1d074616bba64dbd98fc68331468d79c"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}},
{
                      "action":"setFunction",
                      "description":"设置 被选中的 1 等于 &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["000f42f6b75f4be8aaf980f3e22a7d88"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}}}]}},
  "masters":{
},
  "objectPaths":{
    "c60d0b20ccf74444b3f9cc982d672858":{
      "scriptId":"u0"},
    "80984ef1d00c49399d6a8d17352eb55b":{
      "scriptId":"u1"},
    "1445bb1b19564d11bfa95b951f74832d":{
      "scriptId":"u2"},
    "d21000f9c1b0433a8475a91f44f7d499":{
      "scriptId":"u3"},
    "33b8bd2237aa4c189a2db77e388204b8":{
      "scriptId":"u4"},
    "f1293eddbc134cdf831b469ed8ad00a0":{
      "scriptId":"u5"},
    "a35b98c7741c4e858b350befb62ca314":{
      "scriptId":"u6"},
    "b82c0b6f03d646798af37fc76138510b":{
      "scriptId":"u7"},
    "b1848780c7e54078839c049d308a6839":{
      "scriptId":"u8"},
    "4bd2648f8cee403db79837a84c9ac00c":{
      "scriptId":"u9"},
    "06005e63de5847bbb28717657defb48d":{
      "scriptId":"u10"},
    "8dadd6d4dfd44ff4a5bd6ea7681204fd":{
      "scriptId":"u11"},
    "c43e79d51f144515aab51862af375255":{
      "scriptId":"u12"},
    "d454c12326ad45979aad5cd57b80cb79":{
      "scriptId":"u13"},
    "d389c12d214e415693fb71564862a720":{
      "scriptId":"u14"},
    "b813678148ab4b769bd796b17fd2fa1d":{
      "scriptId":"u15"},
    "71e1f102007d46878eebd0a642818a44":{
      "scriptId":"u16"},
    "4589a10dcbf94aa3b62c431436d090fa":{
      "scriptId":"u17"},
    "69f36baa403f42e28ad0db3d6b146c96":{
      "scriptId":"u18"},
    "6555b200261e428dba7f988e2a727004":{
      "scriptId":"u19"},
    "e9a1df78fa244d50b2757aa7713fbb6a":{
      "scriptId":"u20"},
    "86b5bc2bff33457984d84679ad2ad67f":{
      "scriptId":"u21"},
    "4fca03aa552b42f6932c9fefd73dafbf":{
      "scriptId":"u22"},
    "9ce63d832f93415aba8e831903d250f2":{
      "scriptId":"u23"},
    "6c261da604f24acda20d918f1d13372f":{
      "scriptId":"u24"},
    "3a94a93b072d490a8e0c0909143f9bb6":{
      "scriptId":"u25"},
    "49645c08f7334c60bab6e2819bfd0fe7":{
      "scriptId":"u26"},
    "10bb6b88934f4551a7c64a17944ab824":{
      "scriptId":"u27"},
    "d527e39ea0644173a80d9ffda82cf7d9":{
      "scriptId":"u28"},
    "16cf34f84ccd4e70a636c3451dffcd5e":{
      "scriptId":"u29"},
    "e233490c585a4672b23262f38934f761":{
      "scriptId":"u30"},
    "192bedbaf3f541438857a37882aaccff":{
      "scriptId":"u31"},
    "de431b86f8714abfb3c11d0619972555":{
      "scriptId":"u32"},
    "931c669242814e27aa4fa8cfb7d38a65":{
      "scriptId":"u33"},
    "56c43433ce754655996bd47b152977f5":{
      "scriptId":"u34"},
    "452a2bf159904d5f91c82f1ce76b6ee8":{
      "scriptId":"u35"},
    "feb0c0f0e8994d8c90357fa311aacb3e":{
      "scriptId":"u36"},
    "5151edfadf4749fe8cc2e1f0177846ca":{
      "scriptId":"u37"},
    "547566a6b2f54104a47ff06277fe986c":{
      "scriptId":"u38"},
    "dfd81f004f1443268510049460acbc78":{
      "scriptId":"u39"},
    "9cdf9420bee9472e9f72c236db8cbca3":{
      "scriptId":"u40"},
    "30006162fcd74ffb9f53018d41e7c558":{
      "scriptId":"u41"},
    "326daffdbd534ba288813e089e1ad2f7":{
      "scriptId":"u42"},
    "87d255644ab740a38b1016e656a8dc7a":{
      "scriptId":"u43"},
    "d6d0634f98e54e4ea42e524c442c3f44":{
      "scriptId":"u44"},
    "0dffaf3bd73d4cbe878d4a3f8fe272bf":{
      "scriptId":"u45"},
    "71fd6b8a9aca4f8d99110bdc75f2d00d":{
      "scriptId":"u46"},
    "7b7b5e71deaa43d5824f9c72022baa6e":{
      "scriptId":"u47"},
    "614c0d54aecc45a08d7fed4151afa7b6":{
      "scriptId":"u48"},
    "a5cd7b7864da491fb696828453a80c26":{
      "scriptId":"u49"},
    "e199a85000a04f85baf2734756a4b096":{
      "scriptId":"u50"},
    "4f4493a516ee4578bdd92b850f3cde73":{
      "scriptId":"u51"},
    "56c8f27abd2d4266a08f3fec51052593":{
      "scriptId":"u52"},
    "17eddb96d85748cc9a7e7784e408c5c5":{
      "scriptId":"u53"},
    "bc3cdfdf9d984c92a52fa015197fe9c0":{
      "scriptId":"u54"},
    "4d2161fdfd6b46f3801c6bff095b0a05":{
      "scriptId":"u55"},
    "f8fe3456f2c749f9b76fc6c7c79a50cb":{
      "scriptId":"u56"},
    "6ae70657229946c5a1f018f785b05948":{
      "scriptId":"u57"},
    "b141d11057d8490e89f094092dc93158":{
      "scriptId":"u58"},
    "21c27c9dcd814bc8bcc31796c5687dc0":{
      "scriptId":"u59"},
    "ae4606b7c70842a6847b901683d47dbe":{
      "scriptId":"u60"},
    "d2c4c7b555334cf2b8367d2fe8e24a90":{
      "scriptId":"u61"},
    "67e38765b81b4d939842718314664402":{
      "scriptId":"u62"},
    "c06a623695004a36b001f9d7a0d9783f":{
      "scriptId":"u63"},
    "ce004e689f13423897cce451e5bb465c":{
      "scriptId":"u64"},
    "1ca1359e763b4c6983a26208447f2c8f":{
      "scriptId":"u65"},
    "cc690beee7df4423be7c729327095d44":{
      "scriptId":"u66"},
    "efb142d4525c42679ee54805c345c00c":{
      "scriptId":"u67"},
    "aac6d5d901714172b3df3b260d641389":{
      "scriptId":"u68"},
    "ad92c5a75dfd4e3dbc1315a005d2e55f":{
      "scriptId":"u69"},
    "6011ad3d37df4080bd2012507f27deda":{
      "scriptId":"u70"},
    "c191d03774ff4adf889857afecceab51":{
      "scriptId":"u71"},
    "000f42f6b75f4be8aaf980f3e22a7d88":{
      "scriptId":"u72"},
    "a1f1bb48dc7546c2bce196c8d4dbcf42":{
      "scriptId":"u73"},
    "1d074616bba64dbd98fc68331468d79c":{
      "scriptId":"u74"},
    "8c3368004d514af180dc281488258c06":{
      "scriptId":"u75"}}});