$axure.loadCurrentPage({
  "url":"kab概况.html",
  "generationDate":new Date(1383013846818.98),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a83312648ca546c197ed06ce39d2d5bf",
    "type":"Axure:Page",
    "name":"KAB概况",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5c5da3600744457cba2057e3e47d5b09",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":114,
              "y":6},
            "size":{
              "width":149,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7cc2a170b35d44328416c0b49694cd71",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":114,
                  "y":6},
                "size":{
                  "width":149,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"31f1332b2f7043b7b108b34d0ab9bfac",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":900,
              "y":6},
            "size":{
              "width":42,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d613856cb8d940f89de33b43f7bc2995",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":900,
                  "y":6},
                "size":{
                  "width":42,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"50398d9608dd4ad988225c5dc68bd4ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":952,
              "y":6},
            "size":{
              "width":64,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a04ddf1344741f0ad337c0c5ba58cd7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":952,
                  "y":6},
                "size":{
                  "width":64,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f6a2e9672d69406e9d14b6254a785fe2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1028,
              "y":7},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cdb2244c058d4be5a1fe473e5880e175",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1028,
                  "y":7},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"42e0cb3be8134f34b6d8e24734170e9a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":21},
            "size":{
              "width":1200,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE0E0E0}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页/u10_line.png"}},
{
          "id":"9af6ade80e554ee59d483af129db2c1f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":26},
            "size":{
              "width":1200,
              "height":106},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF5C5D5F}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f62a79aa0c9444b0976f6e141f8f439d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":26},
                "size":{
                  "width":1200,
                  "height":106},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF5C5D5F}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u11.jpg"}},
{
          "id":"c1ea634281284383ad7863a884d79748",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":390,
              "y":126},
            "size":{
              "width":790,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/kab概况/u11_line.png"}},
{
          "id":"379b8b249acf462bb81a164b86d747e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":299,
              "y":6},
            "size":{
              "width":213,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae9a397774e34fe886cb259af0ffe068",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":299,
                  "y":6},
                "size":{
                  "width":213,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"07b0c0c8c6d64ac89f655ec0e5c70180",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":512,
              "y":6},
            "size":{
              "width":61,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19dfff27405a46a8bdef68332687d173",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":512,
                  "y":6},
                "size":{
                  "width":61,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 管理班级",
                      "target":{
                        "targetType":"page",
                        "url":"管理班级.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"304027be4b814c72bdbb5a6ee35451ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":583,
              "y":6},
            "size":{
              "width":35,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd8aa8d0079447e9b10885f431d14967",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":583,
                  "y":6},
                "size":{
                  "width":35,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 会员登录",
                      "target":{
                        "targetType":"page",
                        "url":"会员登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6a1a5b4ecc6f404ea65a6d6bc483862d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":99,
              "y":26},
            "size":{
              "width":276,
              "height":106}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b30d25d28a2460facd37fde099bf24c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":99,
                  "y":26},
                "size":{
                  "width":276,
                  "height":106}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"00a9129cf91344a8be921bf3ad5e19d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":131,
              "y":154},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0964b65b70541cb8a9838d8fe66dfa1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":131,
                  "y":154},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"98ea43d715f948a6b98208e3efd377c9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":112,
              "y":152},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"06636bc80d06428fb67c25ee03095def",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":112,
                  "y":152},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/kab概况/u22.png"}},
{
          "id":"567be5e5acab479789326f3d73860ce3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":168,
              "y":154},
            "size":{
              "width":17,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bcaa006b669940bda5c1a9bd6f9c4513",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":168,
                  "y":154},
                "size":{
                  "width":17,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b2163907c75d42b8807c42d96166ab10",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":195,
              "y":154},
            "size":{
              "width":54,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f877ce70787d44fa893c7a6fc5d0ed5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":195,
                  "y":154},
                "size":{
                  "width":54,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"be75d034ba34429d8eba06c0ec4142f1",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":170},
            "size":{
              "width":1001,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF949494}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/kab概况/u28_line.png"}},
{
          "id":"bec4e2eb08da47289bb086a45f34ef41",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":114,
              "y":233},
            "size":{
              "width":967,
              "height":1466}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e3bf33e83c54559be1f0a84336ebf3c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":114,
                  "y":233},
                "size":{
                  "width":967,
                  "height":1466}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2c620e3cb9d94931a9e0fbe47c6321ff",
          "label":"主导航",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":385,
              "y":100},
            "size":{
              "width":691,
              "height":44}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"e1e12b27402e4ccea04f4c84e55bd71f",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"0f26648c1c0b4099aae426c6e7694d41",
                  "label":"",
                  "parentDynamicPanel":"2c620e3cb9d94931a9e0fbe47c6321ff",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"14px",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "fontSize":"14px",
                        "fontWeight":"bold",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "fill":{
                          "fillType":"linearGradient",
                          "colors":[{
                              "color":0xFFFFFFFF},
{
                              "color":0xFFFFFFFF},
{
                              "color":0xFFDDEFC4},
{
                              "color":0xFFFFFFFF},
{
                              "color":0xFFFFFFFF},
{
                              "color":0xFF6FBE00},
{
                              "color":0xFF6FBE00}]}}},
                    "size":{
                      "width":90,
                      "height":35},
                    "borderWidth":"-1",
                    "cornerRadiusTopLeft":"2"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0ad43b672c544ac8b01d8bb4eac3e725",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2c620e3cb9d94931a9e0fbe47c6321ff",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontSize":"14px",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "fontSize":"14px",
                            "fontWeight":"bold",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF000000,
                              "opacity":1},
                            "fill":{
                              "fillType":"linearGradient",
                              "colors":[{
                                  "color":0xFFFFFFFF},
{
                                  "color":0xFFFFFFFF},
{
                                  "color":0xFFDDEFC4},
{
                                  "color":0xFFFFFFFF},
{
                                  "color":0xFFFFFFFF},
{
                                  "color":0xFF6FBE00},
{
                                  "color":0xFF6FBE00}]}}},
                        "size":{
                          "width":90,
                          "height":35},
                        "borderWidth":"-1",
                        "cornerRadiusTopLeft":"2"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 首页",
                              "target":{
                                "targetType":"page",
                                "url":"首页.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/首页/u212.png",
                    "mouseOver~":"images/首页/u212_mouseOver.png"}},
{
                  "id":"2636471d7bd643b9bfaa809dbb2b74d3",
                  "label":"",
                  "parentDynamicPanel":"2c620e3cb9d94931a9e0fbe47c6321ff",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"14px",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "fontSize":"14px",
                        "fontWeight":"bold",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "fill":{
                          "fillType":"linearGradient",
                          "colors":[{
                              "color":0xFFFFFFFF},
{
                              "color":0xFFFFFFFF},
{
                              "color":0xFFDDEFC4},
{
                              "color":0xFFFFFFFF},
{
                              "color":0xFFFFFFFF},
{
                              "color":0xFF6FBE00},
{
                              "color":0xFF6FBE00}]}}},
                    "location":{
                      "x":199,
                      "y":0},
                    "size":{
                      "width":90,
                      "height":35},
                    "borderWidth":"-1",
                    "cornerRadiusTopLeft":"2"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4592b197980a407294cadca57b17873c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2c620e3cb9d94931a9e0fbe47c6321ff",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontSize":"14px",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "fontSize":"14px",
                            "fontWeight":"bold",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF000000,
                              "opacity":1},
                            "fill":{
                              "fillType":"linearGradient",
                              "colors":[{
                                  "color":0xFFFFFFFF},
{
                                  "color":0xFFFFFFFF},
{
                                  "color":0xFFDDEFC4},
{
                                  "color":0xFFFFFFFF},
{
                                  "color":0xFFFFFFFF},
{
                                  "color":0xFF6FBE00},
{
                                  "color":0xFF6FBE00}]}}},
                        "location":{
                          "x":199,
                          "y":0},
                        "size":{
                          "width":90,
                          "height":35},
                        "borderWidth":"-1",
                        "cornerRadiusTopLeft":"2"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 KAB公告",
                              "target":{
                                "targetType":"page",
                                "url":"kab公告.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/首页/u212.png",
                    "mouseOver~":"images/首页/u212_mouseOver.png"}},
{
                  "id":"f518f1e080a2467f86c02f1db22c2790",
                  "label":"",
                  "parentDynamicPanel":"2c620e3cb9d94931a9e0fbe47c6321ff",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"14px",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "fontSize":"14px",
                        "fontWeight":"bold",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "fill":{
                          "fillType":"linearGradient",
                          "colors":[{
                              "color":0xFFFFFFFF},
{
                              "color":0xFFFFFFFF},
{
                              "color":0xFFDDEFC4},
{
                              "color":0xFFFFFFFF},
{
                              "color":0xFFFFFFFF},
{
                              "color":0xFF6FBE00},
{
                              "color":0xFF6FBE00}]}}},
                    "location":{
                      "x":299,
                      "y":0},
                    "size":{
                      "width":90,
                      "height":35},
                    "borderWidth":"-1",
                    "cornerRadiusTopLeft":"2"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bb5db80a05544bcf90135b1af49bc895",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2c620e3cb9d94931a9e0fbe47c6321ff",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontSize":"14px",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "fontSize":"14px",
                            "fontWeight":"bold",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF000000,
                              "opacity":1},
                            "fill":{
                              "fillType":"linearGradient",
                              "colors":[{
                                  "color":0xFFFFFFFF},
{
                                  "color":0xFFFFFFFF},
{
                                  "color":0xFFDDEFC4},
{
                                  "color":0xFFFFFFFF},
{
                                  "color":0xFFFFFFFF},
{
                                  "color":0xFF6FBE00},
{
                                  "color":0xFF6FBE00}]}}},
                        "location":{
                          "x":299,
                          "y":0},
                        "size":{
                          "width":90,
                          "height":35},
                        "borderWidth":"-1",
                        "cornerRadiusTopLeft":"2"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 链接",
                              "target":{
                                "targetType":"page",
                                "includeVariables":true},
                              "linkType":"current"},
{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 创业资讯",
                              "target":{
                                "targetType":"page",
                                "url":"创业资讯.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/首页/u212.png",
                    "mouseOver~":"images/首页/u212_mouseOver.png"}},
{
                  "id":"f2b624202b78454f812d9546efc3bac5",
                  "label":"",
                  "parentDynamicPanel":"2c620e3cb9d94931a9e0fbe47c6321ff",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"14px",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "fontSize":"14px",
                        "fontWeight":"bold",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "fill":{
                          "fillType":"linearGradient",
                          "colors":[{
                              "color":0xFFFFFFFF},
{
                              "color":0xFFFFFFFF},
{
                              "color":0xFFDDEFC4},
{
                              "color":0xFFFFFFFF},
{
                              "color":0xFFFFFFFF},
{
                              "color":0xFF6FBE00},
{
                              "color":0xFF6FBE00}]}}},
                    "location":{
                      "x":399,
                      "y":0},
                    "size":{
                      "width":90,
                      "height":35},
                    "borderWidth":"-1",
                    "cornerRadiusTopLeft":"2"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"286006fc86284b6597d29884d8db22aa",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2c620e3cb9d94931a9e0fbe47c6321ff",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontSize":"14px",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "fontSize":"14px",
                            "fontWeight":"bold",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF000000,
                              "opacity":1},
                            "fill":{
                              "fillType":"linearGradient",
                              "colors":[{
                                  "color":0xFFFFFFFF},
{
                                  "color":0xFFFFFFFF},
{
                                  "color":0xFFDDEFC4},
{
                                  "color":0xFFFFFFFF},
{
                                  "color":0xFFFFFFFF},
{
                                  "color":0xFF6FBE00},
{
                                  "color":0xFF6FBE00}]}}},
                        "location":{
                          "x":399,
                          "y":0},
                        "size":{
                          "width":90,
                          "height":35},
                        "borderWidth":"-1",
                        "cornerRadiusTopLeft":"2"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 新闻展示",
                              "target":{
                                "targetType":"page",
                                "url":"新闻展示.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/首页/u212.png",
                    "mouseOver~":"images/首页/u212_mouseOver.png"}},
{
                  "id":"ca8efab7afac4654a7d0efdc92f4352b",
                  "label":"",
                  "parentDynamicPanel":"2c620e3cb9d94931a9e0fbe47c6321ff",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"14px",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "fontSize":"14px",
                        "fontWeight":"bold",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "fill":{
                          "fillType":"linearGradient",
                          "colors":[{
                              "color":0xFFFFFFFF},
{
                              "color":0xFFFFFFFF},
{
                              "color":0xFFDDEFC4},
{
                              "color":0xFFFFFFFF},
{
                              "color":0xFFFFFFFF},
{
                              "color":0xFF6FBE00},
{
                              "color":0xFF6FBE00}]}}},
                    "location":{
                      "x":498,
                      "y":0},
                    "size":{
                      "width":90,
                      "height":35},
                    "borderWidth":"-1",
                    "cornerRadiusTopLeft":"2"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e5ae35e287bd4ac695293241959bc635",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2c620e3cb9d94931a9e0fbe47c6321ff",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontSize":"14px",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "fontSize":"14px",
                            "fontWeight":"bold",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF000000,
                              "opacity":1},
                            "fill":{
                              "fillType":"linearGradient",
                              "colors":[{
                                  "color":0xFFFFFFFF},
{
                                  "color":0xFFFFFFFF},
{
                                  "color":0xFFDDEFC4},
{
                                  "color":0xFFFFFFFF},
{
                                  "color":0xFFFFFFFF},
{
                                  "color":0xFF6FBE00},
{
                                  "color":0xFF6FBE00}]}}},
                        "location":{
                          "x":498,
                          "y":0},
                        "size":{
                          "width":90,
                          "height":35},
                        "borderWidth":"-1",
                        "cornerRadiusTopLeft":"2"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示/隐藏部件",
                              "objectsToFades":[]},
{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 KAB课程",
                              "target":{
                                "targetType":"page",
                                "url":"kab课程.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/首页/u212.png",
                    "mouseOver~":"images/首页/u212_mouseOver.png"}},
{
                  "id":"65b7036b12374c49821ac3e088868648",
                  "label":"",
                  "parentDynamicPanel":"2c620e3cb9d94931a9e0fbe47c6321ff",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"14px",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "fontSize":"14px",
                        "fontWeight":"bold",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "fill":{
                          "fillType":"linearGradient",
                          "colors":[{
                              "color":0xFFFFFFFF},
{
                              "color":0xFFFFFFFF},
{
                              "color":0xFFDDEFC4},
{
                              "color":0xFFFFFFFF},
{
                              "color":0xFFFFFFFF},
{
                              "color":0xFF6FBE00},
{
                              "color":0xFF6FBE00}]}}},
                    "location":{
                      "x":598,
                      "y":0},
                    "size":{
                      "width":90,
                      "height":35},
                    "borderWidth":"-1",
                    "cornerRadiusTopLeft":"2"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8470e2466f7847c2947eab7d4deaf3b4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2c620e3cb9d94931a9e0fbe47c6321ff",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontSize":"14px",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "fontSize":"14px",
                            "fontWeight":"bold",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF000000,
                              "opacity":1},
                            "fill":{
                              "fillType":"linearGradient",
                              "colors":[{
                                  "color":0xFFFFFFFF},
{
                                  "color":0xFFFFFFFF},
{
                                  "color":0xFFDDEFC4},
{
                                  "color":0xFFFFFFFF},
{
                                  "color":0xFFFFFFFF},
{
                                  "color":0xFF6FBE00},
{
                                  "color":0xFF6FBE00}]}}},
                        "location":{
                          "x":598,
                          "y":0},
                        "size":{
                          "width":90,
                          "height":35},
                        "borderWidth":"-1",
                        "cornerRadiusTopLeft":"2"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 创建班级",
                              "target":{
                                "targetType":"page",
                                "url":"创建班级.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/首页/u212.png",
                    "mouseOver~":"images/首页/u212_mouseOver.png"}},
{
                  "id":"71b405f3061742a388f8460f21e6316a",
                  "label":"",
                  "parentDynamicPanel":"2c620e3cb9d94931a9e0fbe47c6321ff",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":26},
                    "size":{
                      "width":700,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/首页/u224_line.png"}},
{
                  "id":"be1b8988310c4e28974825e33096893f",
                  "label":"",
                  "parentDynamicPanel":"2c620e3cb9d94931a9e0fbe47c6321ff",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"14px",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "fontSize":"14px",
                        "fontWeight":"bold",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "fill":{
                          "fillType":"linearGradient",
                          "colors":[{
                              "color":0xFFFFFFFF},
{
                              "color":0xFFFFFFFF},
{
                              "color":0xFFDDEFC4},
{
                              "color":0xFFFFFFFF},
{
                              "color":0xFFFFFFFF},
{
                              "color":0xFF6FBE00},
{
                              "color":0xFF6FBE00}]}}},
                    "fill":{
                      "fillType":"linearGradient",
                      "colors":[{
                          "color":0xFFFFFFFF},
{
                          "color":0xFFFFFFFF},
{
                          "color":0xFF6FBE00},
{
                          "color":0xFF6FBE00}]},
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":90,
                      "height":35},
                    "borderWidth":"-1",
                    "cornerRadiusTopLeft":"2"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d0769c3898384b8082c49ef58a46b37b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2c620e3cb9d94931a9e0fbe47c6321ff",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontSize":"14px",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "fontSize":"14px",
                            "fontWeight":"bold",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF000000,
                              "opacity":1},
                            "fill":{
                              "fillType":"linearGradient",
                              "colors":[{
                                  "color":0xFFFFFFFF},
{
                                  "color":0xFFFFFFFF},
{
                                  "color":0xFFDDEFC4},
{
                                  "color":0xFFFFFFFF},
{
                                  "color":0xFFFFFFFF},
{
                                  "color":0xFF6FBE00},
{
                                  "color":0xFF6FBE00}]}}},
                        "fill":{
                          "fillType":"linearGradient",
                          "colors":[{
                              "color":0xFFFFFFFF},
{
                              "color":0xFFFFFFFF},
{
                              "color":0xFF6FBE00},
{
                              "color":0xFF6FBE00}]},
                        "location":{
                          "x":100,
                          "y":0},
                        "size":{
                          "width":90,
                          "height":35},
                        "borderWidth":"-1",
                        "cornerRadiusTopLeft":"2"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u225.png",
                    "mouseOver~":"images/首页/u212_mouseOver.png"}}]}]},
{
          "id":"d699a18c8444424cbb8a6d64feb3f476",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF5E5E5E,
              "opacity":1},
            "location":{
              "x":566.5,
              "y":190},
            "size":{
              "width":68,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"384d6f3d81ff43b8b262e30d4836feb7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF5E5E5E,
                  "opacity":1},
                "location":{
                  "x":566.5,
                  "y":190},
                "size":{
                  "width":68,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e74e0e04a2944418893a3aeca21d8534",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":114,
              "y":213},
            "size":{
              "width":987,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/kab概况/u49_line.png"}},
{
          "id":"dd26401d39214257b7ca832c2bc41e31",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":1709}},
          "adaptiveStyles":{
},
          "masterId":"034e31733593431b98870f4edc72282d"}]}},
  "masters":{
    "034e31733593431b98870f4edc72282d":{
      "packageId":"034e31733593431b98870f4edc72282d",
      "type":"Axure:Master",
      "name":"底部版权",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"9a9f5c774c684cc4a9d6c03ef9dadf10",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "size":{
                "width":1001,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFBCBCBC}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/首页/u228_line.png"}},
{
            "id":"c3007cf040264ffc9d39990f7013110a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":330,
                "y":48},
              "size":{
                "width":181,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1c4621b95ceb4f86b0fdc69452cd957d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":330,
                    "y":48},
                  "size":{
                    "width":181,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"967cbac02d134f8f9da4fc620a93c521",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":272,
                "y":15},
              "size":{
                "width":46,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"14c0172691ee4563b55ddaf2db6595a5",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":272,
                    "y":15},
                  "size":{
                    "width":46,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 首页",
                        "target":{
                          "targetType":"page",
                          "url":"首页.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"23326f30dc93476b9e2fe4260520a628",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":332,
                "y":15},
              "size":{
                "width":80,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"29db2cd2137540059193cf0dcd3fca0f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":332,
                    "y":15},
                  "size":{
                    "width":80,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 底部单页",
                        "target":{
                          "targetType":"page",
                          "url":"底部单页.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"bda92ae43e734a899ab158f1b89dfe86",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":428,
                "y":15},
              "size":{
                "width":68,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d167430e74674c2f8aab552672946c5a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":428,
                    "y":15},
                  "size":{
                    "width":68,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 版权声明",
                        "target":{
                          "targetType":"page",
                          "url":"版权声明.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"af72b5bec7584c05be709045f54c5fe3",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":518,
                "y":15},
              "size":{
                "width":68,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"798e31d3880446c7a97bc7461e00e77a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":518,
                    "y":15},
                  "size":{
                    "width":68,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 人才招聘",
                        "target":{
                          "targetType":"page",
                          "url":"人才招聘.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"2e8f1d145ab8429d91eaf4c516fc9c4f",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":612,
                "y":15},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6ba9e1b5310b428f857d810b034018bb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":612,
                    "y":15},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 联系我们",
                        "target":{
                          "targetType":"page",
                          "url":"联系我们.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "5c5da3600744457cba2057e3e47d5b09":{
      "scriptId":"u0"},
    "7cc2a170b35d44328416c0b49694cd71":{
      "scriptId":"u1"},
    "31f1332b2f7043b7b108b34d0ab9bfac":{
      "scriptId":"u2"},
    "d613856cb8d940f89de33b43f7bc2995":{
      "scriptId":"u3"},
    "50398d9608dd4ad988225c5dc68bd4ed":{
      "scriptId":"u4"},
    "4a04ddf1344741f0ad337c0c5ba58cd7":{
      "scriptId":"u5"},
    "f6a2e9672d69406e9d14b6254a785fe2":{
      "scriptId":"u6"},
    "cdb2244c058d4be5a1fe473e5880e175":{
      "scriptId":"u7"},
    "42e0cb3be8134f34b6d8e24734170e9a":{
      "scriptId":"u8"},
    "9af6ade80e554ee59d483af129db2c1f":{
      "scriptId":"u9"},
    "f62a79aa0c9444b0976f6e141f8f439d":{
      "scriptId":"u10"},
    "c1ea634281284383ad7863a884d79748":{
      "scriptId":"u11"},
    "379b8b249acf462bb81a164b86d747e4":{
      "scriptId":"u12"},
    "ae9a397774e34fe886cb259af0ffe068":{
      "scriptId":"u13"},
    "07b0c0c8c6d64ac89f655ec0e5c70180":{
      "scriptId":"u14"},
    "19dfff27405a46a8bdef68332687d173":{
      "scriptId":"u15"},
    "304027be4b814c72bdbb5a6ee35451ad":{
      "scriptId":"u16"},
    "dd8aa8d0079447e9b10885f431d14967":{
      "scriptId":"u17"},
    "6a1a5b4ecc6f404ea65a6d6bc483862d":{
      "scriptId":"u18"},
    "2b30d25d28a2460facd37fde099bf24c":{
      "scriptId":"u19"},
    "00a9129cf91344a8be921bf3ad5e19d7":{
      "scriptId":"u20"},
    "d0964b65b70541cb8a9838d8fe66dfa1":{
      "scriptId":"u21"},
    "98ea43d715f948a6b98208e3efd377c9":{
      "scriptId":"u22"},
    "06636bc80d06428fb67c25ee03095def":{
      "scriptId":"u23"},
    "567be5e5acab479789326f3d73860ce3":{
      "scriptId":"u24"},
    "bcaa006b669940bda5c1a9bd6f9c4513":{
      "scriptId":"u25"},
    "b2163907c75d42b8807c42d96166ab10":{
      "scriptId":"u26"},
    "f877ce70787d44fa893c7a6fc5d0ed5f":{
      "scriptId":"u27"},
    "be75d034ba34429d8eba06c0ec4142f1":{
      "scriptId":"u28"},
    "bec4e2eb08da47289bb086a45f34ef41":{
      "scriptId":"u29"},
    "3e3bf33e83c54559be1f0a84336ebf3c":{
      "scriptId":"u30"},
    "2c620e3cb9d94931a9e0fbe47c6321ff":{
      "scriptId":"u31"},
    "0f26648c1c0b4099aae426c6e7694d41":{
      "scriptId":"u32"},
    "0ad43b672c544ac8b01d8bb4eac3e725":{
      "scriptId":"u33"},
    "2636471d7bd643b9bfaa809dbb2b74d3":{
      "scriptId":"u34"},
    "4592b197980a407294cadca57b17873c":{
      "scriptId":"u35"},
    "f518f1e080a2467f86c02f1db22c2790":{
      "scriptId":"u36"},
    "bb5db80a05544bcf90135b1af49bc895":{
      "scriptId":"u37"},
    "f2b624202b78454f812d9546efc3bac5":{
      "scriptId":"u38"},
    "286006fc86284b6597d29884d8db22aa":{
      "scriptId":"u39"},
    "ca8efab7afac4654a7d0efdc92f4352b":{
      "scriptId":"u40"},
    "e5ae35e287bd4ac695293241959bc635":{
      "scriptId":"u41"},
    "65b7036b12374c49821ac3e088868648":{
      "scriptId":"u42"},
    "8470e2466f7847c2947eab7d4deaf3b4":{
      "scriptId":"u43"},
    "71b405f3061742a388f8460f21e6316a":{
      "scriptId":"u44"},
    "be1b8988310c4e28974825e33096893f":{
      "scriptId":"u45"},
    "d0769c3898384b8082c49ef58a46b37b":{
      "scriptId":"u46"},
    "d699a18c8444424cbb8a6d64feb3f476":{
      "scriptId":"u47"},
    "384d6f3d81ff43b8b262e30d4836feb7":{
      "scriptId":"u48"},
    "e74e0e04a2944418893a3aeca21d8534":{
      "scriptId":"u49"},
    "dd26401d39214257b7ca832c2bc41e31":{
      "scriptId":"u50",
      "9a9f5c774c684cc4a9d6c03ef9dadf10":{
        "scriptId":"u51"},
      "c3007cf040264ffc9d39990f7013110a":{
        "scriptId":"u52"},
      "1c4621b95ceb4f86b0fdc69452cd957d":{
        "scriptId":"u53"},
      "967cbac02d134f8f9da4fc620a93c521":{
        "scriptId":"u54"},
      "14c0172691ee4563b55ddaf2db6595a5":{
        "scriptId":"u55"},
      "23326f30dc93476b9e2fe4260520a628":{
        "scriptId":"u56"},
      "29db2cd2137540059193cf0dcd3fca0f":{
        "scriptId":"u57"},
      "bda92ae43e734a899ab158f1b89dfe86":{
        "scriptId":"u58"},
      "d167430e74674c2f8aab552672946c5a":{
        "scriptId":"u59"},
      "af72b5bec7584c05be709045f54c5fe3":{
        "scriptId":"u60"},
      "798e31d3880446c7a97bc7461e00e77a":{
        "scriptId":"u61"},
      "2e8f1d145ab8429d91eaf4c516fc9c4f":{
        "scriptId":"u62"},
      "6ba9e1b5310b428f857d810b034018bb":{
        "scriptId":"u63"}}}});