$axure.loadCurrentPage({
  "url":"修改新闻.html",
  "generationDate":new Date(1383013849428.13),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"86852efb3dcd49fd8ccede6403da36b8",
    "type":"Axure:Page",
    "name":"修改新闻",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c63161999b5645d78fed7f69ad047629",
          "label":"导航",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":50},
            "size":{
              "width":716,
              "height":129}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"de753135df67476b90bdca38092dd9a2",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"2b5f7d9efd64493d98bb3c60612fe148",
                  "label":"",
                  "parentDynamicPanel":"c63161999b5645d78fed7f69ad047629",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":90,
                      "y":7},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"43bbee52937642eb875d4ef407d55266",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c63161999b5645d78fed7f69ad047629",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":90,
                          "y":7},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"7189ebbcd54b41f195a5bac00e25572e",
                  "label":"",
                  "parentDynamicPanel":"c63161999b5645d78fed7f69ad047629",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":300,
                      "y":7},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"03ee258b328649c0a8a550fef39a44f8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c63161999b5645d78fed7f69ad047629",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":300,
                          "y":7},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"bcb199e33cb141bc93121c1eb877a646",
                  "label":"",
                  "parentDynamicPanel":"c63161999b5645d78fed7f69ad047629",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":407,
                      "y":7},
                    "size":{
                      "width":79,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bc57b3b5486e4eaf97015e089bb01ea9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c63161999b5645d78fed7f69ad047629",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":407,
                          "y":7},
                        "size":{
                          "width":79,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c9899da3dd5344289fbf416f107603b9",
                  "label":"",
                  "parentDynamicPanel":"c63161999b5645d78fed7f69ad047629",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":542,
                      "y":7},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"96d725b69a384856b35bd697441d18f4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c63161999b5645d78fed7f69ad047629",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":542,
                          "y":7},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"a48fee1d89e24034975231672866fbc8",
                  "label":"",
                  "parentDynamicPanel":"c63161999b5645d78fed7f69ad047629",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":637,
                      "y":7},
                    "size":{
                      "width":79,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3a0ca5b3d7944f2d92efca1ca7607110",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c63161999b5645d78fed7f69ad047629",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":637,
                          "y":7},
                        "size":{
                          "width":79,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"61612550e0c34fe09c9b766faa77877e",
                  "label":"",
                  "parentDynamicPanel":"c63161999b5645d78fed7f69ad047629",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":22},
                    "size":{
                      "width":1000,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/修改密码_1/u21_line.png"}},
{
                  "id":"d20e6dd6cb924593b327e9c126c9161d",
                  "label":"",
                  "parentDynamicPanel":"c63161999b5645d78fed7f69ad047629",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF5E5E5E,
                      "opacity":1},
                    "location":{
                      "x":68,
                      "y":1},
                    "size":{
                      "width":97,
                      "height":27},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a7af75d48dee44b88dd65572bf4e8469",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c63161999b5645d78fed7f69ad047629",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF5E5E5E,
                          "opacity":1},
                        "location":{
                          "x":68,
                          "y":1},
                        "size":{
                          "width":97,
                          "height":27},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onMouseOver":{
                      "description":"OnMouseOver",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 ",
                              "objectsToFades":[]}]}]},
                    "onMouseOut":{
                      "description":"OnMouseOut",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 ",
                              "objectsToFades":[]}]}]}},
                  "images":{
                    "normal~":"images/新闻管理/u12.png"}},
{
                  "id":"e2112daade88475d9229c9dcad689e69",
                  "label":"",
                  "parentDynamicPanel":"c63161999b5645d78fed7f69ad047629",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "location":{
                      "x":165,
                      "y":7},
                    "size":{
                      "width":115,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"837e93c1460b4501a4642dbc5c97eadd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c63161999b5645d78fed7f69ad047629",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "location":{
                          "x":165,
                          "y":7},
                        "size":{
                          "width":115,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"5b3f67aa41fc453282c89e29aac627e5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":170,
              "height":51}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2da06ef0647a4b2daa3968bd1688cd4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":170,
                  "height":51}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改密码_1/u0.jpg"}},
{
          "id":"8ab344f052a447ca8b6d664ab5836d4e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":105},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6719ab97e9e4e2aa6a43b940d9761cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":48,
                  "y":105},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0e290147f1e246b5a57cefa3587af7a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":33,
              "y":101},
            "size":{
              "width":86,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4cf499c9d0b42dd8d40e691f994f2d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":33,
                  "y":101},
                "size":{
                  "width":86,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 新闻管理",
                      "target":{
                        "targetType":"page",
                        "url":"新闻管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7b58b8eadaf24de696ce552b59aa5e8c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":132,
              "y":101},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f0bd7770dcd41419284bea32b8da96a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":132,
                  "y":101},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"161f3dd05bbf4585bf33ed5e6d718ad4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":598,
              "y":4},
            "size":{
              "width":148,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f4d698331784187a139c59941887713",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":598,
                  "y":4},
                "size":{
                  "width":148,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"930efe4eccfe49208529d13390402c9c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":903,
              "y":4},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0462534cdd7b453f8a271b8f3b6a53b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":903,
                  "y":4},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 后台登录",
                      "target":{
                        "targetType":"page",
                        "url":"后台登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3c033a35fc7141ddbf384ba9ea142654",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":828,
              "y":4},
            "size":{
              "width":88,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46003fc08b1544abbdf6ef4fe26d938b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":828,
                  "y":4},
                "size":{
                  "width":88,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 修改密码",
                      "target":{
                        "targetType":"page",
                        "url":"修改密码_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"89997067ac214dd98840f4d9c7e5bbf2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":756,
              "y":4},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b77ce3ae269b4e40a515b3156c6394c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":756,
                  "y":4},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ba3d13f4db684e9a92011a9b36977c49",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":79,
              "y":149},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"899484ee7f7c40438b30709f9cb6b93e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":79,
                  "y":149},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"400b3392270b40a49b5a00b99fcce5d9",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":117},
            "size":{
              "width":946,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF949494}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/修改密码_1/u24_line.png"}},
{
          "id":"f7084a4f24c34c6692e591ce7c4315b3",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":143,
              "y":145},
            "size":{
              "width":477,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"6bcf379468954f95afc82ea70252a81b",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":143,
              "y":340},
            "size":{
              "width":477,
              "height":210}},
          "adaptiveStyles":{
}},
{
          "id":"588e864ce5424d3d80024b0eeee58ff0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":79,
              "y":320},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc5cb8f2840f4edcbcc842b525226e11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":79,
                  "y":320},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d83a7b14646045ce8eb5975dac24f6df",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":53,
              "y":273},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e055f3557ae4fa98a627521c4087971",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":53,
                  "y":273},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"061ecbb88ecf448392e1b9ad4f134c40",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":143,
              "y":315},
            "size":{
              "width":361,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e4595d0c31449e99da185e472a83b75",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":143,
                  "y":315},
                "size":{
                  "width":361,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加新闻/u41.png"}},
{
          "id":"114892aef626420794c53c19afc5f5e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":72,
              "y":234},
            "size":{
              "width":58,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb3513907eee4d8ca2c89f8d07c9756f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":72,
                  "y":234},
                "size":{
                  "width":58,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6e2d719bcd914d3798fac59aa4fa25e2",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":143,
              "y":190},
            "size":{
              "width":190,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"591d176f89884616867af6bcda42b4c6",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":143,
              "y":234},
            "size":{
              "width":187,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"0c112503f3564e69a94a22b31fcd5a3c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF87DB01}}},
            "fill":{
              "fillType":"solid",
              "color":0xFF6AB30C},
            "location":{
              "x":143,
              "y":624},
            "size":{
              "width":81,
              "height":26},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67e016094f6245f99fd2eaf7b0bd7dda",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF87DB01}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF6AB30C},
                "location":{
                  "x":143,
                  "y":624},
                "size":{
                  "width":81,
                  "height":26},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 alert",
                      "objectsToFades":[{
                          "objectPath":["5aebf7c4f1bd4d2c8377d8828869f92b"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/修改个人资料/u102.png",
            "mouseOver~":"images/修改个人资料/u102_mouseOver.png"}},
{
          "id":"ab640b98052344829e5d6dd97db99ec4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF87DB01}}},
            "fill":{
              "fillType":"solid",
              "color":0xFF6AB30C},
            "location":{
              "x":262,
              "y":624},
            "size":{
              "width":81,
              "height":26},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f9abf5ccbec4c9ca5ba93a853e85aa4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF87DB01}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF6AB30C},
                "location":{
                  "x":262,
                  "y":624},
                "size":{
                  "width":81,
                  "height":26},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 新闻管理",
                      "target":{
                        "targetType":"page",
                        "url":"新闻管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/修改个人资料/u102.png",
            "mouseOver~":"images/修改个人资料/u102_mouseOver.png"}},
{
          "id":"5aebf7c4f1bd4d2c8377d8828869f92b",
          "label":"alert",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":380,
              "y":248},
            "size":{
              "width":320,
              "height":190},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"8cc036982bb042978f7a7141c3f89185",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"19c02f85460e4ba5a4beccb117e12c6c",
                  "label":"",
                  "parentDynamicPanel":"5aebf7c4f1bd4d2c8377d8828869f92b",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":280,
                      "height":160}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cb68b3c761b0472586ac1c1ad6189ded",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5aebf7c4f1bd4d2c8377d8828869f92b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":280,
                          "height":160}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/修改密码_1/u44.png"}},
{
                  "id":"9689e55afd4245d89c76c9b107b638bc",
                  "label":"",
                  "parentDynamicPanel":"5aebf7c4f1bd4d2c8377d8828869f92b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "location":{
                      "x":42,
                      "y":9},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d863393cbce74688b49d8088a03bc6cc",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5aebf7c4f1bd4d2c8377d8828869f92b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontWeight":"700",
                        "location":{
                          "x":42,
                          "y":9},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"5f0402b26dd6490fb96c2a128a1222ee",
                  "label":"",
                  "parentDynamicPanel":"5aebf7c4f1bd4d2c8377d8828869f92b",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":26},
                    "size":{
                      "width":280,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/修改密码_1/u48_line.png"}},
{
                  "id":"7f64c210d686424798fb17fed56d17cb",
                  "label":"",
                  "parentDynamicPanel":"5aebf7c4f1bd4d2c8377d8828869f92b",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":101,
                      "y":120},
                    "size":{
                      "width":78,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ae2dff72c31a431693f7c1bb00bcaf01",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5aebf7c4f1bd4d2c8377d8828869f92b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4},
                        "location":{
                          "x":101,
                          "y":120},
                        "size":{
                          "width":78,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 alert",
                              "objectsToFades":[{
                                  "objectPath":["5aebf7c4f1bd4d2c8377d8828869f92b"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]},
{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 新闻管理",
                              "target":{
                                "targetType":"page",
                                "url":"新闻管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/修改密码_1/u49.png"}},
{
                  "id":"755d48bcca1b49fbb80a5bad1030554a",
                  "label":"",
                  "parentDynamicPanel":"5aebf7c4f1bd4d2c8377d8828869f92b",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":16,
                      "y":9},
                    "size":{
                      "width":16,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9ed3ddebe1684f888a7cd753c13750f6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5aebf7c4f1bd4d2c8377d8828869f92b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "location":{
                          "x":16,
                          "y":9},
                        "size":{
                          "width":16,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/修改密码_1/u51.png"}},
{
                  "id":"0a53687b14cb4baf881c7020dbc537c5",
                  "label":"",
                  "parentDynamicPanel":"5aebf7c4f1bd4d2c8377d8828869f92b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":126,
                      "y":72},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c3f53a7c9bf44c4e9b111d358158cb38",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5aebf7c4f1bd4d2c8377d8828869f92b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":126,
                          "y":72},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"444d648535ba4fe9bf4c7d6b777d4ad0",
                  "label":"",
                  "parentDynamicPanel":"5aebf7c4f1bd4d2c8377d8828869f92b",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":100,
                      "y":72},
                    "size":{
                      "width":16,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"af4969fe8a0943718c3b01cb90886794",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5aebf7c4f1bd4d2c8377d8828869f92b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "location":{
                          "x":100,
                          "y":72},
                        "size":{
                          "width":16,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/修改密码_1/u55.png"}}]}]},
{
          "id":"553755d8b24a4d82b2e07f05847cc8dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":81,
              "y":190},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bdc50692c7d54fc2b2abcae4d95d2901",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":81,
                  "y":190},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7a05ffdd69fb48e987c9c1ad393b5d77",
          "label":"1",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":138,
              "y":276},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b1905b7c6ed483896c5a3ab36b0c6af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":138,
                  "y":276},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 1 等于 &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["7a05ffdd69fb48e987c9c1ad393b5d77"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}},
{
                      "action":"setFunction",
                      "description":"设置 被选中的 2 等于 &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["f78e7b4cb9bb4463bf46da21f4440418"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}}},
{
          "id":"f78e7b4cb9bb4463bf46da21f4440418",
          "label":"2",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":248,
              "y":276},
            "size":{
              "width":47,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa02b122d48745f08e870ec003b0e23b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":248,
                  "y":276},
                "size":{
                  "width":47,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 2 等于 &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["f78e7b4cb9bb4463bf46da21f4440418"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}},
{
                      "action":"setFunction",
                      "description":"设置 被选中的 1 等于 &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["7a05ffdd69fb48e987c9c1ad393b5d77"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}}}]}},
  "masters":{
},
  "objectPaths":{
    "c63161999b5645d78fed7f69ad047629":{
      "scriptId":"u0"},
    "2b5f7d9efd64493d98bb3c60612fe148":{
      "scriptId":"u1"},
    "43bbee52937642eb875d4ef407d55266":{
      "scriptId":"u2"},
    "7189ebbcd54b41f195a5bac00e25572e":{
      "scriptId":"u3"},
    "03ee258b328649c0a8a550fef39a44f8":{
      "scriptId":"u4"},
    "bcb199e33cb141bc93121c1eb877a646":{
      "scriptId":"u5"},
    "bc57b3b5486e4eaf97015e089bb01ea9":{
      "scriptId":"u6"},
    "c9899da3dd5344289fbf416f107603b9":{
      "scriptId":"u7"},
    "96d725b69a384856b35bd697441d18f4":{
      "scriptId":"u8"},
    "a48fee1d89e24034975231672866fbc8":{
      "scriptId":"u9"},
    "3a0ca5b3d7944f2d92efca1ca7607110":{
      "scriptId":"u10"},
    "61612550e0c34fe09c9b766faa77877e":{
      "scriptId":"u11"},
    "d20e6dd6cb924593b327e9c126c9161d":{
      "scriptId":"u12"},
    "a7af75d48dee44b88dd65572bf4e8469":{
      "scriptId":"u13"},
    "e2112daade88475d9229c9dcad689e69":{
      "scriptId":"u14"},
    "837e93c1460b4501a4642dbc5c97eadd":{
      "scriptId":"u15"},
    "5b3f67aa41fc453282c89e29aac627e5":{
      "scriptId":"u16"},
    "2da06ef0647a4b2daa3968bd1688cd4d":{
      "scriptId":"u17"},
    "8ab344f052a447ca8b6d664ab5836d4e":{
      "scriptId":"u18"},
    "a6719ab97e9e4e2aa6a43b940d9761cd":{
      "scriptId":"u19"},
    "0e290147f1e246b5a57cefa3587af7a3":{
      "scriptId":"u20"},
    "b4cf499c9d0b42dd8d40e691f994f2d0":{
      "scriptId":"u21"},
    "7b58b8eadaf24de696ce552b59aa5e8c":{
      "scriptId":"u22"},
    "8f0bd7770dcd41419284bea32b8da96a":{
      "scriptId":"u23"},
    "161f3dd05bbf4585bf33ed5e6d718ad4":{
      "scriptId":"u24"},
    "8f4d698331784187a139c59941887713":{
      "scriptId":"u25"},
    "930efe4eccfe49208529d13390402c9c":{
      "scriptId":"u26"},
    "0462534cdd7b453f8a271b8f3b6a53b8":{
      "scriptId":"u27"},
    "3c033a35fc7141ddbf384ba9ea142654":{
      "scriptId":"u28"},
    "46003fc08b1544abbdf6ef4fe26d938b":{
      "scriptId":"u29"},
    "89997067ac214dd98840f4d9c7e5bbf2":{
      "scriptId":"u30"},
    "b77ce3ae269b4e40a515b3156c6394c0":{
      "scriptId":"u31"},
    "ba3d13f4db684e9a92011a9b36977c49":{
      "scriptId":"u32"},
    "899484ee7f7c40438b30709f9cb6b93e":{
      "scriptId":"u33"},
    "400b3392270b40a49b5a00b99fcce5d9":{
      "scriptId":"u34"},
    "f7084a4f24c34c6692e591ce7c4315b3":{
      "scriptId":"u35"},
    "6bcf379468954f95afc82ea70252a81b":{
      "scriptId":"u36"},
    "588e864ce5424d3d80024b0eeee58ff0":{
      "scriptId":"u37"},
    "bc5cb8f2840f4edcbcc842b525226e11":{
      "scriptId":"u38"},
    "d83a7b14646045ce8eb5975dac24f6df":{
      "scriptId":"u39"},
    "3e055f3557ae4fa98a627521c4087971":{
      "scriptId":"u40"},
    "061ecbb88ecf448392e1b9ad4f134c40":{
      "scriptId":"u41"},
    "6e4595d0c31449e99da185e472a83b75":{
      "scriptId":"u42"},
    "114892aef626420794c53c19afc5f5e1":{
      "scriptId":"u43"},
    "cb3513907eee4d8ca2c89f8d07c9756f":{
      "scriptId":"u44"},
    "6e2d719bcd914d3798fac59aa4fa25e2":{
      "scriptId":"u45"},
    "591d176f89884616867af6bcda42b4c6":{
      "scriptId":"u46"},
    "0c112503f3564e69a94a22b31fcd5a3c":{
      "scriptId":"u47"},
    "67e016094f6245f99fd2eaf7b0bd7dda":{
      "scriptId":"u48"},
    "ab640b98052344829e5d6dd97db99ec4":{
      "scriptId":"u49"},
    "6f9abf5ccbec4c9ca5ba93a853e85aa4":{
      "scriptId":"u50"},
    "5aebf7c4f1bd4d2c8377d8828869f92b":{
      "scriptId":"u51"},
    "19c02f85460e4ba5a4beccb117e12c6c":{
      "scriptId":"u52"},
    "cb68b3c761b0472586ac1c1ad6189ded":{
      "scriptId":"u53"},
    "9689e55afd4245d89c76c9b107b638bc":{
      "scriptId":"u54"},
    "d863393cbce74688b49d8088a03bc6cc":{
      "scriptId":"u55"},
    "5f0402b26dd6490fb96c2a128a1222ee":{
      "scriptId":"u56"},
    "7f64c210d686424798fb17fed56d17cb":{
      "scriptId":"u57"},
    "ae2dff72c31a431693f7c1bb00bcaf01":{
      "scriptId":"u58"},
    "755d48bcca1b49fbb80a5bad1030554a":{
      "scriptId":"u59"},
    "9ed3ddebe1684f888a7cd753c13750f6":{
      "scriptId":"u60"},
    "0a53687b14cb4baf881c7020dbc537c5":{
      "scriptId":"u61"},
    "c3f53a7c9bf44c4e9b111d358158cb38":{
      "scriptId":"u62"},
    "444d648535ba4fe9bf4c7d6b777d4ad0":{
      "scriptId":"u63"},
    "af4969fe8a0943718c3b01cb90886794":{
      "scriptId":"u64"},
    "553755d8b24a4d82b2e07f05847cc8dd":{
      "scriptId":"u65"},
    "bdc50692c7d54fc2b2abcae4d95d2901":{
      "scriptId":"u66"},
    "7a05ffdd69fb48e987c9c1ad393b5d77":{
      "scriptId":"u67"},
    "2b1905b7c6ed483896c5a3ab36b0c6af":{
      "scriptId":"u68"},
    "f78e7b4cb9bb4463bf46da21f4440418":{
      "scriptId":"u69"},
    "fa02b122d48745f08e870ec003b0e23b":{
      "scriptId":"u70"}}});