$axure.loadCurrentPage({
  "url":"会员注册.html",
  "generationDate":new Date(1383013844456.85),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b8e49f938f954a23b251ba5e25109931",
    "type":"Axure:Page",
    "name":"会员注册",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b8ab8c9219cb4156b1ea92ebbe6b0b3c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":114,
              "y":6},
            "size":{
              "width":149,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ecfaf9fa772b425f851caa9cd6084c83",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":114,
                  "y":6},
                "size":{
                  "width":149,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5a5aa3cba7c845688cc65f72d1ea7a52",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":900,
              "y":6},
            "size":{
              "width":42,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7586dc9cbc942599e6a0f16450e2691",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":900,
                  "y":6},
                "size":{
                  "width":42,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a8e256db77cc4d25ae55be9a6a56a75d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":952,
              "y":6},
            "size":{
              "width":64,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1aea5a1e1d8e4411ad52388af9dfe4e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":952,
                  "y":6},
                "size":{
                  "width":64,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ec31ea5129dc42afb49cd93373abe8ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1028,
              "y":7},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24e0edecf87e41c9ba5ca9973585af53",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1028,
                  "y":7},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d23ebd796ae64879a44d6da92e47dbd2",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":21},
            "size":{
              "width":1200,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE0E0E0}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页/u10_line.png"}},
{
          "id":"78966748fff74461b0b0e030a10a873e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":26},
            "size":{
              "width":1200,
              "height":106},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF5C5D5F}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66418e1924ca4793b7a2707c51176065",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":26},
                "size":{
                  "width":1200,
                  "height":106},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF5C5D5F}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u11.jpg"}},
{
          "id":"8d11aaf1f82f4b9d9a034e7449744f8f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":170,
              "y":157},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46b51f53d14c4543b00a0349ee6080aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":170,
                  "y":157},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"957159f078be4b8e966c3dd615f0aae1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":188,
              "y":235},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d38440e24025445a963f1c99d8294a86",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":188,
                  "y":235},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c73427bd5b6c494e9189ace3ff196f4a",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":238,
              "y":227},
            "size":{
              "width":240,
              "height":33}},
          "adaptiveStyles":{
}},
{
          "id":"43e000e4566b4e63b294485d3b928960",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":201,
              "y":287},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18a5f1928bf44986bd739f8892ab34a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":201,
                  "y":287},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"729811c11bad4ea680fd7e76500bd7fc",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":238,
              "y":279},
            "size":{
              "width":240,
              "height":33}},
          "adaptiveStyles":{
}},
{
          "id":"539a0df73deb4ec28b15934563ac277d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":188,
              "y":451},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4db30313e1834bb5b6cf1fa3f709f345",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":188,
                  "y":451},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2f91103c270745d5a9d88db4f7f30344",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":238,
              "y":442},
            "size":{
              "width":111,
              "height":33}},
          "adaptiveStyles":{
}},
{
          "id":"df6389f03a6244cf81edcdba16753562",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":364,
              "y":446},
            "size":{
              "width":59,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e54360f01404cd6a5b0ba7497207066",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":364,
                  "y":446},
                "size":{
                  "width":59,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u32.jpg"}},
{
          "id":"07f115f6f59a4492b231c6eb0fb3ad3a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":99,
              "y":26},
            "size":{
              "width":276,
              "height":106}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f814677d33264cdd9443b8849b22e293",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":99,
                  "y":26},
                "size":{
                  "width":276,
                  "height":106}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ebc5a4dfce44410eb885226f1acc3d3d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF87DB01}}},
            "fill":{
              "fillType":"solid",
              "color":0xFF6AB30C},
            "location":{
              "x":238,
              "y":529},
            "size":{
              "width":240,
              "height":34},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dab2c064b0694a95ab7f05ad5277b6b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF87DB01}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF6AB30C},
                "location":{
                  "x":238,
                  "y":529},
                "size":{
                  "width":240,
                  "height":34},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 会员中心默认页",
                      "target":{
                        "targetType":"page",
                        "url":"会员中心默认页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/会员注册/u26.png",
            "mouseOver~":"images/会员注册/u26_mouseOver.png"}},
{
          "id":"90a303559b5f4a39882a81707ac768b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":175,
              "y":349},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f2eef53f5cc4cfd89e87e97a1b7496a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":175,
                  "y":349},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"020cfff5a9eb4034a83e84bcc00765f3",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":238,
              "y":341},
            "size":{
              "width":240,
              "height":33}},
          "adaptiveStyles":{
}},
{
          "id":"af261839e2aa4704b1f13a311454b0a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":740,
              "y":227},
            "size":{
              "width":228,
              "height":258},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF949494}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e53a43f7dd78402e810db75881243478",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":740,
                  "y":227},
                "size":{
                  "width":228,
                  "height":258},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u15.png"}},
{
          "id":"8d7fd2917d0043a68b3055f0cb9d23c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":782,
              "y":270},
            "size":{
              "width":144,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ae479ddebb14a0a8cc755ee13d6bff2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":782,
                  "y":270},
                "size":{
                  "width":144,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 会员登录",
                      "target":{
                        "targetType":"page",
                        "url":"会员登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4d99c83b55dd4a89a2dd6213b17383c4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":128,
              "y":147.5},
            "size":{
              "width":32,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34c20fa0751a4336b4dcc2bd3fe24680",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":128,
                  "y":147.5},
                "size":{
                  "width":32,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员注册/u35.png"}},
{
          "id":"4c48b6bb9095406a8da9460938057e4d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":452},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9339e4f231e84c13841705aabb7f3608",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":452},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f649ad0323bb405b80868cf888a04edd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":752,
              "y":328},
            "size":{
              "width":205,
              "height":141}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb7f353a051a4489a52ba3ed2c1c7d27",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":752,
                  "y":328},
                "size":{
                  "width":205,
                  "height":141}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员注册/u39.png"}},
{
          "id":"4694640371a34755a6a9b116aa20fc7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":188,
              "y":398},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54106909136446479fbea7391da95040",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":188,
                  "y":398},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6d2cdd92d0914c1d85d30ac28821a5ff",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":238,
              "y":390},
            "size":{
              "width":240,
              "height":33}},
          "adaptiveStyles":{
}},
{
          "id":"c312e5460667468e98a8a705d1af9e79",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":488,
              "y":236},
            "size":{
              "width":22,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6efbd1db9b93426e9db5c7d278c62900",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":488,
                  "y":236},
                "size":{
                  "width":22,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e1356cd820f7427c8c3d104f7dff38f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":488,
              "y":296},
            "size":{
              "width":22,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d5d52691cb34a1eb8f7a510187cd07a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":488,
                  "y":296},
                "size":{
                  "width":22,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b59f39325f8f4d0db8aec6665b8e069b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":488,
              "y":358},
            "size":{
              "width":22,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52a9aae42192461a81c214374de38b9f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":488,
                  "y":358},
                "size":{
                  "width":22,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1cc3b9fc9230419395020b14a2e900a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":488,
              "y":398},
            "size":{
              "width":22,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17271cf9ac5844c78ac889f62ea8e6a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":488,
                  "y":398},
                "size":{
                  "width":22,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"806bf00832d942cdb33c8de42169332e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":490,
              "y":452},
            "size":{
              "width":22,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"80fcd337170c46e9a6453c307100fd99",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":490,
                  "y":452},
                "size":{
                  "width":22,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"178fa0af6e41401bbc8aae4ea25059f1",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":650}},
          "adaptiveStyles":{
},
          "masterId":"034e31733593431b98870f4edc72282d"}]}},
  "masters":{
    "034e31733593431b98870f4edc72282d":{
      "packageId":"034e31733593431b98870f4edc72282d",
      "type":"Axure:Master",
      "name":"底部版权",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"9a9f5c774c684cc4a9d6c03ef9dadf10",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "size":{
                "width":1001,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFBCBCBC}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/首页/u228_line.png"}},
{
            "id":"c3007cf040264ffc9d39990f7013110a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":330,
                "y":48},
              "size":{
                "width":181,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1c4621b95ceb4f86b0fdc69452cd957d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":330,
                    "y":48},
                  "size":{
                    "width":181,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"967cbac02d134f8f9da4fc620a93c521",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":272,
                "y":15},
              "size":{
                "width":46,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"14c0172691ee4563b55ddaf2db6595a5",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":272,
                    "y":15},
                  "size":{
                    "width":46,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 首页",
                        "target":{
                          "targetType":"page",
                          "url":"首页.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"23326f30dc93476b9e2fe4260520a628",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":332,
                "y":15},
              "size":{
                "width":80,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"29db2cd2137540059193cf0dcd3fca0f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":332,
                    "y":15},
                  "size":{
                    "width":80,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 底部单页",
                        "target":{
                          "targetType":"page",
                          "url":"底部单页.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"bda92ae43e734a899ab158f1b89dfe86",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":428,
                "y":15},
              "size":{
                "width":68,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d167430e74674c2f8aab552672946c5a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":428,
                    "y":15},
                  "size":{
                    "width":68,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 版权声明",
                        "target":{
                          "targetType":"page",
                          "url":"版权声明.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"af72b5bec7584c05be709045f54c5fe3",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":518,
                "y":15},
              "size":{
                "width":68,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"798e31d3880446c7a97bc7461e00e77a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":518,
                    "y":15},
                  "size":{
                    "width":68,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 人才招聘",
                        "target":{
                          "targetType":"page",
                          "url":"人才招聘.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"2e8f1d145ab8429d91eaf4c516fc9c4f",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":612,
                "y":15},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6ba9e1b5310b428f857d810b034018bb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":612,
                    "y":15},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 联系我们",
                        "target":{
                          "targetType":"page",
                          "url":"联系我们.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "b8ab8c9219cb4156b1ea92ebbe6b0b3c":{
      "scriptId":"u0"},
    "ecfaf9fa772b425f851caa9cd6084c83":{
      "scriptId":"u1"},
    "5a5aa3cba7c845688cc65f72d1ea7a52":{
      "scriptId":"u2"},
    "b7586dc9cbc942599e6a0f16450e2691":{
      "scriptId":"u3"},
    "a8e256db77cc4d25ae55be9a6a56a75d":{
      "scriptId":"u4"},
    "1aea5a1e1d8e4411ad52388af9dfe4e5":{
      "scriptId":"u5"},
    "ec31ea5129dc42afb49cd93373abe8ca":{
      "scriptId":"u6"},
    "24e0edecf87e41c9ba5ca9973585af53":{
      "scriptId":"u7"},
    "d23ebd796ae64879a44d6da92e47dbd2":{
      "scriptId":"u8"},
    "78966748fff74461b0b0e030a10a873e":{
      "scriptId":"u9"},
    "66418e1924ca4793b7a2707c51176065":{
      "scriptId":"u10"},
    "8d11aaf1f82f4b9d9a034e7449744f8f":{
      "scriptId":"u11"},
    "46b51f53d14c4543b00a0349ee6080aa":{
      "scriptId":"u12"},
    "957159f078be4b8e966c3dd615f0aae1":{
      "scriptId":"u13"},
    "d38440e24025445a963f1c99d8294a86":{
      "scriptId":"u14"},
    "c73427bd5b6c494e9189ace3ff196f4a":{
      "scriptId":"u15"},
    "43e000e4566b4e63b294485d3b928960":{
      "scriptId":"u16"},
    "18a5f1928bf44986bd739f8892ab34a6":{
      "scriptId":"u17"},
    "729811c11bad4ea680fd7e76500bd7fc":{
      "scriptId":"u18"},
    "539a0df73deb4ec28b15934563ac277d":{
      "scriptId":"u19"},
    "4db30313e1834bb5b6cf1fa3f709f345":{
      "scriptId":"u20"},
    "2f91103c270745d5a9d88db4f7f30344":{
      "scriptId":"u21"},
    "df6389f03a6244cf81edcdba16753562":{
      "scriptId":"u22"},
    "4e54360f01404cd6a5b0ba7497207066":{
      "scriptId":"u23"},
    "07f115f6f59a4492b231c6eb0fb3ad3a":{
      "scriptId":"u24"},
    "f814677d33264cdd9443b8849b22e293":{
      "scriptId":"u25"},
    "ebc5a4dfce44410eb885226f1acc3d3d":{
      "scriptId":"u26"},
    "dab2c064b0694a95ab7f05ad5277b6b8":{
      "scriptId":"u27"},
    "90a303559b5f4a39882a81707ac768b4":{
      "scriptId":"u28"},
    "2f2eef53f5cc4cfd89e87e97a1b7496a":{
      "scriptId":"u29"},
    "020cfff5a9eb4034a83e84bcc00765f3":{
      "scriptId":"u30"},
    "af261839e2aa4704b1f13a311454b0a5":{
      "scriptId":"u31"},
    "e53a43f7dd78402e810db75881243478":{
      "scriptId":"u32"},
    "8d7fd2917d0043a68b3055f0cb9d23c7":{
      "scriptId":"u33"},
    "5ae479ddebb14a0a8cc755ee13d6bff2":{
      "scriptId":"u34"},
    "4d99c83b55dd4a89a2dd6213b17383c4":{
      "scriptId":"u35"},
    "34c20fa0751a4336b4dcc2bd3fe24680":{
      "scriptId":"u36"},
    "4c48b6bb9095406a8da9460938057e4d":{
      "scriptId":"u37"},
    "9339e4f231e84c13841705aabb7f3608":{
      "scriptId":"u38"},
    "f649ad0323bb405b80868cf888a04edd":{
      "scriptId":"u39"},
    "bb7f353a051a4489a52ba3ed2c1c7d27":{
      "scriptId":"u40"},
    "4694640371a34755a6a9b116aa20fc7f":{
      "scriptId":"u41"},
    "54106909136446479fbea7391da95040":{
      "scriptId":"u42"},
    "6d2cdd92d0914c1d85d30ac28821a5ff":{
      "scriptId":"u43"},
    "c312e5460667468e98a8a705d1af9e79":{
      "scriptId":"u44"},
    "6efbd1db9b93426e9db5c7d278c62900":{
      "scriptId":"u45"},
    "e1356cd820f7427c8c3d104f7dff38f6":{
      "scriptId":"u46"},
    "6d5d52691cb34a1eb8f7a510187cd07a":{
      "scriptId":"u47"},
    "b59f39325f8f4d0db8aec6665b8e069b":{
      "scriptId":"u48"},
    "52a9aae42192461a81c214374de38b9f":{
      "scriptId":"u49"},
    "1cc3b9fc9230419395020b14a2e900a2":{
      "scriptId":"u50"},
    "17271cf9ac5844c78ac889f62ea8e6a2":{
      "scriptId":"u51"},
    "806bf00832d942cdb33c8de42169332e":{
      "scriptId":"u52"},
    "80fcd337170c46e9a6453c307100fd99":{
      "scriptId":"u53"},
    "178fa0af6e41401bbc8aae4ea25059f1":{
      "scriptId":"u54",
      "9a9f5c774c684cc4a9d6c03ef9dadf10":{
        "scriptId":"u55"},
      "c3007cf040264ffc9d39990f7013110a":{
        "scriptId":"u56"},
      "1c4621b95ceb4f86b0fdc69452cd957d":{
        "scriptId":"u57"},
      "967cbac02d134f8f9da4fc620a93c521":{
        "scriptId":"u58"},
      "14c0172691ee4563b55ddaf2db6595a5":{
        "scriptId":"u59"},
      "23326f30dc93476b9e2fe4260520a628":{
        "scriptId":"u60"},
      "29db2cd2137540059193cf0dcd3fca0f":{
        "scriptId":"u61"},
      "bda92ae43e734a899ab158f1b89dfe86":{
        "scriptId":"u62"},
      "d167430e74674c2f8aab552672946c5a":{
        "scriptId":"u63"},
      "af72b5bec7584c05be709045f54c5fe3":{
        "scriptId":"u64"},
      "798e31d3880446c7a97bc7461e00e77a":{
        "scriptId":"u65"},
      "2e8f1d145ab8429d91eaf4c516fc9c4f":{
        "scriptId":"u66"},
      "6ba9e1b5310b428f857d810b034018bb":{
        "scriptId":"u67"}}}});