$axure.loadCurrentPage({
  "url":"找回密码.html",
  "generationDate":new Date(1383013848856.1),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e887907e5b4b4c9c8972fc2716f7ebf8",
    "type":"Axure:Page",
    "name":"找回密码",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c9bbe925f6b442e6a76bd9764d59769d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":114,
              "y":6},
            "size":{
              "width":149,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3798cd52d0cd47c6bc31dd5c5ff2f32c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":114,
                  "y":6},
                "size":{
                  "width":149,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2837f0b612da4387b498391ed6c3ff5d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":900,
              "y":6},
            "size":{
              "width":42,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7554e0242714452858510a796e682b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":900,
                  "y":6},
                "size":{
                  "width":42,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"502ccbbf249741d5be3b24c64562123e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":952,
              "y":6},
            "size":{
              "width":64,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2637438670d24202b5d223fa37acacd5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":952,
                  "y":6},
                "size":{
                  "width":64,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d50e21dedc6f41a1a716f521e47d0498",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1028,
              "y":7},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb7c8ae35af046ba850e19aea3c6b7c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1028,
                  "y":7},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"713bf7f06f364bd08372f5d75be79009",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":21},
            "size":{
              "width":1200,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE0E0E0}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页/u10_line.png"}},
{
          "id":"af9a65e305ab422c8901ce36972dd132",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":26},
            "size":{
              "width":1200,
              "height":106},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF5C5D5F}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2936f89ef924c73825aab5c43761701",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":26},
                "size":{
                  "width":1200,
                  "height":106},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF5C5D5F}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u11.jpg"}},
{
          "id":"c7c49dd2a2504839a7935401ef42731e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":114,
              "y":157},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16be86de37c34f45b2a7f6bbec63af40",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":114,
                  "y":157},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u19.png"}},
{
          "id":"8f955c8edec049f4976ba4731466441b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":140,
              "y":154},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1babf875d44c495c973f52bb8720d885",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":140,
                  "y":154},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4a15986020a049729ca1990b556fc984",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":99,
              "y":26},
            "size":{
              "width":276,
              "height":106}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f77d619c21a14c0194eff7a5e0da6271",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":99,
                  "y":26},
                "size":{
                  "width":276,
                  "height":106}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3c333f97a45843d7aa3299fdbb12a905",
          "label":"fin",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":230},
            "size":{
              "width":450,
              "height":110}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"b18a8377072f4030b9418f1470405bcc",
              "label":"step1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"ebb5c2c36dcf433cb1fc9e172abbbf5a",
                  "label":"",
                  "parentDynamicPanel":"3c333f97a45843d7aa3299fdbb12a905",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":1,
                      "y":85},
                    "size":{
                      "width":79,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e0a4a585e80e4a24aae4bb5888c2575a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3c333f97a45843d7aa3299fdbb12a905",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":1,
                          "y":85},
                        "size":{
                          "width":79,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"50451a0d32a548888eb480db88a3fd43",
                  "label":"",
                  "parentDynamicPanel":"3c333f97a45843d7aa3299fdbb12a905",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":84,
                      "y":77},
                    "size":{
                      "width":240,
                      "height":33}},
                  "adaptiveStyles":{
}},
{
                  "id":"3fc3b677b93f4971a74edce266465471",
                  "label":"",
                  "parentDynamicPanel":"3c333f97a45843d7aa3299fdbb12a905",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF87DB01}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF6AB30C},
                    "location":{
                      "x":337,
                      "y":76},
                    "size":{
                      "width":113,
                      "height":34},
                    "borderWidth":"-1",
                    "cornerRadiusTopLeft":"3"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c3f7aafdc28b485da70ca1274631540f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3c333f97a45843d7aa3299fdbb12a905",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontSize":"16px",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "fill":{
                              "fillType":"solid",
                              "color":0xFF87DB01}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF6AB30C},
                        "location":{
                          "x":337,
                          "y":76},
                        "size":{
                          "width":113,
                          "height":34},
                        "borderWidth":"-1",
                        "cornerRadiusTopLeft":"3"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 fin 到 step2",
                              "panelsToStates":[{
                                  "panelPath":["3c333f97a45843d7aa3299fdbb12a905"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/找回密码/u21.png",
                    "mouseOver~":"images/找回密码/u21_mouseOver.png"}}]},
{
              "id":"8a237c3beffa40429f0f169b70fe701d",
              "label":"step2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"40e88fe5b009479bb22e6e23ac4197fa",
                  "label":"",
                  "parentDynamicPanel":"3c333f97a45843d7aa3299fdbb12a905",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":48,
                      "y":85},
                    "size":{
                      "width":40,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6032233282fd4f45abc650f177ef1c12",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3c333f97a45843d7aa3299fdbb12a905",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":48,
                          "y":85},
                        "size":{
                          "width":40,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"729e9fe874554ecf8376894a3fbf89ca",
                  "label":"",
                  "parentDynamicPanel":"3c333f97a45843d7aa3299fdbb12a905",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":98,
                      "y":77},
                    "size":{
                      "width":240,
                      "height":33}},
                  "adaptiveStyles":{
}},
{
                  "id":"74b6ffb77f704e23b1ca941c6148429a",
                  "label":"",
                  "parentDynamicPanel":"3c333f97a45843d7aa3299fdbb12a905",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF87DB01}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF6AB30C},
                    "location":{
                      "x":98,
                      "y":146},
                    "size":{
                      "width":103,
                      "height":34},
                    "borderWidth":"-1",
                    "cornerRadiusTopLeft":"3"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4d01cd4045814301a770d0db9a77e0e4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3c333f97a45843d7aa3299fdbb12a905",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontSize":"16px",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "fill":{
                              "fillType":"solid",
                              "color":0xFF87DB01}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF6AB30C},
                        "location":{
                          "x":98,
                          "y":146},
                        "size":{
                          "width":103,
                          "height":34},
                        "borderWidth":"-1",
                        "cornerRadiusTopLeft":"3"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 alert-添加成功,<br>border",
                              "objectsToFades":[{
                                  "objectPath":["76a6b90667f34f87a307a3ace448907e"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["0090d287882a4deeb0b197098d79f781"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/找回密码/u26.png",
                    "mouseOver~":"images/找回密码/u26_mouseOver.png"}},
{
                  "id":"0fb0e631d3fb4ab6a84ef62b06092229",
                  "label":"",
                  "parentDynamicPanel":"3c333f97a45843d7aa3299fdbb12a905",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":21,
                      "y":34},
                    "size":{
                      "width":66,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8b5383e15bd345c4abc942b4c47bee4f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3c333f97a45843d7aa3299fdbb12a905",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":21,
                          "y":34},
                        "size":{
                          "width":66,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f5724766b3df40328a6526d2fd6d2bc9",
                  "label":"",
                  "parentDynamicPanel":"3c333f97a45843d7aa3299fdbb12a905",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":124,
                      "y":34},
                    "size":{
                      "width":131,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4ae0bcbd5c8043e794699cfb28ed7b66",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3c333f97a45843d7aa3299fdbb12a905",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":124,
                          "y":34},
                        "size":{
                          "width":131,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"76a6b90667f34f87a307a3ace448907e",
                  "label":"alert-添加成功",
                  "parentDynamicPanel":"3c333f97a45843d7aa3299fdbb12a905",
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":false,
                  "style":{
                    "location":{
                      "x":291,
                      "y":19},
                    "size":{
                      "width":279,
                      "height":148},
                    "visible":false},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":true,
                  "propagate":false,
                  "diagrams":[{
                      "id":"50f54203e53048cd9ce68d36821c7402",
                      "label":"State1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"0090d287882a4deeb0b197098d79f781",
                          "label":"border",
                          "parentDynamicPanel":"76a6b90667f34f87a307a3ace448907e",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "size":{
                              "width":279,
                              "height":148},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFF339900},
                            "outerShadow":{
                              "on":true,
                              "offsetX":5,
                              "offsetY":5,
                              "blurRadius":15,
                              "color":{
                                "r":0,
                                "g":0,
                                "b":0,
                                "a":0.349019607843137}}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"c2607ca796b14900accc27ae7cf9e53e",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"76a6b90667f34f87a307a3ace448907e",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "size":{
                                  "width":279,
                                  "height":148},
                                "borderFill":{
                                  "fillType":"solid",
                                  "color":0xFF339900},
                                "outerShadow":{
                                  "on":true,
                                  "offsetX":5,
                                  "offsetY":5,
                                  "blurRadius":15,
                                  "color":{
                                    "r":0,
                                    "g":0,
                                    "b":0,
                                    "a":0.349019607843137}}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/修改个人资料/border_u253.png"}},
{
                          "id":"11ad2dccf4fd449bbc5c06866c715990",
                          "label":"",
                          "parentDynamicPanel":"76a6b90667f34f87a307a3ace448907e",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":1,
                              "y":1},
                            "size":{
                              "width":277,
                              "height":146}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"237d9f69cb3949148b91807d640991a2",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"76a6b90667f34f87a307a3ace448907e",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":1,
                                  "y":1},
                                "size":{
                                  "width":277,
                                  "height":146}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/修改个人资料/u255.jpg"}},
{
                          "id":"9bf75c94826c49cdab3bb93e9e8f79e4",
                          "label":"",
                          "parentDynamicPanel":"76a6b90667f34f87a307a3ace448907e",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":10,
                              "y":34},
                            "size":{
                              "width":35,
                              "height":36}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"e5fd2b23b38b40abb6a9edca48093405",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"76a6b90667f34f87a307a3ace448907e",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":10,
                                  "y":34},
                                "size":{
                                  "width":35,
                                  "height":36}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/修改个人资料/u257.jpg"}},
{
                          "id":"7ff16eebb354421298240fe8d1b51fdc",
                          "label":"",
                          "parentDynamicPanel":"76a6b90667f34f87a307a3ace448907e",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF009900,
                              "opacity":1},
                            "location":{
                              "x":57,
                              "y":38},
                            "size":{
                              "width":214,
                              "height":46}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"94a0331065f14576b1404871fd39b91a",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"76a6b90667f34f87a307a3ace448907e",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontSize":"14px",
                                "foreGroundFill":{
                                  "fillType":"solid",
                                  "color":0xFF009900,
                                  "opacity":1},
                                "location":{
                                  "x":57,
                                  "y":38},
                                "size":{
                                  "width":214,
                                  "height":46}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"a91c29b2fc3c41f59177700ddc06e6d5",
                          "label":"",
                          "parentDynamicPanel":"76a6b90667f34f87a307a3ace448907e",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":240,
                              "y":10},
                            "size":{
                              "width":37,
                              "height":16}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"0534a18859da438c9f04791a9b61f1e9",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"76a6b90667f34f87a307a3ace448907e",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":240,
                                  "y":10},
                                "size":{
                                  "width":37,
                                  "height":16}},
                              "adaptiveStyles":{
}}],
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"用例 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"fadeWidget",
                                      "description":"隐藏 This,<br>alert-添加成功,<br>border",
                                      "objectsToFades":[{
                                          "objectPath":["a91c29b2fc3c41f59177700ddc06e6d5"],
                                          "fadeInfo":{
                                            "fadeType":"hide",
                                            "options":{
                                              "showType":"none"}}},
{
                                          "objectPath":["76a6b90667f34f87a307a3ace448907e"],
                                          "fadeInfo":{
                                            "fadeType":"hide",
                                            "options":{
                                              "showType":"none"}}},
{
                                          "objectPath":["0090d287882a4deeb0b197098d79f781"],
                                          "fadeInfo":{
                                            "fadeType":"hide",
                                            "options":{
                                              "showType":"none"}}}]}]}]}},
                          "tabbable":true,
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"902e0e5a287d43ab8158653521a05f37",
                          "label":"",
                          "parentDynamicPanel":"76a6b90667f34f87a307a3ace448907e",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "fontName":"'Arial Negreta', 'Arial'",
                            "fontWeight":"700",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1},
                            "stateStyles":{
                              "mouseOver":{
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFF87DB01}}},
                            "fill":{
                              "fillType":"solid",
                              "color":0xFF33CC00},
                            "location":{
                              "x":99,
                              "y":114},
                            "size":{
                              "width":81,
                              "height":26},
                            "borderWidth":"-1",
                            "cornerRadiusTopLeft":"3"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"60706bb4cfc24454b23330c25c174a0d",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"76a6b90667f34f87a307a3ace448907e",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontName":"'Arial Negreta', 'Arial'",
                                "fontWeight":"700",
                                "foreGroundFill":{
                                  "fillType":"solid",
                                  "color":0xFFFFFFFF,
                                  "opacity":1},
                                "stateStyles":{
                                  "mouseOver":{
                                    "fill":{
                                      "fillType":"solid",
                                      "color":0xFF87DB01}}},
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFF33CC00},
                                "location":{
                                  "x":99,
                                  "y":114},
                                "size":{
                                  "width":81,
                                  "height":26},
                                "borderWidth":"-1",
                                "cornerRadiusTopLeft":"3"},
                              "adaptiveStyles":{
}}],
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"用例 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"fadeWidget",
                                      "description":"隐藏 alert-添加成功,<br>border",
                                      "objectsToFades":[{
                                          "objectPath":["76a6b90667f34f87a307a3ace448907e"],
                                          "fadeInfo":{
                                            "fadeType":"hide",
                                            "options":{
                                              "showType":"none"}}},
{
                                          "objectPath":["0090d287882a4deeb0b197098d79f781"],
                                          "fadeInfo":{
                                            "fadeType":"hide",
                                            "options":{
                                              "showType":"none"}}}]},
{
                                      "action":"setPanelState",
                                      "description":"设置 fin 到 step3",
                                      "panelsToStates":[{
                                          "panelPath":["3c333f97a45843d7aa3299fdbb12a905"],
                                          "stateInfo":{
                                            "setStateType":"diagram",
                                            "stateNumber":3,
                                            "stateValue":{
                                              "exprType":"stringLiteral",
                                              "value":"1",
                                              "stos":[]},
                                            "loop":false,
                                            "showWhenSet":false,
                                            "options":{
                                              "compress":false}}}]}]}]}},
                          "tabbable":true,
                          "images":{
                            "normal~":"images/修改个人资料/u263.png",
                            "mouseOver~":"images/修改个人资料/u102_mouseOver.png"}}]}]}]},
{
              "id":"cdc46edde727464a9d3b69c34030e05d",
              "label":"step3",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"d847ad15b93d40e09aa7baebbdd89e47",
                  "label":"",
                  "parentDynamicPanel":"3c333f97a45843d7aa3299fdbb12a905",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":48,
                      "y":30},
                    "size":{
                      "width":79,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3e939178098c49b4a995b32648008645",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3c333f97a45843d7aa3299fdbb12a905",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":48,
                          "y":30},
                        "size":{
                          "width":79,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"5aa64e7606ef41df844421705c8db44d",
                  "label":"",
                  "parentDynamicPanel":"3c333f97a45843d7aa3299fdbb12a905",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":150,
                      "y":26},
                    "size":{
                      "width":200,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"7acb3bc0df9041b8bbfba4656d496a6a",
                  "label":"",
                  "parentDynamicPanel":"3c333f97a45843d7aa3299fdbb12a905",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":48,
                      "y":79},
                    "size":{
                      "width":105,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b0f9817eed394e9f8b143853b29c6c63",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3c333f97a45843d7aa3299fdbb12a905",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":48,
                          "y":79},
                        "size":{
                          "width":105,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d38eb956f062412ab6faad0cc81d4535",
                  "label":"",
                  "parentDynamicPanel":"3c333f97a45843d7aa3299fdbb12a905",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":150,
                      "y":75},
                    "size":{
                      "width":200,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"1f88cd9988794033bcdc9cdc9d8e7ee6",
                  "label":"",
                  "parentDynamicPanel":"3c333f97a45843d7aa3299fdbb12a905",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF87DB01}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF6AB30C},
                    "location":{
                      "x":150,
                      "y":136},
                    "size":{
                      "width":113,
                      "height":34},
                    "borderWidth":"-1",
                    "cornerRadiusTopLeft":"3"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a612f760cc094e5bb29bf388a7745f8a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3c333f97a45843d7aa3299fdbb12a905",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontSize":"16px",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "fill":{
                              "fillType":"solid",
                              "color":0xFF87DB01}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF6AB30C},
                        "location":{
                          "x":150,
                          "y":136},
                        "size":{
                          "width":113,
                          "height":34},
                        "borderWidth":"-1",
                        "cornerRadiusTopLeft":"3"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 alert-添加成功,<br>隐藏 border",
                              "objectsToFades":[{
                                  "objectPath":["b140e17d9a5242bba327214eea3a521a"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["23200135dfa34783931163826909a695"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]},
{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 会员中心默认页",
                              "target":{
                                "targetType":"page",
                                "url":"会员中心默认页.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/找回密码/u21.png",
                    "mouseOver~":"images/找回密码/u21_mouseOver.png"}},
{
                  "id":"b140e17d9a5242bba327214eea3a521a",
                  "label":"alert-添加成功",
                  "parentDynamicPanel":"3c333f97a45843d7aa3299fdbb12a905",
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":false,
                  "style":{
                    "location":{
                      "x":291,
                      "y":19},
                    "size":{
                      "width":279,
                      "height":148},
                    "visible":false},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":true,
                  "propagate":false,
                  "diagrams":[{
                      "id":"45ba0c7270724f0c8743cc24f2a619f6",
                      "label":"State1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"23200135dfa34783931163826909a695",
                          "label":"border",
                          "parentDynamicPanel":"b140e17d9a5242bba327214eea3a521a",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "size":{
                              "width":279,
                              "height":148},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFF339900},
                            "outerShadow":{
                              "on":true,
                              "offsetX":5,
                              "offsetY":5,
                              "blurRadius":15,
                              "color":{
                                "r":0,
                                "g":0,
                                "b":0,
                                "a":0.349019607843137}}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"c21097db0ae84174a0eb6ea304d9f7ec",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"b140e17d9a5242bba327214eea3a521a",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "size":{
                                  "width":279,
                                  "height":148},
                                "borderFill":{
                                  "fillType":"solid",
                                  "color":0xFF339900},
                                "outerShadow":{
                                  "on":true,
                                  "offsetX":5,
                                  "offsetY":5,
                                  "blurRadius":15,
                                  "color":{
                                    "r":0,
                                    "g":0,
                                    "b":0,
                                    "a":0.349019607843137}}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/修改个人资料/border_u253.png"}},
{
                          "id":"e37052044dea4849b328e777fdc95c21",
                          "label":"",
                          "parentDynamicPanel":"b140e17d9a5242bba327214eea3a521a",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":1,
                              "y":1},
                            "size":{
                              "width":277,
                              "height":146}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"deec5cef756d4a198d9f893b9ec0fa70",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"b140e17d9a5242bba327214eea3a521a",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":1,
                                  "y":1},
                                "size":{
                                  "width":277,
                                  "height":146}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/修改个人资料/u255.jpg"}},
{
                          "id":"6136fd69343442bc9c6c839a102fc13f",
                          "label":"",
                          "parentDynamicPanel":"b140e17d9a5242bba327214eea3a521a",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":10,
                              "y":34},
                            "size":{
                              "width":35,
                              "height":36}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"be36b2b28e3a47008787f480e718118e",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"b140e17d9a5242bba327214eea3a521a",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":10,
                                  "y":34},
                                "size":{
                                  "width":35,
                                  "height":36}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/修改个人资料/u257.jpg"}},
{
                          "id":"05fb3e694d114828be4709de22f51f9e",
                          "label":"",
                          "parentDynamicPanel":"b140e17d9a5242bba327214eea3a521a",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF009900,
                              "opacity":1},
                            "location":{
                              "x":57,
                              "y":38},
                            "size":{
                              "width":214,
                              "height":46}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"fa2560728bf940c6b43b7c6ef1aaba16",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"b140e17d9a5242bba327214eea3a521a",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontSize":"14px",
                                "foreGroundFill":{
                                  "fillType":"solid",
                                  "color":0xFF009900,
                                  "opacity":1},
                                "location":{
                                  "x":57,
                                  "y":38},
                                "size":{
                                  "width":214,
                                  "height":46}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"e507f5d0e053462291f1520670fe163a",
                          "label":"",
                          "parentDynamicPanel":"b140e17d9a5242bba327214eea3a521a",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":240,
                              "y":10},
                            "size":{
                              "width":37,
                              "height":16}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"7342926a2e594a9ebe1b4075821b3289",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"b140e17d9a5242bba327214eea3a521a",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":240,
                                  "y":10},
                                "size":{
                                  "width":37,
                                  "height":16}},
                              "adaptiveStyles":{
}}],
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"用例 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"fadeWidget",
                                      "description":"隐藏 This,<br>alert-添加成功,<br>border",
                                      "objectsToFades":[{
                                          "objectPath":["e507f5d0e053462291f1520670fe163a"],
                                          "fadeInfo":{
                                            "fadeType":"hide",
                                            "options":{
                                              "showType":"none"}}},
{
                                          "objectPath":["b140e17d9a5242bba327214eea3a521a"],
                                          "fadeInfo":{
                                            "fadeType":"hide",
                                            "options":{
                                              "showType":"none"}}},
{
                                          "objectPath":["23200135dfa34783931163826909a695"],
                                          "fadeInfo":{
                                            "fadeType":"hide",
                                            "options":{
                                              "showType":"none"}}}]}]}]}},
                          "tabbable":true,
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"8b1ba9a54e7b46b0852751e0c41f3732",
                          "label":"",
                          "parentDynamicPanel":"b140e17d9a5242bba327214eea3a521a",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "fontName":"'Arial Negreta', 'Arial'",
                            "fontWeight":"700",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1},
                            "stateStyles":{
                              "mouseOver":{
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFF87DB01}}},
                            "fill":{
                              "fillType":"solid",
                              "color":0xFF33CC00},
                            "location":{
                              "x":99,
                              "y":114},
                            "size":{
                              "width":81,
                              "height":26},
                            "borderWidth":"-1",
                            "cornerRadiusTopLeft":"3"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"0bd2746b714c4154a7196ef3f5f02e91",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"b140e17d9a5242bba327214eea3a521a",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontName":"'Arial Negreta', 'Arial'",
                                "fontWeight":"700",
                                "foreGroundFill":{
                                  "fillType":"solid",
                                  "color":0xFFFFFFFF,
                                  "opacity":1},
                                "stateStyles":{
                                  "mouseOver":{
                                    "fill":{
                                      "fillType":"solid",
                                      "color":0xFF87DB01}}},
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFF33CC00},
                                "location":{
                                  "x":99,
                                  "y":114},
                                "size":{
                                  "width":81,
                                  "height":26},
                                "borderWidth":"-1",
                                "cornerRadiusTopLeft":"3"},
                              "adaptiveStyles":{
}}],
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"用例 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"fadeWidget",
                                      "description":"隐藏 alert-添加成功,<br>border",
                                      "objectsToFades":[{
                                          "objectPath":["b140e17d9a5242bba327214eea3a521a"],
                                          "fadeInfo":{
                                            "fadeType":"hide",
                                            "options":{
                                              "showType":"none"}}},
{
                                          "objectPath":["23200135dfa34783931163826909a695"],
                                          "fadeInfo":{
                                            "fadeType":"hide",
                                            "options":{
                                              "showType":"none"}}}]},
{
                                      "action":"linkWindow",
                                      "description":"在 当前窗口 打开 会员中心默认页",
                                      "target":{
                                        "targetType":"page",
                                        "url":"会员中心默认页.html",
                                        "includeVariables":true},
                                      "linkType":"current"}]}]}},
                          "tabbable":true,
                          "images":{
                            "normal~":"images/修改个人资料/u263.png",
                            "mouseOver~":"images/修改个人资料/u102_mouseOver.png"}}]}]},
{
                  "id":"5ac0ad5ef71c4990b8dfde21c90f5f5c",
                  "label":"",
                  "parentDynamicPanel":"3c333f97a45843d7aa3299fdbb12a905",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000,
                      "opacity":1},
                    "location":{
                      "x":48,
                      "y":200},
                    "size":{
                      "width":326,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9197e3f6a40b473bbe8ad51b12e1acdd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3c333f97a45843d7aa3299fdbb12a905",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF0000,
                          "opacity":1},
                        "location":{
                          "x":48,
                          "y":200},
                        "size":{
                          "width":326,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"3bc467251a794627b3148146307e90fe",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":99.5,
              "y":496}},
          "adaptiveStyles":{
},
          "masterId":"034e31733593431b98870f4edc72282d"}]}},
  "masters":{
    "034e31733593431b98870f4edc72282d":{
      "packageId":"034e31733593431b98870f4edc72282d",
      "type":"Axure:Master",
      "name":"底部版权",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"9a9f5c774c684cc4a9d6c03ef9dadf10",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "size":{
                "width":1001,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFBCBCBC}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/首页/u228_line.png"}},
{
            "id":"c3007cf040264ffc9d39990f7013110a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":330,
                "y":48},
              "size":{
                "width":181,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1c4621b95ceb4f86b0fdc69452cd957d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":330,
                    "y":48},
                  "size":{
                    "width":181,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"967cbac02d134f8f9da4fc620a93c521",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":272,
                "y":15},
              "size":{
                "width":46,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"14c0172691ee4563b55ddaf2db6595a5",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":272,
                    "y":15},
                  "size":{
                    "width":46,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 首页",
                        "target":{
                          "targetType":"page",
                          "url":"首页.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"23326f30dc93476b9e2fe4260520a628",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":332,
                "y":15},
              "size":{
                "width":80,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"29db2cd2137540059193cf0dcd3fca0f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":332,
                    "y":15},
                  "size":{
                    "width":80,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 底部单页",
                        "target":{
                          "targetType":"page",
                          "url":"底部单页.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"bda92ae43e734a899ab158f1b89dfe86",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":428,
                "y":15},
              "size":{
                "width":68,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d167430e74674c2f8aab552672946c5a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":428,
                    "y":15},
                  "size":{
                    "width":68,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 版权声明",
                        "target":{
                          "targetType":"page",
                          "url":"版权声明.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"af72b5bec7584c05be709045f54c5fe3",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":518,
                "y":15},
              "size":{
                "width":68,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"798e31d3880446c7a97bc7461e00e77a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":518,
                    "y":15},
                  "size":{
                    "width":68,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 人才招聘",
                        "target":{
                          "targetType":"page",
                          "url":"人才招聘.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"2e8f1d145ab8429d91eaf4c516fc9c4f",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":612,
                "y":15},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6ba9e1b5310b428f857d810b034018bb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":612,
                    "y":15},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 联系我们",
                        "target":{
                          "targetType":"page",
                          "url":"联系我们.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "c9bbe925f6b442e6a76bd9764d59769d":{
      "scriptId":"u0"},
    "3798cd52d0cd47c6bc31dd5c5ff2f32c":{
      "scriptId":"u1"},
    "2837f0b612da4387b498391ed6c3ff5d":{
      "scriptId":"u2"},
    "b7554e0242714452858510a796e682b3":{
      "scriptId":"u3"},
    "502ccbbf249741d5be3b24c64562123e":{
      "scriptId":"u4"},
    "2637438670d24202b5d223fa37acacd5":{
      "scriptId":"u5"},
    "d50e21dedc6f41a1a716f521e47d0498":{
      "scriptId":"u6"},
    "fb7c8ae35af046ba850e19aea3c6b7c6":{
      "scriptId":"u7"},
    "713bf7f06f364bd08372f5d75be79009":{
      "scriptId":"u8"},
    "af9a65e305ab422c8901ce36972dd132":{
      "scriptId":"u9"},
    "a2936f89ef924c73825aab5c43761701":{
      "scriptId":"u10"},
    "c7c49dd2a2504839a7935401ef42731e":{
      "scriptId":"u11"},
    "16be86de37c34f45b2a7f6bbec63af40":{
      "scriptId":"u12"},
    "8f955c8edec049f4976ba4731466441b":{
      "scriptId":"u13"},
    "1babf875d44c495c973f52bb8720d885":{
      "scriptId":"u14"},
    "4a15986020a049729ca1990b556fc984":{
      "scriptId":"u15"},
    "f77d619c21a14c0194eff7a5e0da6271":{
      "scriptId":"u16"},
    "3c333f97a45843d7aa3299fdbb12a905":{
      "scriptId":"u17"},
    "ebb5c2c36dcf433cb1fc9e172abbbf5a":{
      "scriptId":"u18"},
    "e0a4a585e80e4a24aae4bb5888c2575a":{
      "scriptId":"u19"},
    "50451a0d32a548888eb480db88a3fd43":{
      "scriptId":"u20"},
    "3fc3b677b93f4971a74edce266465471":{
      "scriptId":"u21"},
    "c3f7aafdc28b485da70ca1274631540f":{
      "scriptId":"u22"},
    "40e88fe5b009479bb22e6e23ac4197fa":{
      "scriptId":"u23"},
    "6032233282fd4f45abc650f177ef1c12":{
      "scriptId":"u24"},
    "729e9fe874554ecf8376894a3fbf89ca":{
      "scriptId":"u25"},
    "74b6ffb77f704e23b1ca941c6148429a":{
      "scriptId":"u26"},
    "4d01cd4045814301a770d0db9a77e0e4":{
      "scriptId":"u27"},
    "0fb0e631d3fb4ab6a84ef62b06092229":{
      "scriptId":"u28"},
    "8b5383e15bd345c4abc942b4c47bee4f":{
      "scriptId":"u29"},
    "f5724766b3df40328a6526d2fd6d2bc9":{
      "scriptId":"u30"},
    "4ae0bcbd5c8043e794699cfb28ed7b66":{
      "scriptId":"u31"},
    "76a6b90667f34f87a307a3ace448907e":{
      "scriptId":"u32"},
    "0090d287882a4deeb0b197098d79f781":{
      "scriptId":"u33"},
    "c2607ca796b14900accc27ae7cf9e53e":{
      "scriptId":"u34"},
    "11ad2dccf4fd449bbc5c06866c715990":{
      "scriptId":"u35"},
    "237d9f69cb3949148b91807d640991a2":{
      "scriptId":"u36"},
    "9bf75c94826c49cdab3bb93e9e8f79e4":{
      "scriptId":"u37"},
    "e5fd2b23b38b40abb6a9edca48093405":{
      "scriptId":"u38"},
    "7ff16eebb354421298240fe8d1b51fdc":{
      "scriptId":"u39"},
    "94a0331065f14576b1404871fd39b91a":{
      "scriptId":"u40"},
    "a91c29b2fc3c41f59177700ddc06e6d5":{
      "scriptId":"u41"},
    "0534a18859da438c9f04791a9b61f1e9":{
      "scriptId":"u42"},
    "902e0e5a287d43ab8158653521a05f37":{
      "scriptId":"u43"},
    "60706bb4cfc24454b23330c25c174a0d":{
      "scriptId":"u44"},
    "d847ad15b93d40e09aa7baebbdd89e47":{
      "scriptId":"u45"},
    "3e939178098c49b4a995b32648008645":{
      "scriptId":"u46"},
    "5aa64e7606ef41df844421705c8db44d":{
      "scriptId":"u47"},
    "7acb3bc0df9041b8bbfba4656d496a6a":{
      "scriptId":"u48"},
    "b0f9817eed394e9f8b143853b29c6c63":{
      "scriptId":"u49"},
    "d38eb956f062412ab6faad0cc81d4535":{
      "scriptId":"u50"},
    "1f88cd9988794033bcdc9cdc9d8e7ee6":{
      "scriptId":"u51"},
    "a612f760cc094e5bb29bf388a7745f8a":{
      "scriptId":"u52"},
    "b140e17d9a5242bba327214eea3a521a":{
      "scriptId":"u53"},
    "23200135dfa34783931163826909a695":{
      "scriptId":"u54"},
    "c21097db0ae84174a0eb6ea304d9f7ec":{
      "scriptId":"u55"},
    "e37052044dea4849b328e777fdc95c21":{
      "scriptId":"u56"},
    "deec5cef756d4a198d9f893b9ec0fa70":{
      "scriptId":"u57"},
    "6136fd69343442bc9c6c839a102fc13f":{
      "scriptId":"u58"},
    "be36b2b28e3a47008787f480e718118e":{
      "scriptId":"u59"},
    "05fb3e694d114828be4709de22f51f9e":{
      "scriptId":"u60"},
    "fa2560728bf940c6b43b7c6ef1aaba16":{
      "scriptId":"u61"},
    "e507f5d0e053462291f1520670fe163a":{
      "scriptId":"u62"},
    "7342926a2e594a9ebe1b4075821b3289":{
      "scriptId":"u63"},
    "8b1ba9a54e7b46b0852751e0c41f3732":{
      "scriptId":"u64"},
    "0bd2746b714c4154a7196ef3f5f02e91":{
      "scriptId":"u65"},
    "5ac0ad5ef71c4990b8dfde21c90f5f5c":{
      "scriptId":"u66"},
    "9197e3f6a40b473bbe8ad51b12e1acdd":{
      "scriptId":"u67"},
    "3bc467251a794627b3148146307e90fe":{
      "scriptId":"u68",
      "9a9f5c774c684cc4a9d6c03ef9dadf10":{
        "scriptId":"u69"},
      "c3007cf040264ffc9d39990f7013110a":{
        "scriptId":"u70"},
      "1c4621b95ceb4f86b0fdc69452cd957d":{
        "scriptId":"u71"},
      "967cbac02d134f8f9da4fc620a93c521":{
        "scriptId":"u72"},
      "14c0172691ee4563b55ddaf2db6595a5":{
        "scriptId":"u73"},
      "23326f30dc93476b9e2fe4260520a628":{
        "scriptId":"u74"},
      "29db2cd2137540059193cf0dcd3fca0f":{
        "scriptId":"u75"},
      "bda92ae43e734a899ab158f1b89dfe86":{
        "scriptId":"u76"},
      "d167430e74674c2f8aab552672946c5a":{
        "scriptId":"u77"},
      "af72b5bec7584c05be709045f54c5fe3":{
        "scriptId":"u78"},
      "798e31d3880446c7a97bc7461e00e77a":{
        "scriptId":"u79"},
      "2e8f1d145ab8429d91eaf4c516fc9c4f":{
        "scriptId":"u80"},
      "6ba9e1b5310b428f857d810b034018bb":{
        "scriptId":"u81"}}}});