$axure.loadCurrentPage({
  "url":"会员登录.html",
  "generationDate":new Date(1383013844330.84),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"90fa7bc399dc4f35b2700a484ff3a58f",
    "type":"Axure:Page",
    "name":"会员登录",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"65b3e94f8fd64058af03fdb86d53e362",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":114,
              "y":6},
            "size":{
              "width":149,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cfd3c99fa3eb4e6eab184e30d0550240",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":114,
                  "y":6},
                "size":{
                  "width":149,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dbdb4da35f054cad86bf614c4c71aad5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":900,
              "y":6},
            "size":{
              "width":42,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d854defe95d40d59c1dc2db26cceff1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":900,
                  "y":6},
                "size":{
                  "width":42,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8fb56859c4434c068c6fa34735ec726e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":952,
              "y":6},
            "size":{
              "width":64,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb8c996fb9214d24875d74864a878415",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":952,
                  "y":6},
                "size":{
                  "width":64,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4137443f36b14e8fa47ee83e439ecbe0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1028,
              "y":7},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54755483a40a450780191e7fbe67e3e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1028,
                  "y":7},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"659d7d19a14e40f2b350fc54dbed4abd",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":21},
            "size":{
              "width":1200,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE0E0E0}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页/u10_line.png"}},
{
          "id":"1dba8420ce0d415a9772ab1cf50087a6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":26},
            "size":{
              "width":1200,
              "height":106},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF5C5D5F}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c4245fba2e0488c95100b613762bd1b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":26},
                "size":{
                  "width":1200,
                  "height":106},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF5C5D5F}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u11.jpg"}},
{
          "id":"0a8a3db4e2c9498ea53353f5ebca3024",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":114,
              "y":157},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6398f100f27452e8ef3135e56f6dc1b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":114,
                  "y":157},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u19.png"}},
{
          "id":"725fe63ba57e4339a392344a6d638ef3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":140,
              "y":154},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7304011b28a4ba59c3edac8c208cdc7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":140,
                  "y":154},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"368d44365b244c62af4c9ac7a1f38077",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":738,
              "y":171},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c57eaeef55d64a94bb12c5f3ab5bbbd6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":738,
                  "y":171},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b5c50b4b737940afbb4309699979829a",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":737,
              "y":193},
            "size":{
              "width":240,
              "height":33}},
          "adaptiveStyles":{
}},
{
          "id":"81fe0cf96e754131a6487e2a0c546e8f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":737,
              "y":235},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cfd211cd816c4f8a939b3a6963df63b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":737,
                  "y":235},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c068ad3c50424c24999d8eca995fbaf6",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":737,
              "y":260},
            "size":{
              "width":240,
              "height":33}},
          "adaptiveStyles":{
}},
{
          "id":"49c76ef0f69944159a90354fcd949630",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":737,
              "y":323},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48f155d5d2dd4ada99acf32a857591a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":737,
                  "y":323},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6a8a80f132b44575bb501fa2c5aaafd9",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":737,
              "y":349},
            "size":{
              "width":111,
              "height":33}},
          "adaptiveStyles":{
}},
{
          "id":"e543f47bb97b472799285f933d8f097e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":863,
              "y":353},
            "size":{
              "width":59,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37dbb668831c48239bd1e4b6153f2e30",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":863,
                  "y":353},
                "size":{
                  "width":59,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u32.jpg"}},
{
          "id":"1585a08518e443e4b46086e4611c771c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":872,
              "y":302},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"300c1b5cb56a4c91ae5e4d78440079de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":872,
                  "y":302},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 找回密码",
                      "target":{
                        "targetType":"page",
                        "url":"找回密码.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4802fb7bdba04e09893db188d9314999",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":99,
              "y":26},
            "size":{
              "width":276,
              "height":106}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a2cdafd69094f1988fb09455c8062de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":99,
                  "y":26},
                "size":{
                  "width":276,
                  "height":106}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a3f163aff1344f0d848bf50f73764e97",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":739,
              "y":458},
            "size":{
              "width":122,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d7d493b630848a09587782a49224572",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":739,
                  "y":458},
                "size":{
                  "width":122,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 会员注册",
                      "target":{
                        "targetType":"page",
                        "url":"会员注册.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d5558d90f5e1491c99d8d709f99f63ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF87DB01}}},
            "fill":{
              "fillType":"solid",
              "color":0xFF6AB30C},
            "location":{
              "x":737,
              "y":400},
            "size":{
              "width":240,
              "height":34},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92e3aee54afe42d8990f3c89b7cccf2d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF87DB01}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF6AB30C},
                "location":{
                  "x":737,
                  "y":400},
                "size":{
                  "width":240,
                  "height":34},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 会员中心默认页",
                      "target":{
                        "targetType":"page",
                        "url":"会员中心默认页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/会员登录/u32.png",
            "mouseOver~":"images/会员登录/u32_mouseOver.png"}},
{
          "id":"74ea9eca6c274f769d573fa9833f6e0a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":177,
              "y":194},
            "size":{
              "width":436,
              "height":263},
            "outerShadow":{
              "on":true,
              "offsetX":11,
              "offsetY":11,
              "blurRadius":11,
              "color":{
                "r":215,
                "g":215,
                "b":215,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"028b3c9ced4d41f79e7e30029f68eab1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":177,
                  "y":194},
                "size":{
                  "width":436,
                  "height":263},
                "outerShadow":{
                  "on":true,
                  "offsetX":11,
                  "offsetY":11,
                  "blurRadius":11,
                  "color":{
                    "r":215,
                    "g":215,
                    "b":215,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员登录/u34.png"}},
{
          "id":"164dd4053d8449febc5bbcacbe0fa9f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":932,
              "y":356},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"046a4f16e841478cb458d9edd0b76045",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":932,
                  "y":356},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cc9cc2604025408a8dfc6b32d56b50b4",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":506}},
          "adaptiveStyles":{
},
          "masterId":"034e31733593431b98870f4edc72282d"}]}},
  "masters":{
    "034e31733593431b98870f4edc72282d":{
      "packageId":"034e31733593431b98870f4edc72282d",
      "type":"Axure:Master",
      "name":"底部版权",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"9a9f5c774c684cc4a9d6c03ef9dadf10",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "size":{
                "width":1001,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFBCBCBC}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/首页/u228_line.png"}},
{
            "id":"c3007cf040264ffc9d39990f7013110a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":330,
                "y":48},
              "size":{
                "width":181,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1c4621b95ceb4f86b0fdc69452cd957d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":330,
                    "y":48},
                  "size":{
                    "width":181,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"967cbac02d134f8f9da4fc620a93c521",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":272,
                "y":15},
              "size":{
                "width":46,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"14c0172691ee4563b55ddaf2db6595a5",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":272,
                    "y":15},
                  "size":{
                    "width":46,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 首页",
                        "target":{
                          "targetType":"page",
                          "url":"首页.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"23326f30dc93476b9e2fe4260520a628",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":332,
                "y":15},
              "size":{
                "width":80,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"29db2cd2137540059193cf0dcd3fca0f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":332,
                    "y":15},
                  "size":{
                    "width":80,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 底部单页",
                        "target":{
                          "targetType":"page",
                          "url":"底部单页.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"bda92ae43e734a899ab158f1b89dfe86",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":428,
                "y":15},
              "size":{
                "width":68,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d167430e74674c2f8aab552672946c5a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":428,
                    "y":15},
                  "size":{
                    "width":68,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 版权声明",
                        "target":{
                          "targetType":"page",
                          "url":"版权声明.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"af72b5bec7584c05be709045f54c5fe3",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":518,
                "y":15},
              "size":{
                "width":68,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"798e31d3880446c7a97bc7461e00e77a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":518,
                    "y":15},
                  "size":{
                    "width":68,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 人才招聘",
                        "target":{
                          "targetType":"page",
                          "url":"人才招聘.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"2e8f1d145ab8429d91eaf4c516fc9c4f",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":612,
                "y":15},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6ba9e1b5310b428f857d810b034018bb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":612,
                    "y":15},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 联系我们",
                        "target":{
                          "targetType":"page",
                          "url":"联系我们.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "65b3e94f8fd64058af03fdb86d53e362":{
      "scriptId":"u0"},
    "cfd3c99fa3eb4e6eab184e30d0550240":{
      "scriptId":"u1"},
    "dbdb4da35f054cad86bf614c4c71aad5":{
      "scriptId":"u2"},
    "1d854defe95d40d59c1dc2db26cceff1":{
      "scriptId":"u3"},
    "8fb56859c4434c068c6fa34735ec726e":{
      "scriptId":"u4"},
    "cb8c996fb9214d24875d74864a878415":{
      "scriptId":"u5"},
    "4137443f36b14e8fa47ee83e439ecbe0":{
      "scriptId":"u6"},
    "54755483a40a450780191e7fbe67e3e3":{
      "scriptId":"u7"},
    "659d7d19a14e40f2b350fc54dbed4abd":{
      "scriptId":"u8"},
    "1dba8420ce0d415a9772ab1cf50087a6":{
      "scriptId":"u9"},
    "1c4245fba2e0488c95100b613762bd1b":{
      "scriptId":"u10"},
    "0a8a3db4e2c9498ea53353f5ebca3024":{
      "scriptId":"u11"},
    "c6398f100f27452e8ef3135e56f6dc1b":{
      "scriptId":"u12"},
    "725fe63ba57e4339a392344a6d638ef3":{
      "scriptId":"u13"},
    "c7304011b28a4ba59c3edac8c208cdc7":{
      "scriptId":"u14"},
    "368d44365b244c62af4c9ac7a1f38077":{
      "scriptId":"u15"},
    "c57eaeef55d64a94bb12c5f3ab5bbbd6":{
      "scriptId":"u16"},
    "b5c50b4b737940afbb4309699979829a":{
      "scriptId":"u17"},
    "81fe0cf96e754131a6487e2a0c546e8f":{
      "scriptId":"u18"},
    "cfd211cd816c4f8a939b3a6963df63b6":{
      "scriptId":"u19"},
    "c068ad3c50424c24999d8eca995fbaf6":{
      "scriptId":"u20"},
    "49c76ef0f69944159a90354fcd949630":{
      "scriptId":"u21"},
    "48f155d5d2dd4ada99acf32a857591a7":{
      "scriptId":"u22"},
    "6a8a80f132b44575bb501fa2c5aaafd9":{
      "scriptId":"u23"},
    "e543f47bb97b472799285f933d8f097e":{
      "scriptId":"u24"},
    "37dbb668831c48239bd1e4b6153f2e30":{
      "scriptId":"u25"},
    "1585a08518e443e4b46086e4611c771c":{
      "scriptId":"u26"},
    "300c1b5cb56a4c91ae5e4d78440079de":{
      "scriptId":"u27"},
    "4802fb7bdba04e09893db188d9314999":{
      "scriptId":"u28"},
    "4a2cdafd69094f1988fb09455c8062de":{
      "scriptId":"u29"},
    "a3f163aff1344f0d848bf50f73764e97":{
      "scriptId":"u30"},
    "8d7d493b630848a09587782a49224572":{
      "scriptId":"u31"},
    "d5558d90f5e1491c99d8d709f99f63ba":{
      "scriptId":"u32"},
    "92e3aee54afe42d8990f3c89b7cccf2d":{
      "scriptId":"u33"},
    "74ea9eca6c274f769d573fa9833f6e0a":{
      "scriptId":"u34"},
    "028b3c9ced4d41f79e7e30029f68eab1":{
      "scriptId":"u35"},
    "164dd4053d8449febc5bbcacbe0fa9f9":{
      "scriptId":"u36"},
    "046a4f16e841478cb458d9edd0b76045":{
      "scriptId":"u37"},
    "cc9cc2604025408a8dfc6b32d56b50b4":{
      "scriptId":"u38",
      "9a9f5c774c684cc4a9d6c03ef9dadf10":{
        "scriptId":"u39"},
      "c3007cf040264ffc9d39990f7013110a":{
        "scriptId":"u40"},
      "1c4621b95ceb4f86b0fdc69452cd957d":{
        "scriptId":"u41"},
      "967cbac02d134f8f9da4fc620a93c521":{
        "scriptId":"u42"},
      "14c0172691ee4563b55ddaf2db6595a5":{
        "scriptId":"u43"},
      "23326f30dc93476b9e2fe4260520a628":{
        "scriptId":"u44"},
      "29db2cd2137540059193cf0dcd3fca0f":{
        "scriptId":"u45"},
      "bda92ae43e734a899ab158f1b89dfe86":{
        "scriptId":"u46"},
      "d167430e74674c2f8aab552672946c5a":{
        "scriptId":"u47"},
      "af72b5bec7584c05be709045f54c5fe3":{
        "scriptId":"u48"},
      "798e31d3880446c7a97bc7461e00e77a":{
        "scriptId":"u49"},
      "2e8f1d145ab8429d91eaf4c516fc9c4f":{
        "scriptId":"u50"},
      "6ba9e1b5310b428f857d810b034018bb":{
        "scriptId":"u51"}}}});