$axure.loadCurrentPage({
  "url":"后台登录.html",
  "generationDate":new Date(1383013848944.11),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d09731ea73b241aca4d7f4c5b33fd7f4",
    "type":"Axure:Page",
    "name":"后台登录",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"eab90b823ae348a3853d5af5e8b0cc64",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009900,
              "opacity":1},
            "location":{
              "x":343,
              "y":190},
            "size":{
              "width":515,
              "height":279},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":15,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d3f6f610eec47d9b9aea9aec78b3e23",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009900,
                  "opacity":1},
                "location":{
                  "x":343,
                  "y":190},
                "size":{
                  "width":515,
                  "height":279},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":15,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/后台登录/u0.png"}},
{
          "id":"2115ae44e79a4472ac04878b144cc911",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":21},
            "size":{
              "width":1200,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE0E0E0}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页/u10_line.png"}},
{
          "id":"4d126631b13a4f94a14bd0bcb3d3d861",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":26},
            "size":{
              "width":1200,
              "height":106},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF5C5D5F}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c3c9d1eaa5c4b508bef744f36b3f9e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":26},
                "size":{
                  "width":1200,
                  "height":106},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF5C5D5F}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u11.jpg"}},
{
          "id":"d8afdc08b06a46c68ba700c282c1f28b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":443,
              "y":239},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52540a5cbabd43efbb1aab11f5f30d95",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":443,
                  "y":239},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3939a4d78a634ebc9fa08a55898abef1",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":442,
              "y":261},
            "size":{
              "width":240,
              "height":33}},
          "adaptiveStyles":{
}},
{
          "id":"90a1756b94054371a90a3a2130104360",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":442,
              "y":303},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"330f8c77069b4795b6bacda1809ba93d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":442,
                  "y":303},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"460bf830f9a54f178499f86ad9f33a68",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":442,
              "y":328},
            "size":{
              "width":240,
              "height":33}},
          "adaptiveStyles":{
}},
{
          "id":"c7097981bbcd4f7d9b4e96e00773a1a3",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":526},
            "size":{
              "width":1001,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页/u228_line.png"}},
{
          "id":"2b8ea42c6cdf40b4a1f66fa1300b38d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":430,
              "y":546},
            "size":{
              "width":181,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e647c338e7f14f54999c46b2c7801b4e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":430,
                  "y":546},
                "size":{
                  "width":181,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4017c6788f534625a6b4354e6e1a0e4b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":99,
              "y":26},
            "size":{
              "width":276,
              "height":106}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09805782bd0c4a079993209b90d34ec3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":99,
                  "y":26},
                "size":{
                  "width":276,
                  "height":106}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2a17717bf420446f89c84f51f97dbb6b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF87DB01}}},
            "fill":{
              "fillType":"solid",
              "color":0xFF6AB30C},
            "location":{
              "x":442,
              "y":399},
            "size":{
              "width":240,
              "height":34},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"3",
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":8,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"216772192c9445e798e8691238d156cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF87DB01}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF6AB30C},
                "location":{
                  "x":442,
                  "y":399},
                "size":{
                  "width":240,
                  "height":34},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"3",
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":8,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 新闻管理",
                      "target":{
                        "targetType":"page",
                        "url":"新闻管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/后台登录/u16.png",
            "mouseOver~":"images/后台登录/u16_mouseOver.png"}},
{
          "id":"3548a3790ff74f04a6386a67013886c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":491,
              "y":199},
            "size":{
              "width":254,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"181d770d554a41ff967f2ea9f1a8440d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":491,
                  "y":199},
                "size":{
                  "width":254,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "eab90b823ae348a3853d5af5e8b0cc64":{
      "scriptId":"u0"},
    "3d3f6f610eec47d9b9aea9aec78b3e23":{
      "scriptId":"u1"},
    "2115ae44e79a4472ac04878b144cc911":{
      "scriptId":"u2"},
    "4d126631b13a4f94a14bd0bcb3d3d861":{
      "scriptId":"u3"},
    "1c3c9d1eaa5c4b508bef744f36b3f9e6":{
      "scriptId":"u4"},
    "d8afdc08b06a46c68ba700c282c1f28b":{
      "scriptId":"u5"},
    "52540a5cbabd43efbb1aab11f5f30d95":{
      "scriptId":"u6"},
    "3939a4d78a634ebc9fa08a55898abef1":{
      "scriptId":"u7"},
    "90a1756b94054371a90a3a2130104360":{
      "scriptId":"u8"},
    "330f8c77069b4795b6bacda1809ba93d":{
      "scriptId":"u9"},
    "460bf830f9a54f178499f86ad9f33a68":{
      "scriptId":"u10"},
    "c7097981bbcd4f7d9b4e96e00773a1a3":{
      "scriptId":"u11"},
    "2b8ea42c6cdf40b4a1f66fa1300b38d3":{
      "scriptId":"u12"},
    "e647c338e7f14f54999c46b2c7801b4e":{
      "scriptId":"u13"},
    "4017c6788f534625a6b4354e6e1a0e4b":{
      "scriptId":"u14"},
    "09805782bd0c4a079993209b90d34ec3":{
      "scriptId":"u15"},
    "2a17717bf420446f89c84f51f97dbb6b":{
      "scriptId":"u16"},
    "216772192c9445e798e8691238d156cf":{
      "scriptId":"u17"},
    "3548a3790ff74f04a6386a67013886c8":{
      "scriptId":"u18"},
    "181d770d554a41ff967f2ea9f1a8440d":{
      "scriptId":"u19"}}});