$axure.loadCurrentPage({
  "url":"修改密码_1.html",
  "generationDate":new Date(1383013849015.11),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"36aea25c6f50438290374a2c37696b0e",
    "type":"Axure:Page",
    "name":"修改密码",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3de9b726181949dbb0299f9377c54361",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":170,
              "height":51}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9967453c36664684bca75575b2987fc6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":170,
                  "height":51}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改密码_1/u0.jpg"}},
{
          "id":"24c200271d0d4ef58798f91517d574f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":598,
              "y":4},
            "size":{
              "width":148,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44c8251392fb40e1b289d9054fd60346",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":598,
                  "y":4},
                "size":{
                  "width":148,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6ea68b56c2a64a68a3b879b8e6c1d1db",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":911,
              "y":4},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b6e8659eec14fd29a32afe098bb057f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":911,
                  "y":4},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 后台登录",
                      "target":{
                        "targetType":"page",
                        "url":"后台登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c18ebd45230747988ae1bc5aec630e45",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":828,
              "y":4},
            "size":{
              "width":88,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd8e8887347245a19d87fd66f31f9153",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":828,
                  "y":4},
                "size":{
                  "width":88,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 修改密码",
                      "target":{
                        "targetType":"page",
                        "url":"修改密码_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b1ace8676a5e405c9770445bfa15238f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":756,
              "y":4},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"126278ee4a0a4a3fa628ad5f5149f279",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":756,
                  "y":4},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c899262190774538942ea24321a3ef65",
          "label":"导航",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":50},
            "size":{
              "width":716,
              "height":129}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"c521b5980324476ea2129168927c9455",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"069f709635834d0ea7456d116879a0fc",
                  "label":"",
                  "parentDynamicPanel":"c899262190774538942ea24321a3ef65",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":90,
                      "y":7},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"75a3a25a7e504637b6850db0d2de89b2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c899262190774538942ea24321a3ef65",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":90,
                          "y":7},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示/隐藏部件",
                              "objectsToFades":[]},
{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 新闻管理",
                              "target":{
                                "targetType":"page",
                                "url":"新闻管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"6a6b7ba37ac648d4a74289a89391dfb8",
                  "label":"",
                  "parentDynamicPanel":"c899262190774538942ea24321a3ef65",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":300,
                      "y":7},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1eede98ad0e54347970cf3c127e93ae2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c899262190774538942ea24321a3ef65",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":300,
                          "y":7},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 KAB公告管理",
                              "target":{
                                "targetType":"page",
                                "url":"kab公告管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"8dfbef24649243f1a849b41dfb51a9ea",
                  "label":"",
                  "parentDynamicPanel":"c899262190774538942ea24321a3ef65",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":407,
                      "y":7},
                    "size":{
                      "width":79,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6d1cb9765f8c428ea4de2401240723a0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c899262190774538942ea24321a3ef65",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":407,
                          "y":7},
                        "size":{
                          "width":79,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 班级管理",
                              "target":{
                                "targetType":"page",
                                "url":"班级管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"99e4a6d6bfc749e08c496925aa382872",
                  "label":"",
                  "parentDynamicPanel":"c899262190774538942ea24321a3ef65",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":542,
                      "y":7},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c21e5ab8b1bd4699a2feb0f59bd3a5d4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c899262190774538942ea24321a3ef65",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":542,
                          "y":7},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 用户管理",
                              "target":{
                                "targetType":"page",
                                "url":"用户管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"03c627c8b9b4437ca2d8790d4905f351",
                  "label":"",
                  "parentDynamicPanel":"c899262190774538942ea24321a3ef65",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":637,
                      "y":7},
                    "size":{
                      "width":79,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"967cfe54653345b9a43b20e4e602480a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c899262190774538942ea24321a3ef65",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":637,
                          "y":7},
                        "size":{
                          "width":79,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 系统参数配置",
                              "target":{
                                "targetType":"page",
                                "url":"系统参数配置.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"fdf6c6bf37274c68aaeaf5751edaf85f",
                  "label":"",
                  "parentDynamicPanel":"c899262190774538942ea24321a3ef65",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":22},
                    "size":{
                      "width":1000,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/修改密码_1/u21_line.png"}},
{
                  "id":"536495c0f2194ad9b8114c335c248cc7",
                  "label":"",
                  "parentDynamicPanel":"c899262190774538942ea24321a3ef65",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "location":{
                      "x":165,
                      "y":7},
                    "size":{
                      "width":115,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"059700cb44664c4499704b119b3c2dda",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c899262190774538942ea24321a3ef65",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "location":{
                          "x":165,
                          "y":7},
                        "size":{
                          "width":115,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 KAB概况管理",
                              "target":{
                                "targetType":"page",
                                "url":"kab概况管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"2ce9effbac654fa3a1024e8430c48cf4",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":54,
              "y":117},
            "size":{
              "width":946,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF949494}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/修改密码_1/u24_line.png"}},
{
          "id":"398c01e4ec794ddb87a1e4c230f3b6e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":82,
              "y":99},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c714520666d34f2a921bfa2759ba8452",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":82,
                  "y":99},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8f136119fd1147e9b8b7a627e8be671c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":60,
              "y":100},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b859a38f65c841cd8b74d16b30707746",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":60,
                  "y":100},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改个人资料/u46.png"}},
{
          "id":"45d643072b7147fb81e8f2245e365d91",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF87DB01}}},
            "fill":{
              "fillType":"solid",
              "color":0xFF6AB30C},
            "location":{
              "x":197,
              "y":354},
            "size":{
              "width":81,
              "height":26},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48b0bcab40864fc1b6eeeacdcf2293e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF87DB01}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF6AB30C},
                "location":{
                  "x":197,
                  "y":354},
                "size":{
                  "width":81,
                  "height":26},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 alert",
                      "objectsToFades":[{
                          "objectPath":["ca5d131315414721bb80bc391671c1b9"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/修改个人资料/u102.png",
            "mouseOver~":"images/修改个人资料/u102_mouseOver.png"}},
{
          "id":"4e9373f4848d4ed3bac5a8ee195fc682",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF87DB01}}},
            "fill":{
              "fillType":"solid",
              "color":0xFF6AB30C},
            "location":{
              "x":316,
              "y":354},
            "size":{
              "width":81,
              "height":26},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4b43d30571245e29b0279a39db247d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF87DB01}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF6AB30C},
                "location":{
                  "x":316,
                  "y":354},
                "size":{
                  "width":81,
                  "height":26},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 新闻管理",
                      "target":{
                        "targetType":"page",
                        "url":"新闻管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/修改个人资料/u102.png",
            "mouseOver~":"images/修改个人资料/u102_mouseOver.png"}},
{
          "id":"7f5cfe6920d8430a90b9d8884e008d0b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":82,
              "y":189},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0ddbf19dc404573b08e8cca15e2a7b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":82,
                  "y":189},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dad48de2124847758bd4da44456be0ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":82,
              "y":242},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8bc4807b17334481b4c6097c860ef055",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":82,
                  "y":242},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"25dbd35cdba44c73835c8e94513d8285",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":197,
              "y":185},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"43b76eb03d024524a712de46e63d0afa",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":197,
              "y":233},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"82841b1749ca4076bfe7507af0495632",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":197,
              "y":290},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"91412289265744579786a883d7aee46c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":82,
              "y":295},
            "size":{
              "width":118,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c09d82e496ed42f69cbb7cc6bdfdea2f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":82,
                  "y":295},
                "size":{
                  "width":118,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5ccac17e52a04f84a74c798ee700163a",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":147,
              "y":198}},
          "adaptiveStyles":{
},
          "masterId":"c4f4574f84ac4b10b53e561ddcd8f2db"},
{
          "id":"ca5d131315414721bb80bc391671c1b9",
          "label":"alert",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":397,
              "y":170},
            "size":{
              "width":320,
              "height":190},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"5cdb996444094808ab8fdef7199bc580",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"a67281cae3de46a285b0ff4ca10e0ab1",
                  "label":"",
                  "parentDynamicPanel":"ca5d131315414721bb80bc391671c1b9",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":280,
                      "height":160}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"de92108cb516419990e614efcc2ef781",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ca5d131315414721bb80bc391671c1b9",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":280,
                          "height":160}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/修改密码_1/u44.png"}},
{
                  "id":"f25a24561bd445a8bf136e58424a2b38",
                  "label":"",
                  "parentDynamicPanel":"ca5d131315414721bb80bc391671c1b9",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "location":{
                      "x":42,
                      "y":9},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"08dc8d175d1542d490142b00186af8ee",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ca5d131315414721bb80bc391671c1b9",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontWeight":"700",
                        "location":{
                          "x":42,
                          "y":9},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"7e2791babd674fe8b0eb59e9b4115e04",
                  "label":"",
                  "parentDynamicPanel":"ca5d131315414721bb80bc391671c1b9",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":26},
                    "size":{
                      "width":280,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/修改密码_1/u48_line.png"}},
{
                  "id":"cced2182836a417ea3893c17b8e6205d",
                  "label":"",
                  "parentDynamicPanel":"ca5d131315414721bb80bc391671c1b9",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":101,
                      "y":120},
                    "size":{
                      "width":78,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"22e4291e9e174f988f6013ad2d4e6945",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ca5d131315414721bb80bc391671c1b9",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4},
                        "location":{
                          "x":101,
                          "y":120},
                        "size":{
                          "width":78,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 alert",
                              "objectsToFades":[{
                                  "objectPath":["ca5d131315414721bb80bc391671c1b9"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/修改密码_1/u49.png"}},
{
                  "id":"d27507abc7814d10ad34a1712c6ce7a3",
                  "label":"",
                  "parentDynamicPanel":"ca5d131315414721bb80bc391671c1b9",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":16,
                      "y":9},
                    "size":{
                      "width":16,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5febc04fbdf84a58a1e655297f21e82e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ca5d131315414721bb80bc391671c1b9",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "location":{
                          "x":16,
                          "y":9},
                        "size":{
                          "width":16,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/修改密码_1/u51.png"}},
{
                  "id":"a984ad0e34cf438394525252989f8439",
                  "label":"",
                  "parentDynamicPanel":"ca5d131315414721bb80bc391671c1b9",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":126,
                      "y":72},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1c2fb3da9512428baa5f447ff74e4851",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ca5d131315414721bb80bc391671c1b9",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":126,
                          "y":72},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d753d5b42bee4fe4af00ec20be450075",
                  "label":"",
                  "parentDynamicPanel":"ca5d131315414721bb80bc391671c1b9",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":100,
                      "y":72},
                    "size":{
                      "width":16,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"67ea0374cbc54061a3f414753b5ccab9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ca5d131315414721bb80bc391671c1b9",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "location":{
                          "x":100,
                          "y":72},
                        "size":{
                          "width":16,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/修改密码_1/u55.png"}}]}]}]}},
  "masters":{
    "c4f4574f84ac4b10b53e561ddcd8f2db":{
      "packageId":"c4f4574f84ac4b10b53e561ddcd8f2db",
      "type":"Axure:Master",
      "name":"alert",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[]}}},
  "objectPaths":{
    "3de9b726181949dbb0299f9377c54361":{
      "scriptId":"u0"},
    "9967453c36664684bca75575b2987fc6":{
      "scriptId":"u1"},
    "24c200271d0d4ef58798f91517d574f6":{
      "scriptId":"u2"},
    "44c8251392fb40e1b289d9054fd60346":{
      "scriptId":"u3"},
    "6ea68b56c2a64a68a3b879b8e6c1d1db":{
      "scriptId":"u4"},
    "4b6e8659eec14fd29a32afe098bb057f":{
      "scriptId":"u5"},
    "c18ebd45230747988ae1bc5aec630e45":{
      "scriptId":"u6"},
    "cd8e8887347245a19d87fd66f31f9153":{
      "scriptId":"u7"},
    "b1ace8676a5e405c9770445bfa15238f":{
      "scriptId":"u8"},
    "126278ee4a0a4a3fa628ad5f5149f279":{
      "scriptId":"u9"},
    "c899262190774538942ea24321a3ef65":{
      "scriptId":"u10"},
    "069f709635834d0ea7456d116879a0fc":{
      "scriptId":"u11"},
    "75a3a25a7e504637b6850db0d2de89b2":{
      "scriptId":"u12"},
    "6a6b7ba37ac648d4a74289a89391dfb8":{
      "scriptId":"u13"},
    "1eede98ad0e54347970cf3c127e93ae2":{
      "scriptId":"u14"},
    "8dfbef24649243f1a849b41dfb51a9ea":{
      "scriptId":"u15"},
    "6d1cb9765f8c428ea4de2401240723a0":{
      "scriptId":"u16"},
    "99e4a6d6bfc749e08c496925aa382872":{
      "scriptId":"u17"},
    "c21e5ab8b1bd4699a2feb0f59bd3a5d4":{
      "scriptId":"u18"},
    "03c627c8b9b4437ca2d8790d4905f351":{
      "scriptId":"u19"},
    "967cfe54653345b9a43b20e4e602480a":{
      "scriptId":"u20"},
    "fdf6c6bf37274c68aaeaf5751edaf85f":{
      "scriptId":"u21"},
    "536495c0f2194ad9b8114c335c248cc7":{
      "scriptId":"u22"},
    "059700cb44664c4499704b119b3c2dda":{
      "scriptId":"u23"},
    "2ce9effbac654fa3a1024e8430c48cf4":{
      "scriptId":"u24"},
    "398c01e4ec794ddb87a1e4c230f3b6e9":{
      "scriptId":"u25"},
    "c714520666d34f2a921bfa2759ba8452":{
      "scriptId":"u26"},
    "8f136119fd1147e9b8b7a627e8be671c":{
      "scriptId":"u27"},
    "b859a38f65c841cd8b74d16b30707746":{
      "scriptId":"u28"},
    "45d643072b7147fb81e8f2245e365d91":{
      "scriptId":"u29"},
    "48b0bcab40864fc1b6eeeacdcf2293e8":{
      "scriptId":"u30"},
    "4e9373f4848d4ed3bac5a8ee195fc682":{
      "scriptId":"u31"},
    "a4b43d30571245e29b0279a39db247d3":{
      "scriptId":"u32"},
    "7f5cfe6920d8430a90b9d8884e008d0b":{
      "scriptId":"u33"},
    "f0ddbf19dc404573b08e8cca15e2a7b4":{
      "scriptId":"u34"},
    "dad48de2124847758bd4da44456be0ad":{
      "scriptId":"u35"},
    "8bc4807b17334481b4c6097c860ef055":{
      "scriptId":"u36"},
    "25dbd35cdba44c73835c8e94513d8285":{
      "scriptId":"u37"},
    "43b76eb03d024524a712de46e63d0afa":{
      "scriptId":"u38"},
    "82841b1749ca4076bfe7507af0495632":{
      "scriptId":"u39"},
    "91412289265744579786a883d7aee46c":{
      "scriptId":"u40"},
    "c09d82e496ed42f69cbb7cc6bdfdea2f":{
      "scriptId":"u41"},
    "5ccac17e52a04f84a74c798ee700163a":{
      "scriptId":"u42"},
    "ca5d131315414721bb80bc391671c1b9":{
      "scriptId":"u43"},
    "a67281cae3de46a285b0ff4ca10e0ab1":{
      "scriptId":"u44"},
    "de92108cb516419990e614efcc2ef781":{
      "scriptId":"u45"},
    "f25a24561bd445a8bf136e58424a2b38":{
      "scriptId":"u46"},
    "08dc8d175d1542d490142b00186af8ee":{
      "scriptId":"u47"},
    "7e2791babd674fe8b0eb59e9b4115e04":{
      "scriptId":"u48"},
    "cced2182836a417ea3893c17b8e6205d":{
      "scriptId":"u49"},
    "22e4291e9e174f988f6013ad2d4e6945":{
      "scriptId":"u50"},
    "d27507abc7814d10ad34a1712c6ce7a3":{
      "scriptId":"u51"},
    "5febc04fbdf84a58a1e655297f21e82e":{
      "scriptId":"u52"},
    "a984ad0e34cf438394525252989f8439":{
      "scriptId":"u53"},
    "1c2fb3da9512428baa5f447ff74e4851":{
      "scriptId":"u54"},
    "d753d5b42bee4fe4af00ec20be450075":{
      "scriptId":"u55"},
    "67ea0374cbc54061a3f414753b5ccab9":{
      "scriptId":"u56"}}});