$axure.loadCurrentPage({
  "url":"添加kab公告.html",
  "generationDate":new Date(1383013851130.23),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"5db1e20388524deca81d9dcc71821d75",
    "type":"Axure:Page",
    "name":"添加KAB公告",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c60d0b20ccf74444b3f9cc982d672858",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":170,
              "height":51}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"80984ef1d00c49399d6a8d17352eb55b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":170,
                  "height":51}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改密码_1/u0.jpg"}},
{
          "id":"1445bb1b19564d11bfa95b951f74832d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":133},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d21000f9c1b0433a8475a91f44f7d499",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":48,
                  "y":133},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"33b8bd2237aa4c189a2db77e388204b8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":598,
              "y":4},
            "size":{
              "width":148,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1293eddbc134cdf831b469ed8ad00a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":598,
                  "y":4},
                "size":{
                  "width":148,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a35b98c7741c4e858b350befb62ca314",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":903,
              "y":4},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b82c0b6f03d646798af37fc76138510b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":903,
                  "y":4},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 后台登录",
                      "target":{
                        "targetType":"page",
                        "url":"后台登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b1848780c7e54078839c049d308a6839",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":828,
              "y":4},
            "size":{
              "width":88,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bd2648f8cee403db79837a84c9ac00c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":828,
                  "y":4},
                "size":{
                  "width":88,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 修改密码",
                      "target":{
                        "targetType":"page",
                        "url":"修改密码_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"06005e63de5847bbb28717657defb48d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":756,
              "y":4},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8dadd6d4dfd44ff4a5bd6ea7681204fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":756,
                  "y":4},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c43e79d51f144515aab51862af375255",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":79,
              "y":177},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d454c12326ad45979aad5cd57b80cb79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":79,
                  "y":177},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d389c12d214e415693fb71564862a720",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":145},
            "size":{
              "width":946,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF949494}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/修改密码_1/u24_line.png"}},
{
          "id":"b813678148ab4b769bd796b17fd2fa1d",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":143,
              "y":173},
            "size":{
              "width":477,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"71e1f102007d46878eebd0a642818a44",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":143,
              "y":368},
            "size":{
              "width":477,
              "height":210}},
          "adaptiveStyles":{
}},
{
          "id":"4589a10dcbf94aa3b62c431436d090fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":79,
              "y":348},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69f36baa403f42e28ad0db3d6b146c96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":79,
                  "y":348},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"86b5bc2bff33457984d84679ad2ad67f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":143,
              "y":343},
            "size":{
              "width":361,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4fca03aa552b42f6932c9fefd73dafbf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":143,
                  "y":343},
                "size":{
                  "width":361,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加新闻/u41.png"}},
{
          "id":"9ce63d832f93415aba8e831903d250f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":77,
              "y":228},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c261da604f24acda20d918f1d13372f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":77,
                  "y":228},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3a94a93b072d490a8e0c0909143f9bb6",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":143,
              "y":224},
            "size":{
              "width":190,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"49645c08f7334c60bab6e2819bfd0fe7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF87DB01}}},
            "fill":{
              "fillType":"solid",
              "color":0xFF6AB30C},
            "location":{
              "x":143,
              "y":624},
            "size":{
              "width":81,
              "height":26},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10bb6b88934f4551a7c64a17944ab824",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF87DB01}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF6AB30C},
                "location":{
                  "x":143,
                  "y":624},
                "size":{
                  "width":81,
                  "height":26},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 alert",
                      "objectsToFades":[{
                          "objectPath":["e233490c585a4672b23262f38934f761"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/修改个人资料/u102.png",
            "mouseOver~":"images/修改个人资料/u102_mouseOver.png"}},
{
          "id":"d527e39ea0644173a80d9ffda82cf7d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF87DB01}}},
            "fill":{
              "fillType":"solid",
              "color":0xFF6AB30C},
            "location":{
              "x":262,
              "y":624},
            "size":{
              "width":81,
              "height":26},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16cf34f84ccd4e70a636c3451dffcd5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF87DB01}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF6AB30C},
                "location":{
                  "x":262,
                  "y":624},
                "size":{
                  "width":81,
                  "height":26},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 KAB公告管理",
                      "target":{
                        "targetType":"page",
                        "url":"kab公告管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/修改个人资料/u102.png",
            "mouseOver~":"images/修改个人资料/u102_mouseOver.png"}},
{
          "id":"e233490c585a4672b23262f38934f761",
          "label":"alert",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":380,
              "y":276},
            "size":{
              "width":320,
              "height":190},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"90ae3419fe3d4306be1fd3d6b9db9804",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"192bedbaf3f541438857a37882aaccff",
                  "label":"",
                  "parentDynamicPanel":"e233490c585a4672b23262f38934f761",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":280,
                      "height":160}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"de431b86f8714abfb3c11d0619972555",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e233490c585a4672b23262f38934f761",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":280,
                          "height":160}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/修改密码_1/u44.png"}},
{
                  "id":"931c669242814e27aa4fa8cfb7d38a65",
                  "label":"",
                  "parentDynamicPanel":"e233490c585a4672b23262f38934f761",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "location":{
                      "x":42,
                      "y":9},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"56c43433ce754655996bd47b152977f5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e233490c585a4672b23262f38934f761",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontWeight":"700",
                        "location":{
                          "x":42,
                          "y":9},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"452a2bf159904d5f91c82f1ce76b6ee8",
                  "label":"",
                  "parentDynamicPanel":"e233490c585a4672b23262f38934f761",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":26},
                    "size":{
                      "width":280,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/修改密码_1/u48_line.png"}},
{
                  "id":"feb0c0f0e8994d8c90357fa311aacb3e",
                  "label":"",
                  "parentDynamicPanel":"e233490c585a4672b23262f38934f761",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":101,
                      "y":120},
                    "size":{
                      "width":78,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5151edfadf4749fe8cc2e1f0177846ca",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e233490c585a4672b23262f38934f761",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4},
                        "location":{
                          "x":101,
                          "y":120},
                        "size":{
                          "width":78,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 alert",
                              "objectsToFades":[{
                                  "objectPath":["e233490c585a4672b23262f38934f761"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]},
{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 KAB公告管理",
                              "target":{
                                "targetType":"page",
                                "url":"kab公告管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/修改密码_1/u49.png"}},
{
                  "id":"547566a6b2f54104a47ff06277fe986c",
                  "label":"",
                  "parentDynamicPanel":"e233490c585a4672b23262f38934f761",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":16,
                      "y":9},
                    "size":{
                      "width":16,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"dfd81f004f1443268510049460acbc78",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e233490c585a4672b23262f38934f761",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "location":{
                          "x":16,
                          "y":9},
                        "size":{
                          "width":16,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/修改密码_1/u51.png"}},
{
                  "id":"9cdf9420bee9472e9f72c236db8cbca3",
                  "label":"",
                  "parentDynamicPanel":"e233490c585a4672b23262f38934f761",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":126,
                      "y":72},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"30006162fcd74ffb9f53018d41e7c558",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e233490c585a4672b23262f38934f761",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":126,
                          "y":72},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"326daffdbd534ba288813e089e1ad2f7",
                  "label":"",
                  "parentDynamicPanel":"e233490c585a4672b23262f38934f761",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":100,
                      "y":72},
                    "size":{
                      "width":16,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"87d255644ab740a38b1016e656a8dc7a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e233490c585a4672b23262f38934f761",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "location":{
                          "x":100,
                          "y":72},
                        "size":{
                          "width":16,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/修改密码_1/u55.png"}}]}]},
{
          "id":"71fd6b8a9aca4f8d99110bdc75f2d00d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":129},
            "size":{
              "width":80,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b7b5e71deaa43d5824f9c72022baa6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":129},
                "size":{
                  "width":80,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 KAB公告管理",
                      "target":{
                        "targetType":"page",
                        "url":"kab公告管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6011ad3d37df4080bd2012507f27deda",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":129},
            "size":{
              "width":97,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c191d03774ff4adf889857afecceab51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":120,
                  "y":129},
                "size":{
                  "width":97,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1721cd15b6904f2cbeaa729d180c34b6",
          "label":"导航",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":50},
            "size":{
              "width":716,
              "height":129}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"fea19f45b79843c5bfdf790d71bad864",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"e1518ca1335f4165b2d8f10516eef8e6",
                  "label":"",
                  "parentDynamicPanel":"1721cd15b6904f2cbeaa729d180c34b6",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":90,
                      "y":7},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"50cf4aad1aaf41e196790b97d44a240a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1721cd15b6904f2cbeaa729d180c34b6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":90,
                          "y":7},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 新闻管理",
                              "target":{
                                "targetType":"page",
                                "url":"新闻管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"5ff639511cfe4e789a3036e0f33fdc87",
                  "label":"",
                  "parentDynamicPanel":"1721cd15b6904f2cbeaa729d180c34b6",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":190,
                      "y":7},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fe5f41959b4e414aa93261fa22e6551d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1721cd15b6904f2cbeaa729d180c34b6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":190,
                          "y":7},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 KAB概况管理",
                              "target":{
                                "targetType":"page",
                                "url":"kab概况管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"794d801dab89423ea3c0cada54f75368",
                  "label":"",
                  "parentDynamicPanel":"1721cd15b6904f2cbeaa729d180c34b6",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":407,
                      "y":7},
                    "size":{
                      "width":79,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"eada9a3da1ab401aa3a6ece7e505f616",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1721cd15b6904f2cbeaa729d180c34b6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":407,
                          "y":7},
                        "size":{
                          "width":79,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 班级管理",
                              "target":{
                                "targetType":"page",
                                "url":"班级管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"bc289b3a50a146c48fd1408c286d9255",
                  "label":"",
                  "parentDynamicPanel":"1721cd15b6904f2cbeaa729d180c34b6",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":542,
                      "y":7},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1985f3fad6bf4ca6b55d22e5896a7a15",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1721cd15b6904f2cbeaa729d180c34b6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":542,
                          "y":7},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 用户管理",
                              "target":{
                                "targetType":"page",
                                "url":"用户管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"aaa678129fe44bc8a09acfbdaa58a559",
                  "label":"",
                  "parentDynamicPanel":"1721cd15b6904f2cbeaa729d180c34b6",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":637,
                      "y":7},
                    "size":{
                      "width":79,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7a2f25600fdc40a690f586d7bd22c0d6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1721cd15b6904f2cbeaa729d180c34b6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":637,
                          "y":7},
                        "size":{
                          "width":79,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 系统参数配置",
                              "target":{
                                "targetType":"page",
                                "url":"系统参数配置.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"6ee9aee39b714ae184e34adda1077dfd",
                  "label":"",
                  "parentDynamicPanel":"1721cd15b6904f2cbeaa729d180c34b6",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":22},
                    "size":{
                      "width":1000,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/修改密码_1/u21_line.png"}},
{
                  "id":"d208ada9e81a4fa7b5eb9a5736dd3971",
                  "label":"",
                  "parentDynamicPanel":"1721cd15b6904f2cbeaa729d180c34b6",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF5E5E5E,
                      "opacity":1},
                    "location":{
                      "x":276,
                      "y":1},
                    "size":{
                      "width":97,
                      "height":27},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e9ea0f1ab99349ed98d2a5fdc6f73300",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1721cd15b6904f2cbeaa729d180c34b6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF5E5E5E,
                          "opacity":1},
                        "location":{
                          "x":276,
                          "y":1},
                        "size":{
                          "width":97,
                          "height":27},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 KAB公告管理",
                              "target":{
                                "targetType":"page",
                                "url":"kab公告管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/新闻管理/u12.png"}}]}]},
{
          "id":"dfdf1821760644329feff416fb5c089f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":77,
              "y":290},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f5a56c01b9249999f5064a3e7afcdab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":77,
                  "y":290},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3d8e56e57c7147ebad43260530f7e780",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":153,
              "y":287},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "c60d0b20ccf74444b3f9cc982d672858":{
      "scriptId":"u0"},
    "80984ef1d00c49399d6a8d17352eb55b":{
      "scriptId":"u1"},
    "1445bb1b19564d11bfa95b951f74832d":{
      "scriptId":"u2"},
    "d21000f9c1b0433a8475a91f44f7d499":{
      "scriptId":"u3"},
    "33b8bd2237aa4c189a2db77e388204b8":{
      "scriptId":"u4"},
    "f1293eddbc134cdf831b469ed8ad00a0":{
      "scriptId":"u5"},
    "a35b98c7741c4e858b350befb62ca314":{
      "scriptId":"u6"},
    "b82c0b6f03d646798af37fc76138510b":{
      "scriptId":"u7"},
    "b1848780c7e54078839c049d308a6839":{
      "scriptId":"u8"},
    "4bd2648f8cee403db79837a84c9ac00c":{
      "scriptId":"u9"},
    "06005e63de5847bbb28717657defb48d":{
      "scriptId":"u10"},
    "8dadd6d4dfd44ff4a5bd6ea7681204fd":{
      "scriptId":"u11"},
    "c43e79d51f144515aab51862af375255":{
      "scriptId":"u12"},
    "d454c12326ad45979aad5cd57b80cb79":{
      "scriptId":"u13"},
    "d389c12d214e415693fb71564862a720":{
      "scriptId":"u14"},
    "b813678148ab4b769bd796b17fd2fa1d":{
      "scriptId":"u15"},
    "71e1f102007d46878eebd0a642818a44":{
      "scriptId":"u16"},
    "4589a10dcbf94aa3b62c431436d090fa":{
      "scriptId":"u17"},
    "69f36baa403f42e28ad0db3d6b146c96":{
      "scriptId":"u18"},
    "86b5bc2bff33457984d84679ad2ad67f":{
      "scriptId":"u19"},
    "4fca03aa552b42f6932c9fefd73dafbf":{
      "scriptId":"u20"},
    "9ce63d832f93415aba8e831903d250f2":{
      "scriptId":"u21"},
    "6c261da604f24acda20d918f1d13372f":{
      "scriptId":"u22"},
    "3a94a93b072d490a8e0c0909143f9bb6":{
      "scriptId":"u23"},
    "49645c08f7334c60bab6e2819bfd0fe7":{
      "scriptId":"u24"},
    "10bb6b88934f4551a7c64a17944ab824":{
      "scriptId":"u25"},
    "d527e39ea0644173a80d9ffda82cf7d9":{
      "scriptId":"u26"},
    "16cf34f84ccd4e70a636c3451dffcd5e":{
      "scriptId":"u27"},
    "e233490c585a4672b23262f38934f761":{
      "scriptId":"u28"},
    "192bedbaf3f541438857a37882aaccff":{
      "scriptId":"u29"},
    "de431b86f8714abfb3c11d0619972555":{
      "scriptId":"u30"},
    "931c669242814e27aa4fa8cfb7d38a65":{
      "scriptId":"u31"},
    "56c43433ce754655996bd47b152977f5":{
      "scriptId":"u32"},
    "452a2bf159904d5f91c82f1ce76b6ee8":{
      "scriptId":"u33"},
    "feb0c0f0e8994d8c90357fa311aacb3e":{
      "scriptId":"u34"},
    "5151edfadf4749fe8cc2e1f0177846ca":{
      "scriptId":"u35"},
    "547566a6b2f54104a47ff06277fe986c":{
      "scriptId":"u36"},
    "dfd81f004f1443268510049460acbc78":{
      "scriptId":"u37"},
    "9cdf9420bee9472e9f72c236db8cbca3":{
      "scriptId":"u38"},
    "30006162fcd74ffb9f53018d41e7c558":{
      "scriptId":"u39"},
    "326daffdbd534ba288813e089e1ad2f7":{
      "scriptId":"u40"},
    "87d255644ab740a38b1016e656a8dc7a":{
      "scriptId":"u41"},
    "71fd6b8a9aca4f8d99110bdc75f2d00d":{
      "scriptId":"u42"},
    "7b7b5e71deaa43d5824f9c72022baa6e":{
      "scriptId":"u43"},
    "6011ad3d37df4080bd2012507f27deda":{
      "scriptId":"u44"},
    "c191d03774ff4adf889857afecceab51":{
      "scriptId":"u45"},
    "1721cd15b6904f2cbeaa729d180c34b6":{
      "scriptId":"u46"},
    "e1518ca1335f4165b2d8f10516eef8e6":{
      "scriptId":"u47"},
    "50cf4aad1aaf41e196790b97d44a240a":{
      "scriptId":"u48"},
    "5ff639511cfe4e789a3036e0f33fdc87":{
      "scriptId":"u49"},
    "fe5f41959b4e414aa93261fa22e6551d":{
      "scriptId":"u50"},
    "794d801dab89423ea3c0cada54f75368":{
      "scriptId":"u51"},
    "eada9a3da1ab401aa3a6ece7e505f616":{
      "scriptId":"u52"},
    "bc289b3a50a146c48fd1408c286d9255":{
      "scriptId":"u53"},
    "1985f3fad6bf4ca6b55d22e5896a7a15":{
      "scriptId":"u54"},
    "aaa678129fe44bc8a09acfbdaa58a559":{
      "scriptId":"u55"},
    "7a2f25600fdc40a690f586d7bd22c0d6":{
      "scriptId":"u56"},
    "6ee9aee39b714ae184e34adda1077dfd":{
      "scriptId":"u57"},
    "d208ada9e81a4fa7b5eb9a5736dd3971":{
      "scriptId":"u58"},
    "e9ea0f1ab99349ed98d2a5fdc6f73300":{
      "scriptId":"u59"},
    "dfdf1821760644329feff416fb5c089f":{
      "scriptId":"u60"},
    "9f5a56c01b9249999f5064a3e7afcdab":{
      "scriptId":"u61"},
    "3d8e56e57c7147ebad43260530f7e780":{
      "scriptId":"u62"}}});