$axure.loadCurrentPage({
  "url":"添加创业资讯.html",
  "generationDate":new Date(1383013849987.17),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0c962752b2d048a6ae6c39efa513ff33",
    "type":"Axure:Page",
    "name":"添加创业资讯",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c60d0b20ccf74444b3f9cc982d672858",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":170,
              "height":51}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"80984ef1d00c49399d6a8d17352eb55b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":170,
                  "height":51}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改密码_1/u0.jpg"}},
{
          "id":"1445bb1b19564d11bfa95b951f74832d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":133},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d21000f9c1b0433a8475a91f44f7d499",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":48,
                  "y":133},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"33b8bd2237aa4c189a2db77e388204b8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":598,
              "y":4},
            "size":{
              "width":148,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1293eddbc134cdf831b469ed8ad00a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":598,
                  "y":4},
                "size":{
                  "width":148,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a35b98c7741c4e858b350befb62ca314",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":903,
              "y":4},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b82c0b6f03d646798af37fc76138510b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":903,
                  "y":4},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 后台登录",
                      "target":{
                        "targetType":"page",
                        "url":"后台登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b1848780c7e54078839c049d308a6839",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":828,
              "y":4},
            "size":{
              "width":88,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bd2648f8cee403db79837a84c9ac00c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":828,
                  "y":4},
                "size":{
                  "width":88,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 修改密码",
                      "target":{
                        "targetType":"page",
                        "url":"修改密码_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"06005e63de5847bbb28717657defb48d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":756,
              "y":4},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8dadd6d4dfd44ff4a5bd6ea7681204fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":756,
                  "y":4},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c43e79d51f144515aab51862af375255",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":79,
              "y":177},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d454c12326ad45979aad5cd57b80cb79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":79,
                  "y":177},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d389c12d214e415693fb71564862a720",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":145},
            "size":{
              "width":946,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF949494}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/修改密码_1/u24_line.png"}},
{
          "id":"b813678148ab4b769bd796b17fd2fa1d",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":143,
              "y":173},
            "size":{
              "width":477,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"71e1f102007d46878eebd0a642818a44",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":143,
              "y":368},
            "size":{
              "width":477,
              "height":210}},
          "adaptiveStyles":{
}},
{
          "id":"4589a10dcbf94aa3b62c431436d090fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":79,
              "y":348},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69f36baa403f42e28ad0db3d6b146c96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":79,
                  "y":348},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6555b200261e428dba7f988e2a727004",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":53,
              "y":301},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9a1df78fa244d50b2757aa7713fbb6a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":53,
                  "y":301},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"86b5bc2bff33457984d84679ad2ad67f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":143,
              "y":343},
            "size":{
              "width":361,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4fca03aa552b42f6932c9fefd73dafbf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":143,
                  "y":343},
                "size":{
                  "width":361,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加新闻/u41.png"}},
{
          "id":"3b5b9f2389014f68857b652d6700cefd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":72,
              "y":262},
            "size":{
              "width":58,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cce7f94d8f194dee9b8e7c0e738dc063",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":72,
                  "y":262},
                "size":{
                  "width":58,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9ce63d832f93415aba8e831903d250f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":77,
              "y":222},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c261da604f24acda20d918f1d13372f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":77,
                  "y":222},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3a94a93b072d490a8e0c0909143f9bb6",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":143,
              "y":218},
            "size":{
              "width":190,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"92ae211f57514dbba08156def35ab5cb",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":143,
              "y":262},
            "size":{
              "width":187,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"49645c08f7334c60bab6e2819bfd0fe7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF87DB01}}},
            "fill":{
              "fillType":"solid",
              "color":0xFF6AB30C},
            "location":{
              "x":143,
              "y":624},
            "size":{
              "width":81,
              "height":26},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10bb6b88934f4551a7c64a17944ab824",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF87DB01}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF6AB30C},
                "location":{
                  "x":143,
                  "y":624},
                "size":{
                  "width":81,
                  "height":26},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 alert",
                      "objectsToFades":[{
                          "objectPath":["e233490c585a4672b23262f38934f761"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/修改个人资料/u102.png",
            "mouseOver~":"images/修改个人资料/u102_mouseOver.png"}},
{
          "id":"d527e39ea0644173a80d9ffda82cf7d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF87DB01}}},
            "fill":{
              "fillType":"solid",
              "color":0xFF6AB30C},
            "location":{
              "x":262,
              "y":624},
            "size":{
              "width":81,
              "height":26},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16cf34f84ccd4e70a636c3451dffcd5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF87DB01}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF6AB30C},
                "location":{
                  "x":262,
                  "y":624},
                "size":{
                  "width":81,
                  "height":26},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 创业资讯管理",
                      "target":{
                        "targetType":"page",
                        "url":"创业资讯管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/修改个人资料/u102.png",
            "mouseOver~":"images/修改个人资料/u102_mouseOver.png"}},
{
          "id":"e233490c585a4672b23262f38934f761",
          "label":"alert",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":380,
              "y":276},
            "size":{
              "width":320,
              "height":190},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"90ae3419fe3d4306be1fd3d6b9db9804",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"192bedbaf3f541438857a37882aaccff",
                  "label":"",
                  "parentDynamicPanel":"e233490c585a4672b23262f38934f761",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":280,
                      "height":160}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"de431b86f8714abfb3c11d0619972555",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e233490c585a4672b23262f38934f761",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":280,
                          "height":160}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/修改密码_1/u44.png"}},
{
                  "id":"931c669242814e27aa4fa8cfb7d38a65",
                  "label":"",
                  "parentDynamicPanel":"e233490c585a4672b23262f38934f761",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "location":{
                      "x":42,
                      "y":9},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"56c43433ce754655996bd47b152977f5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e233490c585a4672b23262f38934f761",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontWeight":"700",
                        "location":{
                          "x":42,
                          "y":9},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"452a2bf159904d5f91c82f1ce76b6ee8",
                  "label":"",
                  "parentDynamicPanel":"e233490c585a4672b23262f38934f761",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":26},
                    "size":{
                      "width":280,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/修改密码_1/u48_line.png"}},
{
                  "id":"feb0c0f0e8994d8c90357fa311aacb3e",
                  "label":"",
                  "parentDynamicPanel":"e233490c585a4672b23262f38934f761",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":101,
                      "y":120},
                    "size":{
                      "width":78,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5151edfadf4749fe8cc2e1f0177846ca",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e233490c585a4672b23262f38934f761",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4},
                        "location":{
                          "x":101,
                          "y":120},
                        "size":{
                          "width":78,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 alert",
                              "objectsToFades":[{
                                  "objectPath":["e233490c585a4672b23262f38934f761"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]},
{
                              "action":"fadeWidget",
                              "description":"显示/隐藏部件",
                              "objectsToFades":[]},
{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 创业资讯管理",
                              "target":{
                                "targetType":"page",
                                "url":"创业资讯管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/修改密码_1/u49.png"}},
{
                  "id":"547566a6b2f54104a47ff06277fe986c",
                  "label":"",
                  "parentDynamicPanel":"e233490c585a4672b23262f38934f761",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":16,
                      "y":9},
                    "size":{
                      "width":16,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"dfd81f004f1443268510049460acbc78",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e233490c585a4672b23262f38934f761",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "location":{
                          "x":16,
                          "y":9},
                        "size":{
                          "width":16,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/修改密码_1/u51.png"}},
{
                  "id":"9cdf9420bee9472e9f72c236db8cbca3",
                  "label":"",
                  "parentDynamicPanel":"e233490c585a4672b23262f38934f761",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":126,
                      "y":72},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"30006162fcd74ffb9f53018d41e7c558",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e233490c585a4672b23262f38934f761",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":126,
                          "y":72},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"326daffdbd534ba288813e089e1ad2f7",
                  "label":"",
                  "parentDynamicPanel":"e233490c585a4672b23262f38934f761",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":100,
                      "y":72},
                    "size":{
                      "width":16,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"87d255644ab740a38b1016e656a8dc7a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e233490c585a4672b23262f38934f761",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "location":{
                          "x":100,
                          "y":72},
                        "size":{
                          "width":16,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/修改密码_1/u55.png"}}]}]},
{
          "id":"0020eb2f2043428cb288132afa685214",
          "label":"导航",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":50},
            "size":{
              "width":716,
              "height":129}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"63f70123aed74e6f84b5af902204de46",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"c1b42a6c647e4efc8c77fb998c3c1d62",
                  "label":"",
                  "parentDynamicPanel":"0020eb2f2043428cb288132afa685214",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":90,
                      "y":7},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d20cef65babb41eebdb9074b6e78665c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0020eb2f2043428cb288132afa685214",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":90,
                          "y":7},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 新闻管理",
                              "target":{
                                "targetType":"page",
                                "url":"新闻管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"5c5c0f403b3f417c9d8ac76a87220c75",
                  "label":"",
                  "parentDynamicPanel":"0020eb2f2043428cb288132afa685214",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":300,
                      "y":7},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"24e3403472c14801b17c7fdc5b48d8f8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0020eb2f2043428cb288132afa685214",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":300,
                          "y":7},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 KAB公告管理",
                              "target":{
                                "targetType":"page",
                                "url":"kab公告管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"ef0b4766afc9441896144f8e2402a414",
                  "label":"",
                  "parentDynamicPanel":"0020eb2f2043428cb288132afa685214",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":407,
                      "y":7},
                    "size":{
                      "width":79,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d7d7b7fc145e4df19d96f1e834e32582",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0020eb2f2043428cb288132afa685214",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":407,
                          "y":7},
                        "size":{
                          "width":79,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 班级管理",
                              "target":{
                                "targetType":"page",
                                "url":"班级管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"536edc3fc01245b5a1b9629ade9af686",
                  "label":"",
                  "parentDynamicPanel":"0020eb2f2043428cb288132afa685214",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":542,
                      "y":7},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"498d0a80eeff428f848836e408b12225",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0020eb2f2043428cb288132afa685214",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":542,
                          "y":7},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 用户管理",
                              "target":{
                                "targetType":"page",
                                "url":"用户管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"665a4e782cb54a878921594ad404740e",
                  "label":"",
                  "parentDynamicPanel":"0020eb2f2043428cb288132afa685214",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":637,
                      "y":7},
                    "size":{
                      "width":79,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1f25402a2d0d4c4593f253f9f3232c2d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0020eb2f2043428cb288132afa685214",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":637,
                          "y":7},
                        "size":{
                          "width":79,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 系统参数配置",
                              "target":{
                                "targetType":"page",
                                "url":"系统参数配置.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c2d6b282461249d89cda4755c98570eb",
                  "label":"",
                  "parentDynamicPanel":"0020eb2f2043428cb288132afa685214",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":22},
                    "size":{
                      "width":1000,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/修改密码_1/u21_line.png"}},
{
                  "id":"9d7165d8b63844589b09547126debce2",
                  "label":"",
                  "parentDynamicPanel":"0020eb2f2043428cb288132afa685214",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF5E5E5E,
                      "opacity":1},
                    "location":{
                      "x":173,
                      "y":1},
                    "size":{
                      "width":97,
                      "height":27},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ba474bd91c3b44429ada448acf0b65f4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0020eb2f2043428cb288132afa685214",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF5E5E5E,
                          "opacity":1},
                        "location":{
                          "x":173,
                          "y":1},
                        "size":{
                          "width":97,
                          "height":27},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onMouseOut":{
                      "description":"OnMouseOut",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 ",
                              "objectsToFades":[]}]}]}},
                  "images":{
                    "normal~":"images/新闻管理/u12.png"}},
{
                  "id":"8ffc03c9698a408696cc6ebafe68de76",
                  "label":"",
                  "parentDynamicPanel":"0020eb2f2043428cb288132afa685214",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":173,
                      "y":38},
                    "size":{
                      "width":80,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1a6b7b8e234c402e883ff350f0cc5b66",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0020eb2f2043428cb288132afa685214",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":173,
                          "y":38},
                        "size":{
                          "width":80,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 KAB概况管理",
                              "target":{
                                "targetType":"page",
                                "url":"kab概况管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"636fb0f49455433d8ceaf951b9f12fe4",
                  "label":"",
                  "parentDynamicPanel":"0020eb2f2043428cb288132afa685214",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "location":{
                      "x":280,
                      "y":38},
                    "size":{
                      "width":110,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7f9c75615d7e427098c9ecf52a7d1dd0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0020eb2f2043428cb288132afa685214",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontWeight":"700",
                        "location":{
                          "x":280,
                          "y":38},
                        "size":{
                          "width":110,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 创业资讯管理",
                              "target":{
                                "targetType":"page",
                                "url":"创业资讯管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f1bb10fb0c4d4d24b8b96336dac2df50",
                  "label":"",
                  "parentDynamicPanel":"0020eb2f2043428cb288132afa685214",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":410,
                      "y":38},
                    "size":{
                      "width":137,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4d8734b90c974e55a4c0a4c1a7bec593",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0020eb2f2043428cb288132afa685214",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":410,
                          "y":38},
                        "size":{
                          "width":137,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 KAB课程介绍管理",
                              "target":{
                                "targetType":"page",
                                "url":"kab课程介绍管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"54c6c53d8ccd4d6a84c22162982ad5e2",
                  "label":"",
                  "parentDynamicPanel":"0020eb2f2043428cb288132afa685214",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":570,
                      "y":38},
                    "size":{
                      "width":84,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"eee367e472994facb31962c79b1861b2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0020eb2f2043428cb288132afa685214",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":570,
                          "y":38},
                        "size":{
                          "width":84,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 单页管理",
                              "target":{
                                "targetType":"page",
                                "url":"单页管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"d6d0634f98e54e4ea42e524c442c3f44",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":31,
              "y":131},
            "size":{
              "width":82,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0dffaf3bd73d4cbe878d4a3f8fe272bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":31,
                  "y":131},
                "size":{
                  "width":82,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"71fd6b8a9aca4f8d99110bdc75f2d00d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":115,
              "y":131},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b7b5e71deaa43d5824f9c72022baa6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":115,
                  "y":131},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 创业资讯管理",
                      "target":{
                        "targetType":"page",
                        "url":"创业资讯管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8876211a636d4ff29d24ea30a48499bd",
          "label":"1",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":143,
              "y":301},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f0f0a664c02406e8939f0b69b041fd0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":143,
                  "y":301},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 1 等于 &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["8876211a636d4ff29d24ea30a48499bd"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}},
{
                      "action":"setFunction",
                      "description":"设置 被选中的 2 等于 &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["884be67989cc4b6dbd09c200c121eb46"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}}},
{
          "id":"884be67989cc4b6dbd09c200c121eb46",
          "label":"2",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":253,
              "y":301},
            "size":{
              "width":47,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f57404e65e0d4d10b4bff63133fb250b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":253,
                  "y":301},
                "size":{
                  "width":47,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 2 等于 &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["884be67989cc4b6dbd09c200c121eb46"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}},
{
                      "action":"setFunction",
                      "description":"设置 被选中的 1 等于 &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["8876211a636d4ff29d24ea30a48499bd"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}}},
{
          "id":"54c7f800643748538925fea3eccdfb92",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":131},
            "size":{
              "width":96,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cbea5f1c64464125aad7c0c07cc9b1b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":131},
                "size":{
                  "width":96,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "c60d0b20ccf74444b3f9cc982d672858":{
      "scriptId":"u0"},
    "80984ef1d00c49399d6a8d17352eb55b":{
      "scriptId":"u1"},
    "1445bb1b19564d11bfa95b951f74832d":{
      "scriptId":"u2"},
    "d21000f9c1b0433a8475a91f44f7d499":{
      "scriptId":"u3"},
    "33b8bd2237aa4c189a2db77e388204b8":{
      "scriptId":"u4"},
    "f1293eddbc134cdf831b469ed8ad00a0":{
      "scriptId":"u5"},
    "a35b98c7741c4e858b350befb62ca314":{
      "scriptId":"u6"},
    "b82c0b6f03d646798af37fc76138510b":{
      "scriptId":"u7"},
    "b1848780c7e54078839c049d308a6839":{
      "scriptId":"u8"},
    "4bd2648f8cee403db79837a84c9ac00c":{
      "scriptId":"u9"},
    "06005e63de5847bbb28717657defb48d":{
      "scriptId":"u10"},
    "8dadd6d4dfd44ff4a5bd6ea7681204fd":{
      "scriptId":"u11"},
    "c43e79d51f144515aab51862af375255":{
      "scriptId":"u12"},
    "d454c12326ad45979aad5cd57b80cb79":{
      "scriptId":"u13"},
    "d389c12d214e415693fb71564862a720":{
      "scriptId":"u14"},
    "b813678148ab4b769bd796b17fd2fa1d":{
      "scriptId":"u15"},
    "71e1f102007d46878eebd0a642818a44":{
      "scriptId":"u16"},
    "4589a10dcbf94aa3b62c431436d090fa":{
      "scriptId":"u17"},
    "69f36baa403f42e28ad0db3d6b146c96":{
      "scriptId":"u18"},
    "6555b200261e428dba7f988e2a727004":{
      "scriptId":"u19"},
    "e9a1df78fa244d50b2757aa7713fbb6a":{
      "scriptId":"u20"},
    "86b5bc2bff33457984d84679ad2ad67f":{
      "scriptId":"u21"},
    "4fca03aa552b42f6932c9fefd73dafbf":{
      "scriptId":"u22"},
    "3b5b9f2389014f68857b652d6700cefd":{
      "scriptId":"u23"},
    "cce7f94d8f194dee9b8e7c0e738dc063":{
      "scriptId":"u24"},
    "9ce63d832f93415aba8e831903d250f2":{
      "scriptId":"u25"},
    "6c261da604f24acda20d918f1d13372f":{
      "scriptId":"u26"},
    "3a94a93b072d490a8e0c0909143f9bb6":{
      "scriptId":"u27"},
    "92ae211f57514dbba08156def35ab5cb":{
      "scriptId":"u28"},
    "49645c08f7334c60bab6e2819bfd0fe7":{
      "scriptId":"u29"},
    "10bb6b88934f4551a7c64a17944ab824":{
      "scriptId":"u30"},
    "d527e39ea0644173a80d9ffda82cf7d9":{
      "scriptId":"u31"},
    "16cf34f84ccd4e70a636c3451dffcd5e":{
      "scriptId":"u32"},
    "e233490c585a4672b23262f38934f761":{
      "scriptId":"u33"},
    "192bedbaf3f541438857a37882aaccff":{
      "scriptId":"u34"},
    "de431b86f8714abfb3c11d0619972555":{
      "scriptId":"u35"},
    "931c669242814e27aa4fa8cfb7d38a65":{
      "scriptId":"u36"},
    "56c43433ce754655996bd47b152977f5":{
      "scriptId":"u37"},
    "452a2bf159904d5f91c82f1ce76b6ee8":{
      "scriptId":"u38"},
    "feb0c0f0e8994d8c90357fa311aacb3e":{
      "scriptId":"u39"},
    "5151edfadf4749fe8cc2e1f0177846ca":{
      "scriptId":"u40"},
    "547566a6b2f54104a47ff06277fe986c":{
      "scriptId":"u41"},
    "dfd81f004f1443268510049460acbc78":{
      "scriptId":"u42"},
    "9cdf9420bee9472e9f72c236db8cbca3":{
      "scriptId":"u43"},
    "30006162fcd74ffb9f53018d41e7c558":{
      "scriptId":"u44"},
    "326daffdbd534ba288813e089e1ad2f7":{
      "scriptId":"u45"},
    "87d255644ab740a38b1016e656a8dc7a":{
      "scriptId":"u46"},
    "0020eb2f2043428cb288132afa685214":{
      "scriptId":"u47"},
    "c1b42a6c647e4efc8c77fb998c3c1d62":{
      "scriptId":"u48"},
    "d20cef65babb41eebdb9074b6e78665c":{
      "scriptId":"u49"},
    "5c5c0f403b3f417c9d8ac76a87220c75":{
      "scriptId":"u50"},
    "24e3403472c14801b17c7fdc5b48d8f8":{
      "scriptId":"u51"},
    "ef0b4766afc9441896144f8e2402a414":{
      "scriptId":"u52"},
    "d7d7b7fc145e4df19d96f1e834e32582":{
      "scriptId":"u53"},
    "536edc3fc01245b5a1b9629ade9af686":{
      "scriptId":"u54"},
    "498d0a80eeff428f848836e408b12225":{
      "scriptId":"u55"},
    "665a4e782cb54a878921594ad404740e":{
      "scriptId":"u56"},
    "1f25402a2d0d4c4593f253f9f3232c2d":{
      "scriptId":"u57"},
    "c2d6b282461249d89cda4755c98570eb":{
      "scriptId":"u58"},
    "9d7165d8b63844589b09547126debce2":{
      "scriptId":"u59"},
    "ba474bd91c3b44429ada448acf0b65f4":{
      "scriptId":"u60"},
    "8ffc03c9698a408696cc6ebafe68de76":{
      "scriptId":"u61"},
    "1a6b7b8e234c402e883ff350f0cc5b66":{
      "scriptId":"u62"},
    "636fb0f49455433d8ceaf951b9f12fe4":{
      "scriptId":"u63"},
    "7f9c75615d7e427098c9ecf52a7d1dd0":{
      "scriptId":"u64"},
    "f1bb10fb0c4d4d24b8b96336dac2df50":{
      "scriptId":"u65"},
    "4d8734b90c974e55a4c0a4c1a7bec593":{
      "scriptId":"u66"},
    "54c6c53d8ccd4d6a84c22162982ad5e2":{
      "scriptId":"u67"},
    "eee367e472994facb31962c79b1861b2":{
      "scriptId":"u68"},
    "d6d0634f98e54e4ea42e524c442c3f44":{
      "scriptId":"u69"},
    "0dffaf3bd73d4cbe878d4a3f8fe272bf":{
      "scriptId":"u70"},
    "71fd6b8a9aca4f8d99110bdc75f2d00d":{
      "scriptId":"u71"},
    "7b7b5e71deaa43d5824f9c72022baa6e":{
      "scriptId":"u72"},
    "8876211a636d4ff29d24ea30a48499bd":{
      "scriptId":"u73"},
    "0f0f0a664c02406e8939f0b69b041fd0":{
      "scriptId":"u74"},
    "884be67989cc4b6dbd09c200c121eb46":{
      "scriptId":"u75"},
    "f57404e65e0d4d10b4bff63133fb250b":{
      "scriptId":"u76"},
    "54c7f800643748538925fea3eccdfb92":{
      "scriptId":"u77"},
    "cbea5f1c64464125aad7c0c07cc9b1b1":{
      "scriptId":"u78"}}});